### ISSUE TITLE
Website Design Issues

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#102]
- [x] Make Favicon transparent
- [x] Change deploy logo to a documents logo and adapt text
- [x] Clarify FAQ questions besser and write about ODbL
- [x] Where should we put style reference in the maps section?
- [x] How to work together with Mapbox Studio online? Upload small extract or  just deploy afterwards?

**Comment by lukasmartinelli** [comment]
- [ ] Thanks Switch for the hosting of the MBTiles files

**Comment by lukasmartinelli** [comment]
Add note (ref to tutorial) to tileserver-mapnik

**Comment by lukasmartinelli** [comment]
- [ ] Upload lower zoom levels on download page

**Comment by lukasmartinelli** [comment]
- [ ] Link something in vector maps (repo of mapbox-gl-js-example)
- [ ] Fork mapbox gl styles and work on it to provide example

**Comment by lukasmartinelli** [comment]
- [ ] Change license text in FAQ

**Comment by manuelroth** [comment]
@klokan I created a pull request for the reference to the getting started tutorial on the tileserver-mapnik repository https://github.com/klokantech/tileserver-mapnik/pull/5

**Comment by manuelroth** [comment]
Vector Tileserver link: http://klokantech.tileserver.com/v1/index.json?key=WQ5sRntXphOrWgesmtmU
