### ISSUE TITLE
Puerto Rico extract

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#103]
> I'm Víctor Ramírez from Open Street Map Puerto Rico Team. I recently visited your http://osm2vectortiles.org/ site and was very excited about the prospect of an easier way to set up self hosted vector tile maps. Unfortunately, Puerto Rico was not included in you country extracts. Even though Puerto Rico is a semi autonomous territory of the United States, the mappers here, myself included, usually create and work with maps of the island independently of the rest of the United States. We're working very hard to improve OSM data, as I am sure you can appreciate from our recent changesets, and it would be very useful for us to have a country extract.
>
>Thanks in advance,
>
>Víctor Ramírez
>OSM Puerto Rico Team
> victor.ramirez@gmail.com

**Comment by klokan** [comment]
Please generate the vector tiles from an OSM planet dump for your country yourself.

Here is a step-by-step guide:
http://osm2vectortiles.org/docs/own-vector-tiles/

**Comment by vramirez122000** [comment]
Thank you for the instructions for generating the tiles. If there is a way to setup the coordinate bounds for Puerto Rico and merge them into this project, so as make the Puerto Rico extract available in your site, I would gladly contribute such a patch.

**Comment by lukasmartinelli** [comment]
> Thank you for the instructions for generating the tiles. If there is a way to setup the coordinate bounds for Puerto Rico and merge them into this project, so as make the Puerto Rico extract available in your site, I would gladly contribute such a patch.

If you provide me with the BBOX of Puerto Rico I will add it to the extracts :)

**Comment by vramirez122000** [comment]
Yes!!

min lat: 17.6701939
max lat: 18.7347042
min lon: -68.1976318
max lon: -65.088501

**Comment by lukasmartinelli** [comment]
Finally uploaded it and added to the countries list (I know not politically correct but hope is ok).

https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/puerto_rico.mbtiles
