### ISSUE TITLE
Remove Mapbox dependencies and switch to own fonts and sprites for example Maps

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#105]
The vector maps on http://osm2vectortiles.org/maps/ still use the Mapbox API for fonts and glyphs.
We can use local fonts and glyphs and avoid a Mapbox API Key like in https://github.com/osm2vectortiles/mapbox-gl-js-example

**Comment by hyperknot** [comment]
Did a python script which batch fixes fonts in projects. The lookup table can be extended/customized.
https://gist.github.com/hyperknot/6106b253cfe852f84124

**Comment by lukasmartinelli** [comment]
> Did a python script which batch fixes fonts in projects. The lookup table can be extended/customized.
> https://gist.github.com/hyperknot/6106b253cfe852f84124

I only see this now - sorry. The script is great, we will try to include it into the container to automatically
fix fonts of the users.

**Comment by manuelroth** [comment]
With the new website we don't have any dependancies on mapbox anymore all fonts and sprites are served from https://github.com/osm2vectortiles/mapbox-gl-styles repository
