### ISSUE TITLE
Raster tiles are displayer over semi-transparent osm tiles in Leaflet mode + code

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#106]
For styles such as Streets-Basic, everything is rendered twice, on top of each other, in a semi-transparent way. It is because for some reason both an osm tile and the generated tile is added for Leaflet.

```
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
L.tileLayer('http://192.168.99.100:8080/mapbox-studio-streets-basic/{z}/{x}/{y}.png'
```

The openstreetmap tile layer should be removed, or limited to low zooms (with maxZoom option).

**Comment by lukasmartinelli** [comment]
This is a tileserver-mapnik thinf https://github.com/klokantech/tileserver-mapnik.

@klokan: me and @manuel also wondered why there is always an OpenStreetMap basemap underneath?
It is not tragic because people can remove it but I also think it is a bit confusing.

**Comment by klokan** [comment]
Fixed in OL3 and Leaflet viewers.

The original reason is that our tileviewer project (the frontend of the tileserver-maptiler) has been developed originally for http://www.maptiler.com/ project - and it run on various tile backend (S3/PHP/NODE/local files/etc).
