### ISSUE TITLE
Wrong TileJSON link in docker

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#107]
The port is missing from the TileJSON link, should be:
```
http://192.168.99.100/mapbox-studio-osm-bright/index.json
->
http://192.168.99.100:8080/mapbox-studio-osm-bright/index.json
```

**Comment by lukasmartinelli** [comment]
I don't see it :see_no_evil:  Are you referring to this tutorial?
http://osm2vectortiles.org/docs/serve-raster-tiles-docker/

Source can be found here: https://github.com/osm2vectortiles/osm2vectortiles/blob/gh-pages/docs/serve-raster-tiles-docker.md

I thought I corrected that before the launch.

![serve_raster_tiles_with_docker_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/11912270/c89a3a90-a635-11e5-90dc-8e80a3fa57fc.png)

**Comment by klokan** [comment]
@lukasmartinelli - the OGC WMTS, TileJSON and tutorials for usage in QGIS and ArcGIS on in the sidebar. Just scroll down on the right side.

I see this is a usability problem.
The issue with missing port acknowledged and to be fixed.

**Comment by klokan** [comment]
The port has been added to TileJSON link in tileviewer. I believe this issue is resolved.
