### ISSUE TITLE
Support for PPI / retina / @2x tiles

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#108]
The only thing missing from this amazing project is the support for `@2x` / retina tiles. 

One popular URL structure is the one used by Mapbox, it is supported by Leaflet out of the box:
```
normal: http://b.tiles.mapbox.com/v4/mapbox.streets/6/37/22.png
retina: http://b.tiles.mapbox.com/v4/mapbox.streets/6/37/22@2x.png
```

**Comment by klokan** [comment]
Well, this has been done and it runs already - exactly with the syntax mentioned above.

Try it on the tileserver-maptiler docker or on hosting at http://maps.klokantech.com/.

There is also Static Maps API for requests like: /osm-bright/static/8.82,47.225,15/500x500@2x.png see PR https://github.com/mojodna/tessera/pull/31

**Comment by klokan** [comment]
Does Leaflet switch this automatically in case there is "autoscale:true" in TileJSON metadata?

**Comment by hyperknot** [comment]
@klokan Sorry, I didn't mention I'm talking about docker. Sorry, the server supports it (I just found no mention about it anywhere, so I didn't check), it's just that the sources for Leaflet (and possibly OL, but I haven't used it), is not generating retina-aware code. 

There is no support for `autoscale`. Leaflet 1.0 will have some retina autodetetion, but it's broken at the moment.

The right way to make Leaflet request the `@2x` tiles is this (works both in Leaflet 0.7 and 1.0 beta):
```
L.tileLayer('http://192.168.99.100:8080/mapbox-studio-streets-basic/{z}/{x}/{y}' + (L.Browser.retina ? '@2x' : '') + '.png', {....});
```

**Comment by klokan** [comment]
@hyperknot thank you for the implementation tips.

We have made the retina support for tilesets with autoscale in metadata in the Leaflet and OL3 viewer template - so you should see now in Docker.

Leaflet and OL3 runs automatically in retina on supported hardware.

**Comment by hyperknot** [comment]
Thanks, I can confirm it works well in both Leaflet and OL3.
