### ISSUE TITLE
MD5 checksum for the planet download

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#109]
The planet download is so big, that even over a reliable connection there is a chance it gets corrupted.

Please provide a MD5 checksum so people can verify if their download is correct, like it's done on http://planet.osm.org/

**Comment by lukasmartinelli** [comment]
Good idea. Added the MD5 hash of the world planet file `8f72dc1279d27f0b3e29d27957c7ad7a`.

@hyperknot What do you think about distributing the planet file as torrent. Would that be more convenient for you?

![downloads_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/11912402/9e719fbe-a63b-11e5-917a-46af6e80839b.png)

**Comment by hyperknot** [comment]
@lukasmartinelli I'm downloading it to a server, so a single HTTP download is the most convenient. I believe with torrent the updates would be quite problematic (you'd need to ask all seeders to download a new torrent and stop seeding the old one).
