### ISSUE TITLE
Label rendering problems

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#110]
[docker / raster tiles]: Many of the labels are rendered cut in half. This is probably the hardest / most infamous problem when rendering vector tiles, Mapbox has talked a lot about how hard it is.

Out of the box, these cut lables are quite common in the docker image. I don't know what would be a proper solution, but a common workaround seems to be to raise the buffer zone around meta-tiles. So a meta-tile would be buffered +128 px / +256 px etc. on each side, and cropped afterwards.

What is the default buffer settings used by tileserver-mapnik, and how can we possibly change it when using the docker image?

<img width="336" alt="screen shot 2015-12-20 at 13 11 39" src="https://cloud.githubusercontent.com/assets/494223/11917941/080435b4-a71c-11e5-952d-a6c4ceb890d7.png">

**Comment by sfkeller** [comment]
Why not also raising meta-tiles size? It seems to be close to 2 since there are also duplicate label issues.
![clipboard01 jpg](https://cloud.githubusercontent.com/assets/43340/11917998/ee153ca4-a71e-11e5-897e-1408a8f39c88.png)

**Comment by hyperknot** [comment]
@sfkeller yes, it'd also be a good idea. 

Would it be possible to configure the docker container with something like a config.json in the data folder?

**Comment by klokan** [comment]
Check `buffer-size` on the tm2source for related layers - and compare with MapBox maps - to be sure the buffers are correct in vector tiles.

Tweaking of raster tile rendering is next step - you can study how https://github.com/mojodna/tessera runs internally and prepare an improved config...

Comments on results of your research are welcome - this is an open-source project. Just make what you want - fix the bug for you and share the solution with others!

**Comment by lukasmartinelli** [comment]
> This is probably the hardest / most infamous problem when rendering vector tiles, Mapbox has talked a lot about how hard it is.

You have some resources there we can read/watch to learn how to improve the problem?
I only find bug reports.

> Out of the box, these cut lables are quite common in the docker image. I don't know what would be a proper solution, but a common workaround seems to be to raise the buffer zone around meta-tiles. So a meta-tile would be buffered +128 px / +256 px etc. on each side, and cropped afterwards.


For the vector tiles we use the same buffer configurations Mapbox has defined in https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/#Layer.Reference.
Most of the time for labels we have bigger buffer (the maximum of 256px).
We may increase the buffers in the source project even more - but this increases the size of the MBTiles even more and from what we have tested does not always solve the problem.

**But you think this is a rendering issue?**
There are some tricks that I read on the issues on the Mapbox projects like setting `text-avoid-edges: true;` in CartoCSS - but those seem more like workarounds.

With raster tiles it was not that bad so far even Mapbox has quite alot of label bugs we've seen so far in their official raster maps.

Mapbox GL has even more weird label issues.

![schweizerkarte](https://cloud.githubusercontent.com/assets/1288339/11918660/9911a0d2-a73a-11e5-86f6-9966f1e42b99.png)

**Comment by hyperknot** [comment]
It might be interesting to see how does Wikimedia / Kartotherian solve the issue, I haven't seen a broken label on their maps, it's even better than Mapbox. Their tm2source only has 64 buffers, so I believe it's related to the rasterising part.
https://maps.wikimedia.org
https://github.com/kartotherian/kartotherian
https://github.com/kartotherian/osm-bright.tm2source

You can actually get their PBF info in JSON:
https://maps.wikimedia.org/osm-intl/9/319/191.json

@klokan I opened this issue as a discussion thread, not as a bug report, and I'll contribute whatever I can to this project.

Here are the best resources about vector tile rendering I know about:
* [Dane Springmeyer - Vector Tiles for Distributed, High Performance Rendering of OSM](https://vimeo.com/68095142)
* [Dane Springmeyer - The State of Vector Tiles](https://www.youtube.com/watch?v=se2cd3BMYRY)
* [Dane Springmeyer - Vector tiles for fast custom maps](https://vimeo.com/106228141)
* [Dane Springmeyer - Processing OpenStreetMap Into Vector Tiles](https://vimeo.com/92032328)
* [Advanced CartoCSS Techniques — Alan McConchie, Stamen Design, Seth Fitzsimmons](https://vimeo.com/106848543)
* [Andy Allan: Lightning Map Tiles](https://www.youtube.com/watch?v=NoLJHgqDCzc)
* [How Simplicity Will Save GIS - Vladimir Agafonkin](https://vimeo.com/106112939)
* [Mobile vector map rendering with Mapbox tools — Justin Miller, Mapbox](https://vimeo.com/107472767)
* [Running Your Own Rendering Infrastructure — Alan McConchie, Stamen Design, Seth Fitzsimmons, Stamen Design](https://vimeo.com/107531947)

p.s.: Can you enable the wiki? I'd be happy to put this one in there for example.

**Comment by klokan** [comment]
Wiki enabled

**Comment by hyperknot** [comment]
Thanks, I've collected all the relevant talks here:
https://github.com/osm2vectortiles/osm2vectortiles/wiki/Resources

**Comment by manuelroth** [comment]
- Label rendering problems with mapbox gl is fixed since the following pull request https://github.com/mapbox/mapbox-gl-js/pull/1727
- However label rendering issues can still be found with raster maps, we don't have a solution for this yet

**Comment by sfkeller** [comment]
I've analyzed 

Looking at the data I have some questions. Given tile 9/268/178 there's the place_label class which contains among others following label:

    {
      "geometry": [[2673, 337]], "type": 1, "id": 18, 
      "properties": {
        "osm_id": 1599381299,
        "name": "Frauenfeld",
        "name_de": "Frauenfeld",
        "name_en": "Frauenfeld",
        "name_es": "Frauenfeld",
        "name_fr": "Frauenfeld",
        "name_ru": "\u0424\u0440\u0430\u0443\u044d\u043d\u0444\u0435\u043b\u044c\u0434",
        "name_zh": "Frauenfeld"
        "type": "town",
        "localrank": 1,
        "scalerank": 9,
      }
    }

1. Leaving out "name_ru" (and other name tags) would save space.
2. I observed many place_labels in the tiles which are way outside the extent. That would perhaps save space too?
3. Spec. says, "A feature MAY contain an id field.". Is the value of id (here 18) really "unique among the features of the parent layer"?

**Comment by manuelroth** [comment]
The label rendering problem is fixed as of https://github.com/mapbox/mapbox-gl-js/pull/1727
