### ISSUE TITLE
Rectangular regions missing from vector tiles

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#112]
Some rectangular areas, like the one above Bovec, Slovenia, are missing from the vector tiles. As you can see, it's kind of effecting other providers as well, but somehow the bug's extents is less with Mapbox and with Thunderforest.

Vector tiles:
<img width="687" alt="screen shot 2016-01-07 at 02 08 43" src="https://cloud.githubusercontent.com/assets/494223/12159623/26f85f7e-b4e4-11e5-89fb-5de6f9c5eb8f.png">

Raster tiles:
<img width="873" alt="screen shot 2016-01-07 at 02 14 43" src="https://cloud.githubusercontent.com/assets/494223/12159674/802a6998-b4e4-11e5-93d4-a8c654a05fbf.png">

Mapbox:
<img width="847" alt="screen shot 2016-01-07 at 02 14 51" src="https://cloud.githubusercontent.com/assets/494223/12159682/8bbd8dd0-b4e4-11e5-80b0-abc952af5698.png">

Thunderforest:
<img width="860" alt="screen shot 2016-01-07 at 02 17 27" src="https://cloud.githubusercontent.com/assets/494223/12159706/d4632950-b4e4-11e5-84e8-22b2080f3b5b.png">

**Comment by lukasmartinelli** [comment]
Will be dealt with in #111.

**Comment by manuelroth** [comment]
OSM2VectorTiles v2.0 looks now more like Mapbox.
![osm2vectortiles_with_bright_style](https://cloud.githubusercontent.com/assets/1810384/15497834/f150cbd8-219c-11e6-8f3d-e99863831be9.png)
