### ISSUE TITLE
Stations do not have network set to more specific

### ISSUE THREAD

**Issue by hannesj** [osm2vectortiles/osm2vectortiles#115]
Currently it is impossible to distinguish between different types of stations, e.g. railway and subway stations, as they both have type set to "Station" and network set to "rail" in the poi_label layer. Proper keys for network should come from the [station](http://wiki.openstreetmap.org/wiki/Key:station?uselang=en-US) tag.

**Comment by lukasmartinelli** [comment]
> Currently it is impossible to distinguish between different types of stations, e.g. railway and subway stations, as they both have type set to "Station" and network set to "rail" in the poi_label layer. Proper keys for network should come from the station tag.

Yes we once had all transport POI in a separate table with all the extra attributes needed, but in the current architecture we don't have any `station` value.
We have to reevaluate how to get those attributes, but it is a change that **requires rerendering**.

**Comment by manuelroth** [comment]
@hannesj In [Mapbox Streets v7](https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v7/#rail_station_label) a new layer rail_station_label was introduced. It provides a field maki, which lets you distinguish between different types of stations (subway stations are called `rail-light`, rail station are called `rail`)

**Comment by lukasmartinelli** [comment]
So this is already solved by #204 right @manuelroth? Reopen it if not :grinning:

**Comment by manuelroth** [comment]
@lukasmartinelli Yes, the layer `rail_station_label` has been implemeted in #204, the more specific `network` field will be implemented in #229
