### ISSUE TITLE
Custom Raster Maps broken

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#117]
All raster maps that are hosted from the SWITCH infrastructure seem to be down.
Need to debug the problem. We can shut down the vector tiles server from SWITCH but the raster maps are quite cool, would like
to keep them this way.

Maps served from the Klokantech CDN are still fine.

![collection_of_map_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/12673774/08999a78-c67f-11e5-9425-1bae6fa52375.png)

**Comment by sfkeller** [comment]
Their status does'nt mention problems currently https://twitter.com/switchdrive_op 
Should we send a mail to support?

**Comment by lukasmartinelli** [comment]
> Their status does'nt mention problems currently https://twitter.com/switchdrive_op 
> Should we send a mail to support?

Thanks.
No, probably just a process on the host that hang itself up. It's a host problem not an infrastructure one is my guess.

**Comment by lukasmartinelli** [comment]
Works again.
Removed some other instances we were no longer using on Switch.
