### ISSUE TITLE
Having trouble parsing tile_data bytes from mbtiles data retrieval

### ISSUE THREAD

**Issue by dfdietrick** [osm2vectortiles/osm2vectortiles#118]
I'm trying to write Java code to display the vector tile data, using OpenMap combined with the java-vector-tile decoder.  When I pull the tile_data byte array out of the database, the java-vector-tile decoder doesn't read it correctly.  I've compared the bytes with other tile data I've received from servers, and it seems off - it looks really different, like it's encoded, compressed or something.  I've tried running the bytes through Base64/zip decoding, but that doesn't help.

My question:  is that tile_data byte array compressed or otherwise encoded?

**Comment by lukasmartinelli** [comment]
> I'm trying to write Java code to display the vector tile data, using OpenMap combined with the java-vector-tile decoder. When I pull the tile_data byte array out of the database, the java-vector-tile decoder doesn't read it correctly. I've compared the bytes with other tile data I've received from servers, and it seems off - it looks really different, like it's encoded, compressed or something. I've tried running the bytes through Base64/zip decoding, but that doesn't help.

Nice, didn't know about https://github.com/ElectronicChartCentre/java-vector-tile
The protocol buffer files inside the MBTiles data field are gzip compressed and need to be decoded first.

We do this in our compare tool by @manuelroth 
```javascript
 zlib.unzip(tile, function(err, tile) {
	    if (!err) {
      		var rawTile = new VectorTile(new Protobuf(tile))
      		var tileName = program.z + "-" + program.x + "-" + program.y;
      		var tileInfo = tileInformation.printOutput(rawTile.layers, program.provider, tileName);
      		console.log(tileInfo);
      	}
```
https://github.com/osm2vectortiles/osm2vectortiles/blob/master/tools/compare/tileInfo.js#L33

If you `wget` the file from the server and then parse it with the java-vector-tile decoder, does that work?

**Comment by dfdietrick** [comment]
Thanks Lukas, that was the thing I was missing, to explicitly decompress as gzip.  I used a `GZIPInputStream` and can now parse the tile features successfully.
