### ISSUE TITLE
Roadmap Planning

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#120]
Perhaps we can already collect some ideas and start the discussion before we meet to ease the brainstorming process.

@manuelroth @sfkeller @klokan 

There are different parts where we can focus our attention in the next few months:

Important:
- Fix bugs #116 #113 #114 #112 #111 #110 #85
- Make world map updatable - the big important one #16
- Reduce size of MBTiles #86

Enhancements:
- Improving quality of the map further
- Feature requests by community #115 #95
- Automate and fix extract rendering #124 
- Smarter strategy for avoiding empty tiles #74 

IMHO we can push into different directions (happy to hear your suggestions as well).
- Implement a **offline** GeoName search (very interesting from an academic perspective - there are a lot of tools out there that already solve the problem kind of
  - *OSS*
    - https://github.com/pelias/pelias
    - https://github.com/foursquare/twofishes
    - https://github.com/twain47/Nominatim
  - *Commercial*
    - https://www.mapbox.com/developers/api/geocoding/
    - https://developers.google.com/maps/documentation/javascript/examples/places-searchbox
    - https://www.microsoft.com/maps/choose-your-bing-maps-API.aspx)
- Create offline MBTiles viewer with e.g. QMapBoxGL to realize the OSM on a USB stick idea #72
- Or perhaps even terrain? #119 But this is kind of a quite different project altogether.
- Contribute back to other OSS projects
  - Introduce our changes into Kartotherian (where they would be welcomed according to my recent mail exchange with Yuri)
  - Try migrating OSM Switzerland to vector tiles or perhaps work in the direction of creating a OSM standard map version with osm2vectortiles (including the Carto style)

I would actually really like to push the **offline aspect** of osm2vectortiles in the next half year.
Sure our in comparison to Mapbox Streets the process is open and the data free but if you want to quickly create a custom styled map as small agency you will probably still fall back to the official Mapbox Streets - just for convenience.
But the **offline use case** of osm2vectortiles is something that is really unique and cannot be reproduced by other providers - and never by Mapbox because then they would make the data really easy available.
I am not sure what pushing **offline** might all involve.
But perhaps we can also create some show cases how to use osm2vectortiles with the mobile SDK or build up the extract service and provide a custom SDK so people on mobile can download specific regions via the SDK.

**Comment by muesliq** [comment]
IMHO the issues in the "important" sections are so essential that all points below pale in comparison. 

Regarding future directions:

- Mapbox' geocoding is opensource as well afaik: https://github.com/mapbox/carmen However geocoding is a really really hard thing that many opensource and even commercial projects fail to do properly. That would be project of its own altogether.
- Offline use is just a label, right? Using the Mapbox GL SDKs and osm2vectortiles an offline usecase on iOS and Android can already be implemented today. (+1 for the label.)

**Comment by lukasmartinelli** [comment]
> IMHO the issues in the "important" sections are so essential that all points below pale in comparison.

 Definitely!! Good to know that those are really the top priority ones for you as well. Thanks for the collaboration.

> Mapbox' geocoding is opensource as well afaik: https://github.com/mapbox/carmen However geocoding is a really really hard thing that many opensource and even commercial projects fail to do properly. That would be project of its own altogether.

Also agree, that's why I am hesitant. Some context for you, we need some interesting topics to include into osm2vectortiles to make the new paper more interesting/challenging.

> Offline use is just a label, right? Using the Mapbox GL SDKs and osm2vectortiles an offline usecase on iOS and Android can already be implemented today. (+1 for the label.)

Yes that's only kind of a motto/label/vision to focus on in future. Nothing more. 
This can be implemented today but without guidance, docs and examples it is difficult for people to realize the possibility.

**Comment by hyperknot** [comment]
I can agree with geocoding being a really really hard problem. Many open source and commercial players are trying to do geocoding on OSM data, with various degree of success.

I think what makes osm2vectortiles special is that it's a high-quality, high-performance, easy-to-setup vector tile renderer / server. I would recommend staying on this path and ironing out all the bugs.

**Comment by stephan75** [comment]
See the OSM wiki about http://wiki.openstreetmap.org/wiki/Search_engines

as a collection of all geocoders working with OSM data.
I have no clue about offline features, but generally don't forget about Photon by komoot.de ... mentioned there.

**Comment by klokan** [comment]
Points mentioned as important are without doubts highest on the priority list and are for sure on the roadmap. The project must be cleaned and documented and stabilised and updates must run. I am keen to dig deeper into technical details and tickets in two weeks... This is priority number one.

Other points are for discussion on that meeting... after estimates of effort on more important tasks.

The ideas behind the way HOW the osm2vectortiles project is build can be easily applied on a basic geocoding approach as well - which is crucial for offline use and processing of OSM extracts.
During the vector tile rendering we have in Postgres already a lot of cleaned data in imposm3 tables, with mapped tags and names in multiple languages - I would like to enrich the data and simply export it - to feed an existing fulltext-based geocoder service such as Pelias or the search service behind Swiss GeoAdmin https://map.geo.admin.ch (https://github.com/geoadmin/service-sphinxsearch) or a simple SQLite FTS5 index. We can think about the update process of what we have in the vector tiles in relation to the place search service as well. This is about being able to find what is in the generated vector tiles and zoom to the relevant area.

Preference would be therefore on having bounding boxes and extra rank for fulltext search in the data (derived from Natural Earth + Wikipedia) - and index esp. countries, administrative units, towns, street names and data we put as name into vector tiles. This is a basic version of index of what somebody has in his vector tiles, if he/she generates one from a small OSM extract (such as Switzerland only).

POIs and postal addresses with ZIP and house numbers are lower priority for me personaly, but there are tools and processes in Nominatim and other projects, which can be applied on the PostGIS imposm3 mapping to push this part forward - Andreas has master thesis at HSR about address search processing  (http://wiki.hsr.ch/StefanKeller/PA2EgloffAufgabenstellung) and there is synergy and low hanging fruit in this regards in the osm2vectortiles project. It is the other side of coin.

I don't want to code a new gazetteer service software, we concentrate on automating and scaling of data processing in OSM2VectorTiles anyway...

If there is already fruitful discussion:

- Does anybody know of a single geocoder project, where you can **download ready to use world data** and a docker for the software and have something close to useful for whole world up in minutes running on a desktop? I doubt that, but would love to hear something else...

I mean, can you get of dump of world data to feed https://github.com/pelias/pelias?
There used to be NPI download for Nominatim, but it is gone...
You always ends up with a week of processing of planet dump with osm2pgsql...

BTW Carmen is not THE MapBox Geocoder API...
It makes sense to discuss this on the roadmap meeting for sure.

**Comment by hyperknot** [comment]
I think GeoNames comes closest to the offline processed gazetter data solution, but there the whole Lucene backend is proprietary. So you get the data (in text files), but not the backend needed to query it.

**Comment by muesliq** [comment]
Any estimation when the next release will happen?

**Comment by lukasmartinelli** [comment]
> Any estimation when the next release will happen?

Sorry that we always talk about the next release but you don't see us committing anything :)
Just as context. We will continue development of osm2vectortiles as part of our bachelor thesis which means we will have 3 days a week where we can work and improve this project in after next week. The maintainers will meet all together at 22nd february where we can sketch out the details of the bachelor thesis and then we can tell you about a roadmap after 22nd february. Writing a thesis is a bit more waterfall than agile :)

With next release we usually mean a rerendering of the world which requires at least 1-2 weeks of just computing power.

**Comment by muesliq** [comment]
Cool! Looking forward to the results of the roadmap meeting. 
Great project by the way! :+1:

**Comment by klokan** [comment]
New milestones and tickets are done. Closing this ticket.
