### ISSUE TITLE
Split classification and MBTiles utilities into separate Repos

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#121]
A month ago I split off the code for the SQL code generation of the YAML classifications
into a separate repository https://github.com/lukasmartinelli/classify.

I also moved the MBTiles utility code for the verification, redundancy removal into a separate
project https://github.com/lukasmartinelli/mbtoolbox in the hope it might be useful for other people working with MBTiles.

I thought I was entitled to do this because I wrote 100% of the code and want to maintain them separately as they do solve rather generic problems - but never asked/informed.
Are you okay with this @manuelroth ?

If so we can actually remove the following code, because it is maintained elsewhere
- tools/optimize-mbtiles
- tools/verify
- src/import-sql/generate_sql.py

**Comment by manuelroth** [comment]
@lukasmartinelli I am totally okay with that. Since these new projects will evolve over time, we should just keep in mind that the osm2vectortiles project now depends on them.

**Comment by lukasmartinelli** [comment]
Was a bad idea to separate the classification. I thought it is a more general problem but actually this is pretty tied to our project and not alot of other people can use that. Therefore reintroduced it again in https://github.com/osm2vectortiles/osm2vectortiles/commit/4909ddf17eec423630bfb247e0dc1c881f4c57c2

The mbtoolbox part makes still sense to live separate because it is a utility that can be used very well by other people.
