### ISSUE TITLE
Imposm3 Timestamp

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#122]
Import and play around with importing imposm3 diffs to find out how we can set a timestamp .
For each update of features that imposm3 applies on the database we need to know a timestamp to detect dirty tiles later on.

If we use a `INSERT` trigger we need to detect whether the old record is different from the new one and only then set the timestamp record.
Testing will be done with diffs and data for Switzerland.

**Comment by klokan** [comment]
Tests to be done on diffs of a smaller area - such as osc.gz from http://download.geofabrik.de/europe/switzerland.html

**Comment by lukasmartinelli** [comment]
Played a bit with the diff files. Much dumber approach for versioning might work as well.

1. After the initial import I add a a column `sequence_number` which is the initial OSMOSIS sequence number stored in the `state.txt` file http://download.geofabrik.de/europe/liechtenstein-updates/state.txt `ALTER TABLE <table> ADD column sequencenumber int` and then `UPDATE <table> SET sequence_number=1048`
2. Run the diff imports and after each diff import `UPDATE <table> SET sequence_number=1049 WHERE sequence_number IS NULL`. imposm3 will overwrite the existing sequence number with `NULL` values which is how we can detect what updated.

And we have versioned feature. We ca use timestamp (more practical) instead of sequence number.
This is faster than triggers (doesn't solve the "updated with no actual values changed" problem, but not sure whether this problem actually exists).

Some usage notes.
Don't use Switzerland for playing with diff imports - takes too long. Use Lichtenstein.

```bash
# Download changes for Lichtenstein
 wget http://download.geofabrik.de/europe/liechtenstein-updates/000/001/0{0..75}.osc.gz
# Download state files
 wget http://download.geofabrik.de/europe/liechtenstein-updates/000/001/0{0..75}.state.txt

# Import lichtenstein first
docker-compose up import-osm
# Import changes in import dir
docker-compose up import-osm-diff
```

The new `import-osm-diff` container is actually the same Docker image, just executing a different command.

**Comment by lukasmartinelli** [comment]
## How to import diffs into the database.

1. Given you have downloaded an older PBF file
   `wget http://download.geofabrik.de/europe/liechtenstein-151001.osm.pbf`
2. Run `docker-compose up import-osm` will do an initial import of the PBF file, extract the timestamp of the PBF file and store it as `timestamp` column for each imported OSM table
3. Now you want to download and apply the diffs. Run `docker-compose up import-osm-diff` which will use `osmupdate` to download all diffs until today for the PBF file found in the `import` directory and write them to a `latest-changes.osc.gz` file. This diff file will then be imported with imposm3 diff imports and then the timestamp of that chanages file is updated for all modified rows.

In order for `osmupdate` to work with Geofabrik extracts you need to export set the `OSM_UPDATE_BASEURL` container in the container to `http://download.geofabrik.de/europe/liechtenstein-updates/`

**Comment by klokan** [comment]
@lukasmartinelli - does the import sets the timestamp only on records which have really changed?

If a tag present in OSM raw data, which is ignored by our mapping to SQL tables, is changed/modified/added/deleted, then there is no change for this feature in our database.

This way we can eliminate a lot of the edits in OSM. It sounds like this approach ignores this for now. If it i does - we need a new ticket for solving this properly at later point (BBeta milestone?)

**Comment by lukasmartinelli** [comment]
> If a tag present in OSM raw data, which is ignored by our mapping to SQL tables, is changed/modified/added/deleted, then there is no change for this feature in our database.

A tag that is not explicitely defined in `mapping` will cause no deletes or inserts into the database.

It is possible however that a tag that we don't map to columns (in `fields`) has changed (e.g. `name:de_ch` for a POI `shop=icecream`) and therefore still triggers the update but with the same values.

Before we implement detection of real updates we must ensure that this case **really** occurs #132. In the best case imposm3 already ignores changes to attributes that are not mapped to columns e.g. if not it makes sense to implement that directly into imposm3 since it would be quite a useful feature.

**Comment by klokan** [comment]
Thanks! This is what I meant.

**Comment by lukasmartinelli** [comment]
Btw. updating the timestamp on several million rows after importing does slow down the import quite a bit (on top of the additional time required for diffed imports which is factor x2).

Would be great imposm3 could write the timestamp of the PBF directly into the database at a later stage.

**Comment by lukasmartinelli** [comment]
Okay setting the timestmap per `UPDATE` takes as much time as importing in the first place. Didn't think that just updating one column takes so much time.
