### ISSUE TITLE
Evaluate depth search approach 

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#123]
- Start on low zoom level(z0), run queries with timestamp constraint (where timestamp > 1456149839), if nothing comes back => do the same process for a higher zoom level(z1), until something comes back => now we now that this tile needs to be rerendered
- Find the highest possible zoom level where something has changed

**Comment by lukasmartinelli** [comment]
Given we want to evaluate dirty tiles for zoom level 4 we start at zoom level 1.
1. We take the query of the source project and replace the zoom level with 4 and the bounding box of one zoom level 1 tile
2. If something is dirty in zoom level 1 we do the queries for zoom level 4 again but with the bounding box of zoom level 2 tile
3. Go down deeper with query for zoom level 4 and bbox of level 3 tile.
4. Now we are at the targeted tile zoom level and have the actual tiles that are dirty.

**Comment by klokan** [comment]
A code for generating list of relevant tiles by traversing mercator tile quadtree directly with SQL from: http://javisantana.com/2014/10/22/traversing-quadtree.html
```
    WITH RECURSIVE t(x, y, z, e) AS (
      -- root node (0, 0, 0)
        SELECT 0, 0, 0, exists(select 1 from ships where the_geom_webmercator && CDB_XYZ_Extent(0, 0, 0))
      UNION ALL
        -- coordinate for the children
        SELECT x*2 + xx, y*2 + yy, z+1,
               exists(select 1 from ships where the_geom_webmercator && CDB_XYZ_Extent(x*2 + xx, y*2 + yy, z+1)) from t,
               -- iterate over 4 children
               (VALUES (0, 0), (0, 1), (1, 1), (1, 0)) as c(xx, yy) 
               -- only for tiles with geometry and up to zoom level 8
               where e AND z < 8
    )
    SELECT z, x, y FROM t where e
```
we can use TileBBox() from https://github.com/mapbox/postgis-vt-util instead of CDB_XYZ_Extent().

**Comment by lukasmartinelli** [comment]
The approach from #129 is superior IMHO and we should no longer pursue the approach from #123.

With this approach I mean detecting changes by executing the queries from the tm2source file and probing whether something changed.
