### ISSUE TITLE
Export list of dirty tiles to MBTiles

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#125]
- Talk directly to node-mapnik, so that we can render single tiles and get information about zero size tiles

**Comment by manuelroth** [comment]
- This helps fix https://github.com/osm2vectortiles/osm2vectortiles/issues/74

**Comment by lukasmartinelli** [comment]
I suggest we implement not a direct replacement of the export worker at first but a tool similar to `tl` , `tilelive-copy` that takes a list of dirty tiles and renders the tiles from `tm2source` into a tilelive sink (for simplicity MBTiles at first, later serialtiles).
If someone is finishing up #129  (at the moment it looks really promising) another one can work on #125 so we can test the tile updates for real asap.

**Comment by lukasmartinelli** [comment]
Pleasant surprise. `tilelive-copy` actually supports a `list` rendering scheme which allows rendering a list of dirty tiles into a MBTiles file (which can then be patched to the original MBtiles file).

https://github.com/osm2vectortiles/osm2vectortiles/blob/feature/detect-dirty-tiles/src/export/export-list.sh

Added an additional `export-list` script to the exisisting `export-local` and `export-worker` scripts.

This removes the need of rewriting the export to support rendering dirty tiles.

The current naive implementation already supports detecting dirty tiles and rerendering them (not yet distributed).

```bash
# Writes a tiles.txt to the export folder of the latest dirty tiles
docker-compose up detect-dirty-tiles
# Renders the missing tiles from tiles.txt to a new MBTiles file that can then be patched.
docker-compose up export-list
```

**Comment by lukasmartinelli** [comment]
The export list feature works so far. It is not distributed yet but it is enough to rerender dirty tiles at smaller scale in the next sprints.
