### ISSUE TITLE
Issue in vectortiles tileserver?

### ISSUE THREAD

**Issue by yohanboniface** [osm2vectortiles/osm2vectortiles#127]
Having a quick look at osm2vectortiles, and doing a quick test, I see that `.pbf` URLs return images.

For example:

<pre>
~ http --headers http://osm2vectortiles-1.tileserver.com/v1/18/132805/90194.pbf
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
CF-RAY: 2798cb578243271a-FRA
Cache-Control: public, max-age=14400
Connection: keep-alive
Content-Length: 355
Content-Type: image/png
Date: Wed, 24 Feb 2016 05:33:12 GMT
Etag: 555d180572bbf5452df00af361c96572
Expires: Wed, 24 Feb 2016 09:33:12 GMT
Last-Modified: Tue, 15 Dec 2015 17:55:54 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d369abe5c1cb183690a616342ea43495c1456291992; expires=Thu, 23-Feb-17 05:33:12 GMT; path=/; domain=.tileserver.com; HttpOnly
Vary: Accept-Encoding
</pre>

Sounds like an issue to me.

**Comment by klokan** [comment]
Well - tiles are not requested on zoom level 18 - as metadata tells maxzoom 14.
We have fixed this in source code in December - but forgot to deploy the latest version.
The new version returns 404 error instead.

**Comment by yohanboniface** [comment]
> Well - tiles are not requested on zoom level 18 - as metadata tells maxzoom 14.

Ah, oops, missed that, thanks. A 404 will be clearer though, indeed :)

I'll let you close or not the issue given that you assigned a task.

Thanks for your answer :)

**Comment by klokan** [comment]
Latest version of the tileserver deployed. Now there is 404 error message instead.
