### ISSUE TITLE
Imposm Mapping Schema - 'Used Keys' diagram -  for all osm keys 

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#131]
for a web page: http://osm2vectortiles.org/docs/imposm-schema/

idea:
Is it possible to add  the  all 'referenced'  osm keys to this diagram?
Like the : `addr:city`, `addr:country`, `addr:postcode`, ...  from the `fields:` YAML object.
( or create an another  full 'crossref diagram' / table  )

my query for testing:

``` bash
$ cat mapping.yml | grep key: | cut -c12- | sort -u
addr:city
addr:country
addr:housenumber
addr:place
addr:postcode
addr:street
admin_level
bridge
capital
int_name
layer
maritime
name
name:de
name:en
name:es
name:fr
name:ru
name:zh
oneway
population
ref
scalerank
service
tunnel
website
```

**Comment by lukasmartinelli** [comment]
Yes we can do that. I had it at one point - problem is it is just a really huge diagram where almost too much is displayed.

I will generate a new diagram for you when I get to it.

**Comment by ImreSamu** [comment]
> a really huge diagram where almost too much is displayed.

I agree, usability is important.
For me a simple xref table is perfect in the future.  ( individual osm key ->  sql tables -> layers )

Thank you in advance!
