### ISSUE TITLE
How does imposm3 deal with unmapped Tags

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#132]
Test and figure out how imposm behaves for unmapped tags<->fields. #112 

> It is possible however that a tag that we don't map to columns has changed (e.g. `name:de_ch` for a POI `shop=icecream`) and therefore still triggers the update but with the same values.

> Before we implement detection of real updates we must ensure that this case even occurs. In the best case imposm3 already ignores changes to attributes that are not mapped to columns e.g. if not it makes sense to implement that directly into imposm3 since it is quite a useful feature.

**Comment by lukasmartinelli** [comment]
We just played around by creating manual `.osc` file and found at that if a tag changed that we don't have in our table columns it will still be updated.
And not via a SQL `UPDATE` but with a `DELETE` and then `INSERT`.
We can perhaps reduce the amount of dirty tiles by ensuring we only calculate dirty tiles for rows that have **really** changed.

**Comment by klokan** [comment]
+1 This is very important!

**Comment by klokan** [comment]
Maybe a patch of imposm3 - or how do you want to detect this?

**Comment by lukasmartinelli** [comment]
Goal of this issue was to figure out how it works. Implementation will continue in a different issue.

The implementation in #191 using triggers is sadly too slow at the moment for an entire world diff import. Glad we didn't use triggers earlier for detecting the dirty tiles.
