### ISSUE TITLE
documentation on extract vectortile creation misses BBOX

### ISSUE THREAD

**Issue by stephankn** [osm2vectortiles/osm2vectortiles#135]
The documentation on

http://osm2vectortiles.org/docs/own-vector-tiles/

misses to mention that the BBOX specified in `docker-compose.yml`
(`BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"`) is supposed to work with the example extract of Zurich.

To create other extracts the BBOX needs to be ajdusted.

Please update the documentation. Would also be nice on having some ideas on how to get a worldwide low-zoom coverage added to the extract.

I currently consider to merge in the missing tiles from your extract, but would be great if this could already be done during creation of the mbtiles file.

**Comment by manuelroth** [comment]
- Improved the documentation of own-vector-tiles to include instructions to modify the BBOX environment variable in the docker-compose.yml file https://github.com/osm2vectortiles/osm2vectortiles/commit/92f47d9beb81f691d006feeb08fae2b25a394cdf
- Added optional instructions to merge lower zoom levels (z0 to z5) into extract https://github.com/osm2vectortiles/osm2vectortiles/commit/d39d57bb3164d9e725e3034313b61f3b4b47be12

@stephankn Would appreciate your feedback on this. If you have further improvements, it would be nice if you could create a pull request on the [gh-pages branch](https://github.com/osm2vectortiles/osm2vectortiles/tree/gh-pages). You can find the own-vector-tiles documentation in the [docs/own-vector-tiles.md](https://github.com/osm2vectortiles/osm2vectortiles/blob/gh-pages/docs/own-vector-tiles.md) file.
