### ISSUE TITLE
Import PBF Data Error

### ISSUE THREAD

**Issue by miccferr** [osm2vectortiles/osm2vectortiles#136]
Hi,

I'm following [this guide](http://osm2vectortiles.org/docs/own-vector-tiles/) to generate my own vector tiles.

While running the command `docker-compose up -d postgis` I get the following error:

`import-osm_1 | Please mount the /data/import volume to a folder containing OSM PBF files.`

The data volume var seems to be defined on this line in the  `import-osm/import.sh` script:

`readonly IMPORT_DATA_DIR=${IMPORT_DATA_DIR:-/data/import}`

Hence, I believe it's a docker error (which admittedly I'm not that knowledgeable of..).
Still, in the light of issue #47 , I think it might be useful to be more explicit regarding where the  `.pbf` files should be downloaded.

The [same page](http://osm2vectortiles.org/docs/own-vector-tiles/) refers to an `import` folder, but it's a bit generic, i.e. `Download a PBF and put it into the local import directory.` 

Do you mean the `import-osm` folder? 

What am I doing wrong/missing here?

Thanks in advance!

**Comment by lukasmartinelli** [comment]
I just added empty `import` and `export` folders. They are usually created by docker-compose at startup but as someone who starts the project the first time one cannot know where to put the PBF file.

There is a `import` folder in the root project now where you need to put the PBF file.
After that if you run `import-osm` it should work.

Thanks for the feedback. Tell us if that works for you.
We try to make the docs more clear - or you can create a PR yourself

**Comment by miccferr** [comment]
Hey there,

Thanks for the super-fast answer!

Unfortunately I'm still getting the same error:

`WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
Creating osm2vect_cache_1
Starting osm2vect_pgdata_1
osm2vect_postgis_1 is up-to-date
Creating osm2vect_import-osm_1
Attaching to osm2vect_import-osm_1
import-osm_1 | No PBF files for import found.
import-osm_1 | Please mount the /data/import volume to a folder containing OSM PBF files.
osm2vect_import-osm_1 exited with code 148`

In addition to your input, I tried to recreate the folder structure with `data/import` as specified in  the `import.sh` script in the root of `osm2vectortiles ` folder. 

Maybe I'm missing something with docker? 
My steps so far:

- I've downloaded Docker Compose
- cloned this repo/ cd'd into it
- run `docker-compose up -d postgis`
- downloaded `.pbf` data `wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf`
- run `docker-compose up import-osm`

I'm on a mac with:
- OSX 10.11.1
- docker-compose version 1.6.0, build d99cad6
- Docker version 1.10.2, build c3959b1

**Comment by lukasmartinelli** [comment]
Sorry it is very confusing. The `/data/import` location is actually the volume that is mounted into the Docker container. If you look in the `docker-compose.yml` file you can see that actually the local folder `import` is then mapped to the Docker container volume `/data/import`. The Docker ecosystem is not that approachable to be honest.

So you need to put the downloaded PBF file into the `import`.
Change your workflow to:

- I've downloaded Docker Compose
- cloned this repo/ cd'd into it
- run docker-compose up -d postgis
- **cd `import`**
- downloaded .pbf data `wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf`
- run docker-compose up import-osm

**Comment by miccferr** [comment]
Aha! I see..this is much clearer now. 

Still it gives me the same error :(
It behaves like there's either no .pbf file, nor the mapping works as expected.

Just to be sure, once I download and cd into the repo, I also need to run `make` to setup all of Docker's images etc, right?

**Comment by lukasmartinelli** [comment]
> Just to be sure, once I download and cd into the repo, I also need to run make to setup all of Docker's images etc, right?

We use the `Makefile` only to use the latest images locally. When you use `docker-compose` it should automatically pull down the latest images from Docker hub we prebuilt for you.


> It behaves like there's either no .pbf file, nor the mapping works as expected.

We once had issues before with Docker and OSX. Usually Virtualbox mounts the directory into the VM where Docker is running and everything is fine. If you installed the Docker toolbox

**Comment by lukasmartinelli** [comment]
So it definitly was a Docker issue :grin: Happy mapping @miccferr and I hope you can still use osm2vectortiles even though it lacks terrain data.

**Comment by nitinlkoin1984** [comment]
I am having the same issue. Can you elaborate how this issue was resolved.

**Comment by lukasmartinelli** [comment]
> I am having the same issue. Can you elaborate how this issue was resolved.

Using OSX? Are you mounting the import folder in the docker compose to a special folder?
Or elaborate a bit.

Have you put the PBF file into the `./import` folder at the repo root?

What happens is because Docker runs on VirtualBox on OSX mounting the filesystem raises weird issues. But we no longer had problems with this now.

**Comment by nitinlkoin1984** [comment]
I am using windows 7. The problem I am facing is that docker virtual folder is not being mapped to a physical folder. I did place the .pbf file in ./import folder at the root.

**Comment by lukasmartinelli** [comment]
> I am using windows 7. The problem I am facing is that docker virtual folder is not being mapped to a physical folder. I did place the .pbf file in ./import folder at the root.

Don't know how Docker on Windows works - but another thing you can try is if you have Kitematic (https://kitematic.com/) or so installed you can click on the volume folders there to open the actual mounted location.

Otherwise I recommend running it on a Linux virtual machine (most Windows guys at the uni use Docker this way - but I know this recommendation is never cool).

**Comment by nitinlkoin1984** [comment]
I am doing is that way. Opening Kitematic and mapping the folders to physical folders. At the end of the process I get a very small file. For example the houston extract on your website is 55mb. My houston extract following the process outlined is 155 kb

**Comment by lukasmartinelli** [comment]
Good it worked. We merge the lower zoom levels of the planet in the
extracts so zooming out looks nice - but 155KB seems really tiny..

**Comment by nitinlkoin1984** [comment]
I got it to work. I created an Austin extract which was 25mb. I think the problem is with the folder and volumes permissions on windows. I had to "enable volume" in Kitematic for export image.

Everything is working now. Thanks for your help. These tools are amazing and much quicker and easier to deploy then other solutions.

**Comment by sfkeller** [comment]
Nice! This "enable volume" in Kitematic for export image could be added to the docs for Windows users.

**Comment by beikehanbao23** [comment]
maybe u have me the  permission of the folder

or the SE of linux    
just rum cmd:         setenforce 0
