### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#14]
Create `docs` folder with Markdown files. Markdown can then be exported to [readthedocs](https://readthedocs.org/). Documentation should make it easy for sysadmins and designers to get started quickly.

Because the project consists of stitching software together, this puzzle needs to be explained.
Experiences and project management and thesis related thing should not belong to the project documentation.

**Comment by lukasmartinelli** [comment]
I want to keep the documentation on our own http://osm2vectortiles.org page where we also provide download links, introduction etc. We can still write Markdown like before and just use Github Pages. That's the easiest way to do it where we have the most control.

Read the docs gives better options (with Sphinx and restructured text) for generating documentation but by controlling the page ourselves we can make it look better and more uniform and can also build our own custom stuff into the page (like Mapbox GL samples or data comparisons).

Changes on http://osm2vectortiles.org/ are online (not looking good on mobile though).

![5wvktbmhif](https://cloud.githubusercontent.com/assets/1288339/11015762/b575a066-856b-11e5-91f4-172458c56968.gif)

**Comment by lukasmartinelli** [comment]
I don't know where to best put this but a few things I noticed when we talked with people about the project

- People care about labels and label ranks -> new idea there was using Wikipedia links of OSM data to determine importance (but that's a topic for itself)
- People don't like that data in the vector tiles might be missing because it is not considered important by us
- People do like that there is an open alternative to the all mighty Mapbox
- It was asked pretty quickly, how the MBTiles would get updated
- Disputed borders really are kind of a undecided problem. People map the border and set `disputed=yes`. And borders are the relations that are updated the most.
- People are also interested in rendering MBTiles themselves (so making our PostGIS / export stack approachable would make also sense - it is not just for us)
- Documentation will be absolutely crucial - explaining the project on the site and helping as fast as possible to get to the goal of MBTiles is important
- Packaging tessera/Mapbox GL locally makes for an extrem good demo use case even though it is perhaps of limited use. One can just give the people an executable (on a branded stick?), they click on it and choose an MBTiles and voilà - a nice map rendered from **own** data from OpenStreetMap. This will get people talking. Docker while very powerful and actually the end goal is an additional obstacle when just trying to get started as fast as quickly (My guess is especially for Windows people)

**Comment by klokan** [comment]
Improved documentation for usage on a small OSM planet dumps (cities extracts, etc) without the cluster is necessary... ensure and test the main `export` docker runs directly - without access to cloud buckets and queues - if the AWS variables are not set by the user...

**Comment by manuelroth** [comment]
We decided to take a question based approach with the documentation. We write down the most common questions which will probably be asked, and answer them with tutorials and text. The separation between user and dev documentation will stay. 

#### User Documentation
The user documentation describes how to get started with OSM Vector Tiles and how to create a custom style. 

#### Dev Documentation
Whereas the dev documentation focuses on which data is included, how to host them, creating own extract, adding own data.
