### ISSUE TITLE
Check for duplicate identification of dirty tiles

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#141]
- The current implementation of dirty tile detection writes the identified tiles into a file, but it doesn't check if the tile was already identified before
- This results in rendering a tile twice instead of once
- This issue is fixed, if all tiles in the dirty tiles file are distinct

**Comment by lukasmartinelli** [comment]
It is possible to do it in SQL as well but the advantage to do it in JS is that we have lots of smaller queries for the zoom levels (which puts less load on the PostgreSQL server). Plus we have stats about what changed on each level.

**Comment by lukasmartinelli** [comment]
> This issue is fixed, if all tiles in the dirty tiles file are distinct

You can use Underscore `uniq`.
http://underscorejs.org/
