### ISSUE TITLE
Optimize Speed of Imposm3 Timestamp 

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#144]
Future improvement of #122 

Didn't expect that but doing an `UPDATE` on planet is painfully slow. The planet import is now setting the timestamp to the initi<l day since 1.5 days - much longer than just writing the rows with imposm3 took.

Need to think about an other more performant way like
- tuning PostgreSQL
- writing the timestamp of a PBF via imposm3 (write a imposm patch in Golang)
- instead of updating rewriting the entire table via `COPY`
- run the `UPDATE` queries in parallel
- run PostgreSQL in the "Running with Scisscors mode" (that helped before for use cases like that because we don't care so much about ACID in this project) http://www.databasesoup.com/2015/02/running-with-scissors-mode.html

I think the `UPDATE` approach is nice for when the rows have changed via imposm diff import but for setting the timestamp on the initial import it is too slow.

**Comment by lukasmartinelli** [comment]
> writing the timestamp of a PBF via imposm3 (write a imposm patch in Golang)

Tried tuning PostgreSQL but update just takes too long to be practical. The bigger problem is that the database size actually doubles (until the VACUUM is done) which means it no longer fits on the 375GB SSD we have attached to the machines - therefore the only option is to add the timestamp at import time.

This has a higher priority because until the timestamp is not there we cannot actually test performance of the diff update approaches.

Will dig into the imposm3 code now and check how we best write an additional column at import time and then add a new field type to imposm3.

**Comment by hyperknot** [comment]
Here are the best documents optimising PostgreSQL for full planet OSM import, in case you haven't read them yet. Also, what helped me (strangely!) was to add a huge swap partition (like 60 GB), and just let it swap. In my case it meant using cache 26000 on a 32 GB server, but that was with osm2pgsql.

[2010-07-10-rendering-toolchain-performance.pdf](https://github.com/osm2vectortiles/osm2vectortiles/files/161093/2010-07-10-rendering-toolchain-performance.pdf)
[ramm-osm2pgsql-sotm-2012.pdf](https://github.com/osm2vectortiles/osm2vectortiles/files/161095/ramm-osm2pgsql-sotm-2012.pdf)
[osm2pgsql-performance.pdf](https://github.com/osm2vectortiles/osm2vectortiles/files/161094/osm2pgsql-performance.pdf)

**Comment by lukasmartinelli** [comment]
> Here are the best documents optimising PostgreSQL for full planet OSM import, in case you haven't read them yet. Also, what helped me (strangely!) was to add a huge swap partition (like 60 GB), and just let it swap. In my case it meant using cache 26000 on a 32 GB server, but that was with osm2pgsql.

Thanks a lot of @hyperknot. Didn't know all of those links.
We already did tuning on the import but we can certainly still improve it.
I only did PostgreSQL settings tuning so far - no tuning of the machine settings. Worth investigating there as well. What we found out there is that for the imposm phase having fast CPU is most important and then later IO becomes the bottleneck (there it helps to have fast SSDs).

We run the import on 52GB memory machines with 8 cores and then store the database files on a shared disk that we attach to the workers and then copy the DB files over to the local SSD disks of the workers. And then we start the rendering.

But in this issue the problem is actually adding a timestamp to each row that contains the date of the OSM snapshot in the PBF file in the most performant way possible.

**Comment by lukasmartinelli** [comment]
PR https://github.com/omniscale/imposm3/pull/94 adds a `pbf_timestamp` to imposm3 which makes setting the timestamp initially really fast.
I can't figure out the timestamp for the current diff import in the field type therefore this setting timestamp of diffed rows works with `UPDATE` so far.

> This introduces a new field type pbf_timestamp which will set the value to the timestamp defined in the PBF Header.
