### ISSUE TITLE
Prepare FOSS4G proposal (deadline 21.3.2016)

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#147]
## FOSS4G information

- http://2016.foss4g.org/programme.html
- http://2014.foss4g.org/abstract-review-process-for-foss4g-2014/index.html
- Running Your Own Rendering Infrastructure: https://vimeo.com/107531947
- [http://2014.foss4g.org/abstract-review-process-for-foss4g-2014/index.html](Abstract Review process FOSS4G)

## FOSS4G videos for inspiration

- https://vimeo.com/106228141
- https://vimeo.com/144088224
- https://vimeo.com/142335630
- https://vimeo.com/107531947

**Comment by klokan** [comment]
I am going to make a draft.

**Comment by manuelroth** [comment]
We discussed today, that we will submit two separat proposals for FOSS4G.
First proposal:
- Explaining the process of vector tile creation
  - Import OSM, Natural Earth, Custom data
  - Update scaleranks
  - Export process
- Step-by-Step instructions (from OSM data to vector tiles)
- Demo: Vector Tiles creation of small extract

We will create a first draft this week.

**Comment by manuelroth** [comment]
FOSSGIS Proposal:
Einleitung:
Das Projekt OSM2VectorTiles bietet einerseits einen Workflow um selbst Vektor Tiles aus OpenStreetMap zu erstellen und bietet diese andererseits gratis zum Download an.
Der Workflow um die Vektor Tiles zu erstellen ist Open Source und kann verwendet werden um eigene Vektor Tiles zu erstellen. Dies ermöglicht jedem eine selbst gestaltete Karte der gesamten Welt zu erstellen und anzubieten, ohne Kenntnisse von PostGIS und Mapnik zu haben.

Inhalt:
In der Präsentation zeigen wir, wie man in wenigen Minuten seine eigene Karte designen und verwenden kann. Wir führen zuerst durch ein simples Kartendesign in Mapbox Studio 
und zeigen wie man eine eigene Karte ohne Abhängigkeiten auf externe Anbieter zur Verfügung stellt. Danach zeigen wir wie man das Gleiche mit einer lokalen Kopie der Daten erreichen kann.
Im Gegensatz zu anderen Kartenanbietern sind die Daten frei verfügbar, somit lassen sich auch Offline Applikationen auf Desktop und Mobile umsetzen. Mit dem Mapbox GL SDK können Vektor Tiles auch offline auf dem Smartphone mit einem eigenen Kartenstil verwendet werden.

Ziel:
Die Zuhörer wissen nach unserer Präsentation wie sie eine selbst gestaltete Karte erstellen und veröffentlichen können. Zudem können sie die vom OSM2VectorTiles Projekt zur Verfügung gestellten Daten verwenden, um ihre Karte auch Offline anbieten zu können.

**Comment by lukasmartinelli** [comment]
*FOSS4G Proposal - v0.1*

## Create Vector Tiles from OpenStreetMap

In the talk we want to show people how to create their own vector tiles based on OpenStreetMap and other external data.
The talk will cover import tools like imposm3 to import 
the data into PostGIS and then shows how to generate vector tiles using tilelive and Mapnik.
We will explain the open source workflow we use at OSM2VectorTiles to prerender global vector tiles and instruct you how to adapt the workflow to fit your vector tile needs.

OSM2VectorTiles is a project simplifying installation of free and offline world maps powered by OpenStreetMap. It offers freely downloadable OSM vector tiles, and a set of open-source tools for use and generating of the maps.

**Comment by lukasmartinelli** [comment]
@klokan We created a first draft of the proposal. We will focus a bit more on how to create vector tiles and what tools to use and then go over and show how to adapt OSM2VectorTiles for your needs.

What would @hannesj @hyperknot @ImreSamu like to hear in a FOSS4G talk about OSM2VectorTiles (or lessons learnt from the project)?

**Comment by ImreSamu** [comment]
> What would like to hear in a FOSS4G talk about OSM2VectorTiles

my list:

Used open source technologies & projects.

Benchmarks and data sizes :
* planet
* big country (  osm pbf extract size:  1-5 GB )
* small country (  < 500Mb )

Future roadmap 

Extending the data modell & customisation:
* How to add new language code 
* How to add new osm keys ( like whllechair= )
* How to add new layers 

Comparing the Alternative solutions with osm2vectortiles
* Mapzen ,  Kartotherian, ...

**Comment by lukasmartinelli** [comment]
> Benchmarks and data sizes :
> 
> planet
> big country ( osm pbf extract size: 1-5 GB )
> small country ( < 500Mb )
> Future roadmap
> 
> Extending the data modell & customisation:
> 
> How to add new language code
> How to add new osm keys ( like whllechair= )
> How to add new layers
> Comparing the Alternative solutions with osm2vectortiles
> 
> Mapzen , Kartotherian, ...

We should definitly add most of them to documentation. We can show one or two customization scenarios at FOSS4G. 

Yes we need to differentiate more cleanly between Mapzen (which is not offline) and Kartotherian (which we try to collaborate with).

Benchmark wise we have a lot of data layour around in the issues. Just for your interest 
rendering the entire world takes a `52` GB RAM machine with 8 cores using 8? Mapnik workers **5 weeks**. But we use 5 machines so we get down the actual time of rendering the entire world to one week. For updates we hope we can get by with much less infrastructure.

**Comment by lukasmartinelli** [comment]
@klokan Could you send us your proposal draft for the second part that is focusing on using the vector tiles?
Would be best if we have the proposal done today.

**Comment by klokan** [comment]
Will jump on it soon.

**Comment by klokan** [comment]
My suggestion for the proposal for the two talks:

### World on a USB stick: turning OpenStreetMap to vector tiles

OSM2VectorTiles.org project offers free downloadable vector tiles ready to use by people interested in hosting custom base maps on their own infrastructure. The whole world fits on a USB stick, and can be served from an ordinary web hosting and styled and enriched to make beautiful and fast maps for web and mobile applications.

This talk will demonstrate the open-source tools and process used to generate the world vector tiles (called Open Streets) and it will show how the same software stack can be applied to create customised vector tiles from your own geodata or OpenStreetMap Planet extracts.

Thanks to the Docker containers and open-source tools such as Mapnik with vector tile extension, PostGIS, TileLive and Mapbox Studio Classic the process is straightforward and repeatable. The OSM2VectorTiles process allows also updates of the tiles on regular bases. Practical tips and live demonstration of how to generate custom tiles is going to be presented.

### TileServer GL: Serving vector tiles to the web, mobile apps, desktop GIS, raster tiles and static images

Hosting base maps with your custom look&feel, even for the whole world, is thanks to the OSM vector tiles and open-source software easy and achievable even with a low-end hardware. Such maps can power web sites, mobile apps, large production services as well as run behind firewalls, or completely offline - for example on the board of an airplane.

This talk demonstrates examples of practical use of the vector tiles downloaded from the OSM2VectorTiles.org project or any other tiles in MVT format generated with open-source tools or other software.

A new open-source project called TileServer GL is going to be presented. This project exposes map styles written in JSON into web applications using WebGL powered by MapBox GL JS library as well as into native mobile SDKs for iOS and Android. In the same moment the style can be rendered on server side with the OpenGL ES 2.0 graphic acceleration into traditional raster tiles and served to older web browsers using any of the tranditional clients such as Leaflet or OpenLayers. Raster tiles are OGC WMTS compatible - allowing opening of the maps in destkop GIS software such as QGIS or ArcGIS. The maps can be served with variable scale (Retina / HiDPI) or drawn in defined extent and zoom for printing purposes or static illustration.

Alternative projects are going to be presented as well - such as TileServer-Mapnik derived from Tessera & TileLive for serving maps made with CartoCSS .tm2 styles in MapBox Studio Classic.
The vector tiles itself could be hosted even in a basic unpacked form in directories or served from SQLite/MBTiles with basic scripts directly. 

All these project shows how to use vector tiles according specification made by MapBox and all the related popular open-source projects and in the same moment retain control of the data and costs, while hosting maps on a custom infrastructure.

**Comment by manuelroth** [comment]
Thanks for your suggestion. We took the best of both proposal drafts and submitted the final proposal.

**Comment by klokan** [comment]
@manuelroth please add "petr.pridal@klokantech.com" as another speaker.

**Comment by manuelroth** [comment]
@klokan Added you as another speaker

Following the proposal we submitted:

The advantages of vector tiles over traditional raster tiles are well known. There are already a handful of vector tile provider present, but they may not always serve your use case optimally. After this talk you will know how to create your own custom vector tiles based on OpenStreetMap and will know the tools and processes you need to use.

The talk will cover how to import OpenStreetMap data into PostGIS and then shows how to generate vector tiles using Tilelive and Mapnik. We will present the open source workflow we use at OSM2VectorTiles to prerender global vector tiles and instruct you how to adapt the workflow to create custom vector tiles. Thanks to Docker and tools such as Mapnik, PostGIS, Tilelive and Mapbox Studio Classic the process is straightforward and repeatable.

The OSM2VectorTiles project offers free downloadable vector tiles ready to use by people interested in hosting custom base maps on their own infrastructure. The whole world fits on a USB stick and can be served from an ordinary web hosting and styled and enriched to make beautiful and fast maps for web and mobile applications.

**Comment by lukasmartinelli** [comment]
Yesss!!! The FOSS4G talk got accepted! 
Thanks for voting and helping to prepare the draft!

**Comment by sfkeller** [comment]
Congrats! Actually you already tweeted about before :-O

**Comment by manuelroth** [comment]
So, @lukasmartinelli and me are going to be at [FOSS4G](http://2016.foss4g.org/home.html) somewhere between 24th and 26th of August and at [FOSSGIS](http://frab.fossgis-konferenz.de/de/2016/public/schedule/1) on the 5th of July (9.30 AM GI Studio). @ImreSamu @hannesj @muesliq @hyperknot @numenor do you plan to attend one of these conferences, would be a great chance to meet you guys in person after all these great contributions, ideas and discussions.

**Comment by hyperknot** [comment]
I totally admire your work, and huge congrats for being accepted, but I'm
afraid I won't be able to pay 590-750 EUR + travel + accommodation for the
3 days of attending the conference (which started with Free in its name
once...), hopefully we can meet once in the future!

**Comment by ImreSamu** [comment]
other conference for presenting: 
**"Propose your session to State of the Map 2016!  ( The deadline is May 21, 2016. )"**
http://2016.stateofthemap.org/   [ September 23 - 25, 2016 ;  Brussels ]

**Comment by muesliq** [comment]
Nope, unfortunately neither of the two. Maybe Brussels, will see.

**Comment by numenor** [comment]
I am really sorry, but no attandence by me. But congratulations to you for getting accepted and the chance to make your great work even better known!

**Comment by sfkeller** [comment]
Just as a side note: 
One can apply for a scholarship at State of the Map 2016: https://blog.openstreetmap.org/2016/04/25/we-want-you-at-state-of-the-map-apply-for-a-scholarship/
And at FOSS4G 2016 there is a studentship programme: http://2016.foss4g.org/attending.html#studentship

**Comment by ImreSamu** [comment]
FOSSGIS 2016 Streaming "Vector Tiles from OpenStreetMap "
*   automated stream dumps - **start 15 minutes after** 

http://streaming.media.ccc.de/fossgis16/relive/5050/

**Comment by lukasmartinelli** [comment]
@muesliq @numenor @hyperknot @hannesj or who else we have interacted with over the past months: **Someone at State of the Map in Brussels? Would love to talk with you**.

I know @ sfkeller @klokan @ImreSamu and myself @lukasmartinelli will be there so we can
probably have good time discussing the future of OSM2VectorTiles perhaps also do some hacking on it.

**Comment by sfkeller** [comment]
Good idea.We can meet at Saturday after end of talks (5:40) or before.
I'm actually not yet in Brussels before Saturday moring. 
There are BOF's scheduled (currently) at Sunday only and at Monday, September 26th there's a dedicated hack day.
