### ISSUE TITLE
Kitematic friendliness of Tileserver Dockers

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#15]
Make the dockers (especially VectorTileServer Docker #5) user-friendly (Volumes, exported ports, logs in the stdout)...

The same for #3 (copy planet to Volume).

**Comment by lukasmartinelli** [comment]
Copy sample data outside of the container so people have something.

**Comment by lukasmartinelli** [comment]
In my opinion this has been resolved.

**Comment by klokan** [comment]
Correct. We have just fixed the vector tile opening via TileJSON from tileserver-mapnik into MapBox Studio Classic, ensured that OGC WMTS runs in QGIS and the whole docker is usable also behind on HTTPS.

**Comment by lukasmartinelli** [comment]
> We have just fixed the vector tile opening via TileJSON from tileserver-mapnik into MapBox Studio Classic

Wow nice!! So the TMS/XYZ issue has been resolved?

**Comment by klokan** [comment]
Yes. See: https://github.com/klokantech/tileserver-mapnik/issues/8
