### ISSUE TITLE
Traversing quadtree sql CTE slow

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#153]
- We discovered that the recursive sql query described in #129 is way to slow
- Example: 
```
not optimized:
z8 query: 239 rows: 11268.274 ms
z9 query: 350 rows: 18268.220 ms
z10 query: 526 rows: 23917.291 ms
z11 query: 770 rows: 37697.867 ms
z12 query: 1372 rows: 64910.485 ms
z13toz14 query: 7259 rows: 64910.485 ms

optimized:
z8 query: 239 rows: 63.467 ms (178x faster)
z9 query: 350 rows: 152.138 ms (120x faster)
z10 query: 526 rows: 411.682 ms (80x faster)
z11 query: 770 rows: 1789.290 ms (21x faster)
z12 query: 1372 rows: 8835.929 ms (7x faster)
z13toz14 query: 7259 rows: 64910.485 ms (equal faster)
```
- Because of this we decided to compare the recursive sql query with the [tile-cover](https://github.com/mapbox/tile-cover) node module of mapbox
- Based on the results we will decide with approach we will take

**Comment by klokan** [comment]
I am not sure what is current approach, but what makes sense to me is:
- run the SQL query generating list of tiles for each changed feature separately (small and fast queries getting your tiles on different zoom levels)
- save the list of dirty tiles together with zoom and osm_id in a special table
- getting list of changed `osm_id` from the saved views - for individual zoom levels defined by our mapping style
- selecting distinct list of dirty tiles based on zoom and osm_ids from the previously saved table with all dirty tiles records

This would be fast and save to do. Can you in details describe your current approach please?
I am now also on Hangouts - if you prefer to chat about this shortly instead...

**Comment by manuelroth** [comment]
### Comparison Results: 
The following measurements were made on the same data with the same machine
```
Traversing quadtree CTE query:
z8 query: 239 rows: 63.467 ms
z9 query: 350 rows: 152.138 ms
z10 query: 526 rows: 411.682 ms
z11 query: 770 rows: 1789.290 ms
z12 query: 1372 rows: 8835.929 ms
z13toz14 query: 7259 rows: 64910.485 ms

tile-cover node module:
z8 query: 239 rows: 2ms (31x faster)
z9 query: 350 rows: 4ms (38x faster)
z10 query: 526 rows: 5ms (82x faster)
z11 query: 770 rows: 10ms (178x faster)
z12 query: 1372 rows: 17ms (519x faster)
z13toz14 query: 7259 rows: 392ms (165x faster)
```
In conclusion the numbers tell us, that the `traversing quadtree` approach depends on the zoom level and the `tile-cover` approach depends on the amount of rows.

**Comment by manuelroth** [comment]
`traversing quadtree` approach:
The following query generates the dirty tiles for each changed feature separately:
```
SELECT * 
FROM (
  WITH RECURSIVE dirty_tiles(x, y, z, e) AS (
  -- root node (0, 0, 0)
  SELECT 0, 0, 0, EXISTS(
    SELECT 1 FROM changed_poi_points WHERE geometry && CDB_XYZ_Extent(0, 0, 0)
  )
  UNION ALL
  -- coordinate for the children
  SELECT x*2 + xx, y*2 + yy, z+1, EXISTS(
    SELECT 1 FROM changed_poi_points
    WHERE geometry && CDB_XYZ_Extent(x*2 + xx, y*2 + yy, z+1)
    ) FROM dirty_tiles,
    -- iterate over 4 children
    (VALUES (0, 0), (0, 1), (1, 1), (1, 0)) as c(xx, yy) 
    -- only for tiles with geometry and up to zoom level 14
    WHERE e AND z < 7
), changed_poi_points AS (
  SELECT * FROM landuse_z7 WHERE timestamp = '2016-03-02 20:14:02'::timestamp
)
SELECT z, x, y FROM dirty_tiles where e
) as a
WHERE z BETWEEN 7 AND 7;
```
This query is executed for each updated row of the zoom level view of the layer:

**Comment by lukasmartinelli** [comment]
Resolved by

**Comment by klokan** [comment]
I believe you compare here apples and pears.

The SQL dirty tiles must be calculated on each shape separately. Please read my described approach above - then it is comparable. You can't iterate on the whole view with the dirty_tiles approach - as these queries are for sure slow.
From the view you can only extract the identifiers of the changed features.

Wouldn't it make sense to try it? Please comment.

**Comment by lukasmartinelli** [comment]
> Wouldn't it make sense to try it? Please comment.

I understand the approach you describe if we try it like that only then we can actually compare the two approaches. Because then we basically do the same in both approaches (from shape -> tiles) not from (tiles -> shapes like now in PostgreSQL).

IMHO it is unlikely we will get faster than with tilecover - in the best case just as fast at the expense of a more complex approach. My hope in using SQL was that it becomes simpler because of less moving parts, if it is not simpler than the JS approach we can continue with tilecover.

If the tilecover approach does not scale for the entire world (who knows..) we can look at the SQL approach again.

What exactly is the disadvantage using tilecover from your perspective?
