### ISSUE TITLE
Test performance of Recursive Tile Function with Geometry Argument

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#155]
Create function that takes a geometry as argument and returns set of touched tiles and do performance test.

**Comment by manuelroth** [comment]
Non working example:
```
CREATE OR REPLACE FUNCTION detect_dirty_tiles(
    geometry_argument geometry
) RETURNS TABLE (
    z INTEGER,
    x INTEGER,
    y INTEGER
) AS $$
BEGIN
	RETURN QUERY(
	    WITH RECURSIVE overlapping_tiles(x, y, z, overlaps) AS (
		SELECT 0, 0, 0, geometry_argument && CDB_XYZ_Extent(0, 0, 0)
		UNION ALL
		SELECT x*2 + xx, y*2 + yy, z+1, geometry_argument && CDB_XYZ_Extent(x*2 + xx, y*2 + yy, z+1)   
		(VALUES (0, 0), (0, 1), (1, 1), (1, 0)) as c(xx, yy) 
		WHERE overlaps AND z < 14
		)
		SELECT z, x, y FROM overlapping_tiles WHERE overlaps
	);
END;
$$ LANGUAGE plpgsql IMMUTABLE;
```

**Comment by lukasmartinelli** [comment]
Long monologue ahead...

## Performance Comparisons

@manuelroth Hmmpf embarassing error. What we actually timed in JS was only the mapping for the tiles to results. Not even the tile cover or querying code.

With new measurements the situation looks more realistic. Like always - most things are too good to be true - JS is still pretty darn fast though.

The SQL function works perfect btw. And it is definitly much faster to use it this way.

```sql
CREATE OR REPLACE FUNCTION overlapping_tiles(
    geom geometry
) RETURNS TABLE (
    tile_z INTEGER,
    tile_x INTEGER,
    tile_y INTEGER
) AS $$
BEGIN
    RETURN QUERY 
        WITH RECURSIVE tiles(x, y, z, e) AS (
            SELECT 0, 0, 0, geom && CDB_XYZ_Extent(0, 0, 0)
            UNION ALL
            SELECT x*2 + xx, y*2 + yy, z+1,
                   geom && CDB_XYZ_Extent(x*2 + xx, y*2 + yy, z+1)
            FROM tiles,
            (VALUES (0, 0), (0, 1), (1, 1), (1, 0)) as c(xx, yy) 
            WHERE e AND z < 14
        )
        SELECT z, x, y FROM tiles WHERE e;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
```

Now let's select **all overlapped tiles by all geometries** of landuse_z12.

```sql
SELECT osm_id,
       tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
FROM landuse_z12;
```

Takes 9440ms. But the second and third time it takes 2500ms.
This is reasonable fast  :+1: 

For `landuse_z13toz14` it takes 30s (5 samples) on PostgreSQL.
`landuse_z13toz14` has 270k objects.

Now I think this is equivalent to the same Node code which will also find all tiles of all geometries returned.

```javascript
// Will calculate the tiles from z0 to z14
//  from the geoms loaded from landuse_z12 view 
detect_dirty_tiles('landuse_z12', 0, 14);
```

Takes ca. **500ms**to calculate tile boundaries inclusive transfering the geometries from data to Node (the transfering is likely to not scale).
Kind of weird that Node is still faster because it needs to transfer the geometries first and then run the algorithm)

For `landuse_z13toz14` Node  takes 1700ms. Now in context I guess performance will decrease once too many geometries need to be transfered to Node.

But this is just the comparison performance wise.

## How to detect Changes More Efficiently in SQL
Please correct me here where I am wrong @klokan  

We will use the overlapping_tiles function differently in SQL so perhaps the performance decrease is still worth it because we can use it smarter.

Instead of calculating the tile indizes for all zoom level views in SQL we will calculate the tile indizes for all objects of `osm_landusages` and store them.

Like a table `osm_changes`.

```sql
CREATE TABLE osm_tiles (
    layer char(30),
    osm_id bigint,
    z INTEGER,
    x INTEGER,
    y INTEGER,
    PRIMARY KEY(layer, osm_id, z, x, y)
);
```

And now all osm shapes that are used in the landuse layer are inserted in
`osm_tiles`. Takes 40s (which is probably the 30s + 10s IO).

```sql
INSERT INTO osm_tiles
SELECT '#landuse',
       osm_id,
       tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
FROM osm_landusages;
```

But the layer is also served by the generalized table `osm_landusages_gen0` and `osm_landusages_gen1`. Now in theory the generalized tables e.g. could cover different tiles because they are different geometries? - but I hope we can ignore that. So actually we need to do.

```sql
WITH landuse_layer_sources AS (
    SELECT osm_id, geometry FROM osm_landusages_gen0
    UNION ALL
    SELECT osm_id, geometry FROM osm_landusages_gen1
    UNION ALL
    SELECT osm_id, geometry FROM osm_landusages
)
INSERT INTO osm_tiles
SELECT '#landuse',
       osm_id,
       tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
FROM landuse_layer_sources
GROUP BY 1, 2, 3, 4, 5
```

Which takes 45s. But again timing doesn't matter so much perhaps because this only need to be done once (as long as it still performs for entire planet).

And now after an update happens on a row we take the OSM id of our changed row and look up in osm_tiles which tiles are affected.

It is also still possible to do it all in one batch.

Get all affected osm_ids.

```sql
SELECT DISTINCT osm_id (
--- union all landuse zoom level views
SELECT * FROM landuse_z12
UNION ALL
SELECT * FROM landuse_z11 
...
)
```

And now those osm_ids can be looked up to affected tiles by joining them (still pretty fast).

## Conclusion

Wrote it down primarily to keep it in my own head.
So the SQL function is not quite as fast as I hoped for.
It is a pretty sophisticated and efficient approach - with the big advantage that it works on TRIGGER level very well.

I am however a worried about the `osm_id` (I don't know how well they really identify a shape, I think it could be multiple geoms in different tables exist with the same osm_id due to the mapping config we use). And performance wise I still need to test the real deal with planet data.

**Comment by lukasmartinelli** [comment]
Now we also discussed about the performance differences between going from shapes to tiles (SQL above) and from tiles to shapes (SQL in this comment).

## Queries

**Shapes to Tiles**:

```sql
SELECT osm_id,
       tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
FROM landuse_z12;
```

**Tiles to Shapes**

```sql
WITH RECURSIVE overlapping_tiles(x, y, z, e) AS (
  -- root node (0, 0, 0)
  SELECT 0, 0, 0, EXISTS(
    SELECT 1 FROM changed_poi_points WHERE geometry && CDB_XYZ_Extent(0, 0, 0)
  )
  UNION ALL
  -- coordinate for the children
  SELECT x*2 + xx, y*2 + yy, z+1, EXISTS(
    SELECT 1 FROM changed_poi_points
    WHERE geometry && CDB_XYZ_Extent(x*2 + xx, y*2 + yy, z+1)
    ) FROM overlapping_tiles,
    -- iterate over 4 children
    (VALUES (0, 0), (0, 1), (1, 1), (1, 0)) as c(xx, yy) 
    -- only for tiles with geometry and up to zoom level 14
    WHERE e AND z < 14
), changed_poi_points AS (
  SELECT * FROM landuse_z12
)
SELECT z, x, y FROM overlapping_tiles where e;
```

## Timings

Now the weird part. The **tiles to shapes** approach is just as fast.
This invalidates our hypothesis that doing the recursive function on one geometry is faster than doing it on all geometries.

Time for query 1 (5 samples): 2500-2700ms
Time for query 2 (5 samples):  2800-2900ms

## EDIT

Forget the timings above.
Actually the two queries don't return the same data (imo they should?). :weary:
Need to look at this tomorrow with a fresh head. Query 1 returns 27k tiles and Query 2 returns 500.

I guess  the function I wrote is wrong. Need to redo it and do all timings again.
So the measurement above is invalid.

**Comment by lukasmartinelli** [comment]
So this query returns the same results.

```sql
SELECT tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
FROM landuse_z12
GROUP BY 1, 2, 3
ORDER BY 3
```

Takes 2500 to 2800ms.
I have a lot of `x`, `y`, `z` duplicates in the `overlapping_tiles` functions - which shouldn't happen - really hints at bug in `overlapping_tiles`.

**Comment by lukasmartinelli** [comment]
I need to test all of these things on the world db - only then it matters. Last time it also happened that I had alot of small scale tests and on world everything behaves more extreme.
 
The PostGIS of the world import ran out of space (due to the update query - that is why the update was hanging for days). Creating a new one now.

**Comment by lukasmartinelli** [comment]
We discussed using `LATERAL JOIN` for performance today.

The `EXPLAIN ANALYZE` returns a bit different approaches but the timings on small datasets **are the same**. Need to test this on a larger set though to be sure.

```sql
SELECT t.x, t.y, t.z FROM landuse_z12 AS l
LEFT JOIN LATERAL (
SELECT tile_x(overlapping_tiles(geometry)) AS x,
       tile_y(overlapping_tiles(geometry)) AS y,
       tile_z(overlapping_tiles(geometry)) AS z
) AS t ON true
GROUP BY 1, 2, 3
ORDER BY 3
```

**Comment by klokan** [comment]
In the above statement I would replace GROUP BY 1, 2, 3 with DISTINCT in the SELECT (for better readability) and add missing WHERE timestamp - to be more transparent.

You approach has one significant drawback - if the same geometry appears on landuse_z12 and landuse_z11 then you will several times calculate all tiles for this geometry down to zoom level 14!
It would be better to calculate it only once and cache it in RAM instead.

So a boost in speed could be probably made by calculating all tiles on z0 - z14 for each modified geometry just once - store it in a temporary table - and select the distinct tiles appearing on zoom level of your interest for list of modified osm_ids in the view of your interest (such as landuse_z12).

To calculate the zxy tiles for all modified geometries on one table (like "places") just once you can use something like:  `CREATE TEMP UNLOGGED TABLE dirty AS SELECT z, x, y ...`. This table could be ordered (with an index) and possibly live only inside of transaction (with ON COMMIT DROP suffix?)

It would be then worth to check what caches in Postgres should be increased so these temp tables with all dirty tiles for one day (or our final update period) all stay in RAM.

Another optimisation could be to add into overlapping_tiles also z as argument - to stop the recursion sooner - if you know you have no interest in deeper zoom levels.

**Comment by lukasmartinelli** [comment]
> You approach has one significant drawback - if the same geometry appears on landuse_z12 and landuse_z11 then you will several times calculate all tiles for this geometry down to zoom level 14!
> It would be better to calculate it only once and cache it in RAM instead.
> 
> So a boost in speed could be probably made by calculating all tiles on z0 - z14 for each modified geometry just once - store it in a temporary table - and select the distinct tiles appearing on zoom level of your interest for list of modified osm_ids in the view of your interest (such as landuse_z12).

Exactly I tried to describe this approach above in **How to detect Changes More Efficiently in SQL** . The queries here are for performance testing only (that is why they have to timestamp clause).

> It would be then worth to check what caches in Postgres should be increased so these temp tables with all dirty tiles for one day (or our final update period) all stay in RAM.

This can be configured with the "running with scissors" mode of PostgreSQL.
If we use the TRIGGER approach we would insert the affected tiles into a permament table not a temp table. But if we only do a query once we need a temp table.

> Another optimisation could be to add into overlapping_tiles also z as argument - to stop the recursion sooner - if you know you have no interest in deeper zoom levels.

Definitly we already used that in some examples and it indeed helps a lot.

If we calculate the affected tiles once and store them in a temp table we will have to go down to z14 at least once. But if we don't do that optimization (but we really need it because otherwise it is too slow now) then we need to stop the recursion earlier.

**Comment by lukasmartinelli** [comment]
> We discussed using LATERAL JOIN for performance today.

I used the `LATERAL JOIN` the wrong way.
Now it is indeed approximately 3x faster.

```sql
SELECT DISTINCT tile_x AS x, tile_y AS y, tile_z AS z
FROM landuse_z12 AS l
INNER JOIN LATERAL overlapping_tiles(geometry) AS t ON true
ORDER BY tile_z
```
