### ISSUE TITLE
Analyze which table have name but no geometry

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#156]
- Create table which shows which table have the geometry and name in same table
Example: Boundaries <=> Country Label
(Geometry is in admin layer and name is in country_label layer => join between tables is needed)

**Comment by klokan** [comment]
List of all layers / tables which has "name", "name_en", etc. and whether we have bounding box: a) in the same table b) in a different table - and which one c) not imported by imposm3 mapping d) completely missing in OSM

**Comment by manuelroth** [comment]
> List of all layers / tables which has "name", "name_en", etc. and whether we have bounding box: a) in the same table b) in a different table - and which one c) not imported by imposm3 mapping d) completely missing in OSM

a) layers / tables with bounding box (geometry) in the same table:
- road / osm_roads (no polygon only linestring)
- road_label / osm_roads (no polygon only linestring)
- water / osm_water_polygons
- water_label / osm_water_polygons
- waterway / osm_water_lines (no polygon only linestring)
- waterway_label / osm_water_lines (no polygon only linestring)
- marine_label / custom_seas (no polygon only linestring and point)

b) layers / tables with bounding box (geometry) in a different table:
- poi_label / osm_poi_points => aeroway, landuse, landuse_overlay, building

c) layers / tables with bounding box (geometry) not imported by imposm3 mapping:
- place_label => admin*
- state_label / custom_states => admin*
- country_label / custom_countries=> admin*

d) layers / tables with bounding box (geometry) completely missing in OSM:
 (place_label, state_label, country_label)

*Administrative boundaries are currently stored as linestrings to convert them to polygons a new mapping would be required.

Boundaries are represented as linestrings in OSM that are linked together with a relation, therefore imposm3 would have to convert these relations to polygons.
We decided against this last year because not all linestrings could be converted to polygons, this resulted in missing boundaries for some countries and admin areas.

The open question c) and d) is still how to map the label to the polygon. See Stefan's post about relations => https://github.com/geometalab/OSMNames/issues/1

#### Conclusion
Because simply joining the tables is not possible in all cases, a new imposm mapping needs to be done for the layers place_label, country_label, poi_label.
