### ISSUE TITLE
Create basic export for osmnames repository

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#157]
- Described in detail in issue https://github.com/geometalab/OSMNames/issues/1
(Good example is could be the building layer)

**Comment by manuelroth** [comment]
Created basic export for table osm_roads as explained in https://github.com/geometalab/OSMNames/issues/1. I will let the code stay in branch feature/export-geonames until we decided how to organize the osmnames project.

**Comment by klokan** [comment]
Where can we download the exported data for whole world?

**Comment by lukasmartinelli** [comment]
Will retry upload to our S3 share. It is a 12GB TSV file that is 4GB gzipped.
Somehow I got quota errors uploading to Google Drive.

**Comment by lukasmartinelli** [comment]
> Where can we download the exported data for the whole world?

Download link of streets osmnames export.

https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.2/osmnames/roads.tsv.gz
