### ISSUE TITLE
Thesis: Write evaluation of 3 dirty tile detection approaches

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#159]
- Describe 3 different approaches to detect dirty tiles
  - tile-cover + updated geometries from postgis
  - recursive CTE + updated geometries
  - insert trigger with recursive CTE on single geometrie

**Comment by lukasmartinelli** [comment]
Wrote low quality  text so we don't forget those chapters later.
But definitly needs to be revisited in the writing phase again.
