### ISSUE TITLE
node version 0.10.x vs. new

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#161]
I'm not an expert on this, but I've just seen other projects recommending to use only Node 0.10.x for tilelive-vector, and it's also the required engine in it's package.json:
https://github.com/mapbox/tilelive-vector/blob/master/package.json

In case there are possible bugs with tilelive-vector, it might be because of node version, just to keep in mind. One related issue: https://github.com/mapbox/tilelive-vector/issues/103

// sorry if everything is working fine with Node 5.x, I just wanted to make a note about possible bugs.

**Comment by lukasmartinelli** [comment]
> I'm not an expert on this, but I've just seen other projects recommending to use only Node 0.10.x for tilelive-vector, and it's also the required engine in it's package.json:
> https://github.com/mapbox/tilelive-vector/blob/master/package.json

Great feedback. This is stuff we would never notice. Thanks.
Our build suddenly started breaking with node 0.10.x (even though we fixed the npm versions) #139 that's why it thankfully got fixed in #160.

I want to keep this issue open as a reminder for some time when bugs and weird things start happening we have a clue why.

**Comment by hyperknot** [comment]
@lukasmartinelli #160 changed both the package versions and the node version. I'd guess it was the package versions which fixed the bug, and it'd work with node 0.10 as well. 

node-mapnik says this on the homepage:
depends: Node v0.10.x or v0.12.x (v0.12.x support requires node-mapnik >= v3.1.6)
however they do provide "matrix" builds (that's wheel / bundle for node AFAIK) for node 0.10, 4, 5
https://github.com/mapnik/node-mapnik/blob/8faf1774e799e43d4becef37797cc4632266328c/.travis.yml#L29

Afaik, mapnik is a pain to compile, and sticking with the matrix builds is a good idea (afaik we are getting those at the moment).

Mapbox seems to be using node 0.10 in production, as it seems from their travis.yml files:
https://github.com/mapnik/node-mapnik/blob/master/.travis.yml
https://github.com/mapbox/node-mbtiles/blob/master/.travis.yml
https://github.com/mapbox/tilelive/blob/master/.travis.yml
https://github.com/mapbox/tilelive-vector/blob/master/.travis.yml
https://github.com/mapbox/tilelive-bridge/blob/master/.travis.yml
https://github.com/mapbox/tilelive-mapnik/blob/master/.travis.yml

**Comment by lukasmartinelli** [comment]
Thanks again @hyperknot for the detailed research.

Let's roll back to v0.10 again and try get a working set of dependencies based on 
`mapnik@3.5.2`.

**Comment by hyperknot** [comment]
I updated all Dockerfiles to node 0.10 and bumped the packages in this PR, waiting to see if build succeeds:
https://github.com/osm2vectortiles/osm2vectortiles/pull/168
