### ISSUE TITLE
Database schema: Rename table and field names consistently

### ISSUE THREAD

**Issue by sfkeller** [osm2vectortiles/osm2vectortiles#163]
Referring to http://osm2vectortiles.org/docs/database-schema/ make table names even more consistent in order to make it more self-documenting.
Something along these lines:
* aero_polygons => aero_polygon
* landusages => landuse_polygon
* admin => admin_polygon
* etc.

Fieldnames (definitions): 
* When you mention osm_id here, do you mean the osm_id from OSM or the "enhanced" osm_id?
* In addition (especially if this table renaming is no feasible) indicate as field type not "geometry" but the geometry type (point, linestring, polygon),

**Comment by lukasmartinelli** [comment]
> Referring to http://osm2vectortiles.org/docs/database-schema/ make table names even more consistent in order to make it more self-documenting.

Completly agree. We should also define this naming rules in the documentation as well.

> When you mention osm_id here, do you mean the osm_id from OSM or the "enhanced" osm_id?

Until now we used the raw `osm_id`. This could be another issue to create an enhanced OSM id following the multiplication rules of Mapbox (chapter OSM IDs) https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v7/

> In addition (especially if this table renaming is no feasible) indicate as field type not "geometry" but the geometry type (point, linestring, polygon),

Yes this will make the diagram much more useful :+1:
