### ISSUE TITLE
Docker build caching

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#169]
Docker build caches each command, so an `apt-get update`, etc. makes no change, if it was ever run on the same image before.

In Travis this is not a problem, as it always starts with a clean environment, there is no cache there. But on real environments, I believe the cache can be any age. I don't know how are you publishing the images, or how frequently are docker build commands run, but Makefile might need `--no-cache` for consistent results.

**Comment by lukasmartinelli** [comment]
> In Travis this is not a problem, as it always starts with a clean environment, there is no cache there. But on real environments, I believe the cache can be any age. I don't know how are you publishing the images, or how frequently are docker build commands run, but Makefile might need --no-cache for consistent results.

Our public Docker images use automated trusted builds so we do not push any
images explicitly.

For local development we want the docker build in  `Makefile` to cache otherwise
it would be too slow for development. Users of osm2vectortiles can build it themselves but we recommend to use the prebuilt images at https://hub.docker.com/u/osm2vectortiles/.

> Docker build caches each command, so an apt-get update, etc. makes no change, if it was ever run on the same image before.

I would actually like to fix the the versions of aptitude packages installed to guarantee more repeatable builds. I will use this issue ticket to check out whether the Dockerfile are all good other
we can improve something.

Btw. shameless self plug. I wrote a Dockerfile linter http://hadolint.lukasmartinelli.ch exactly for this purpose to help people to create best practice Dockerfiles.

**Comment by hyperknot** [comment]
Sorry, I forgot to mention that this issue was only relevant to developers building the containers, for normal users the pre-built images are perfectly fine I believe.

I don't think you can pin apt packages like you can with npm and pip packages, as apt repositories usually only serve the very latest version of each package. 

What you can do on apt is to hold an existing (installed) version, but since you are building Docker files from scratch it won't be an option either.

But don't worry, as Ubuntu LTS and Debian has a really conservative policy for packages, so you are guaranteed to be on the same minor version of a package for the lifetime of the OS. (Python 2.7 is for example from 2013): http://packages.ubuntu.com/trusty/python

**Comment by lukasmartinelli** [comment]
What is the concrete improvement we can do here? Otherwise I close this :wink:  Adding `--no-cache` to the Makefile would make it too slow to work with.

I actually never ran into a problem with our apt installs so far.

**Comment by hyperknot** [comment]
No improvement / bug here, just wanted to raise the point that local builds and Travis build can be on different versions, so we might need to manually rebuild with --no-cache from time to time. I was surprised when I first understood this, might not be clear for others as well.

**Comment by lukasmartinelli** [comment]
> No improvement / bug here, just wanted to raise the point that local builds and Travis build can be on different versions, so we might need to manually rebuild with --no-cache from time to time. I was surprised when I first understood this, might not be clear for others as well.

We should create kind of a contributing / developer docs where we can write stuff like this down.
Right now we don't have much information on GitHub as the docs are on the website. But contributor information like this could live in the GitHub README imho.
