### ISSUE TITLE
Alter detect-dirty-tile node script to execute query and write detected tiles to file

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#173]
- Alter detect-dirty-tile node script to execute query and write detected tiles to file

**Comment by lukasmartinelli** [comment]
Roll back to commit https://github.com/osm2vectortiles/osm2vectortiles/commit/3e249cd81b7a92092c64bcfb72e9c3978a0f0404
Also keep in mind to fix timing again https://github.com/osm2vectortiles/osm2vectortiles/commit/d4be86456a3920ec277fac1792784eed06d942a5

Query for detecting dirty tiles (sufficiently fast for world, 3minutes for all landusages and 45seconds for all POIs). Query only works if #172  is done first.

```sql
WITH changed_geometries AS (
	SELECT geometry FROM poi_label_zoom_level_changes
	WHERE timestamp = '2016-03-09 14:15:02'
), changed_tiles AS (
	SELECT DISTINCT t.tile_x AS x, t.tile_y AS y, t.tile_z AS z
	FROM changed_geometries AS c
	INNER JOIN LATERAL overlapping_tiles(c.geometry) AS t ON true
)
SELECT COUNT(*) FROM changed_tiles
```

**Comment by lukasmartinelli** [comment]
> Query for detecting dirty tiles (sufficiently fast for world, 3minutes for all landusages and 45seconds for all POIs). Query only works if #172 is done first.

Uuups bad thought error. Of course this does not work.
We need to use the approach defined in **How to detect Changes More Efficiently in SQL** #155.

**Comment by lukasmartinelli** [comment]
We now have functions in `src/import-sql/views` for each layer to find out the dirty tiles . They look ~ like this. They would have no chance running on the entire planet directly but thanks that the timestamp constraint makes the data set so much smaller they actually complete reasonably fast (All dirty tiles of all layers in < 1h).

```sql
CREATE OR REPLACE FUNCTION changed_tiles_road(ts timestamp)
RETURNS TABLE (x INTEGER, y INTEGER, z INTEGER) AS $$
BEGIN
	RETURN QUERY (
		WITH changed_geometries AS (
		    SELECT osm_id, geometry FROM layer_road
		    WHERE timestamp = ts
		), changed_tiles AS (
		    SELECT DISTINCT c.osm_id, t.tile_x AS x, t.tile_y AS y, t.tile_z AS z
		    FROM changed_geometries AS c
		    INNER JOIN LATERAL overlapping_tiles(c.geometry, 14) AS t ON true
		)

		SELECT c.x, c.y, c.z FROM road_z14 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 14
		UNION

		SELECT c.x, c.y, c.z FROM road_z13 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 13
		UNION

		SELECT c.x, c.y, c.z FROM road_z12 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 12
		UNION

		SELECT c.x, c.y, c.z FROM road_z11 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 11
		UNION

		SELECT c.x, c.y, c.z FROM road_z8toz10 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z BETWEEN 8 AND 10
		UNION

		SELECT c.x, c.y, c.z FROM road_z7 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 7
		UNION

		SELECT c.x, c.y, c.z FROM road_z5toz6 AS l
		INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z BETWEEN 5 AND 6 
	);
END;
$$ LANGUAGE plpgsql;
```
