### ISSUE TITLE
water_label geometries need to be point not polygon

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#177]
Not sure how we handled it before but souldn't https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-sql/views/water_label.sql#L1-L4 use `ST_PointOnSurface`?

**Comment by manuelroth** [comment]
- This was handled before directly in the source query https://github.com/osm2vectortiles/osm2vectortiles/blob/master/open-streets.tm2source/data.yml#L790 
- https://github.com/osm2vectortiles/osm2vectortiles/commit/4366885440c42b41ce7b822415f1f731be6bb0ae moves conversion of polygon to point to the zoom level views
