### ISSUE TITLE
changed-tiles detection when OSM objects are deleted.

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#183]
Hi,  
What is the status of detecting changed-tiles when OSM objects are deleted?

An extreme test case:
- delete all osm object, except 1 POI

Test data : 
* liechtenstein-160101.osm.pbf
* latest.osc.gz

```
wget http://download.geofabrik.de/europe/liechtenstein-160101.osm.pbf
wget http://www.openstreetmap.org/api/0.6/node/3369927793 -O new.osm
osmconvert liechtenstein-160101.osm.pbf  -o=liechtenstein-160101.osm 
osmconvert liechtenstein-160101.osm      new.osm --diff -o=deleted.osc
cat deleted.osc  |  gzip > latest.osc.gz
```

Draft test script : 
- tested with d5be86c
- I have removed the `osmupdate` part from the `./src/import-osm/import.sh`

```
docker-compose run import-osm
docker-compose run import-sql
docker-compose run changed-tiles
cp ./export/tiles.txt  ./export/tiles_01_import.txt

docker-compose run import-osm-diff
docker-compose run changed-tiles
cp ./export/tiles.txt  ./export/tiles_02_diff.txt

```

Now the changed tiles:  443 ; 1  
```
...$wc -l ./export/tiles_*.txt
 443 ./export/tiles_01_import.txt
   1 ./export/tiles_02_diff.txt
```

Expected: 443 ; 443

**Comment by lukasmartinelli** [comment]
> What is the status of detecting changed-tiles when OSM objects are deleted?

Like always great issue and documentation @ImreSamu! :+1: 
Actually we never thought of that problem. We also don't know how imposm3 reacts
to that. **I have no on the top of my head solution for this problem, but we need to think about it.**

Geometries that are deleted will vanish over time as stuff around them needs to be updated and therefore causes a rerendering (but that's a cheap excuse I know) but in 10 days of diffs more than 10-20% of our tiles change.

**Comment by ImreSamu** [comment]
> We also don't know how imposm3 reacts

I will analyze the imposm3 diff part...  
probably a simple   `delete trigger`  is enought to catch this information.

As I remember Imposm3 diff use : 
*  sql delete 
*  sql insert   ( now this is ok - with `timestamp` )

> Geometries that are deleted will vanish over time 

sometimes geometries modified, and POIs moved to other part of the Earth   
My other extreme test is [the node  number 1](https://blog.openstreetmap.org/2015/12/25/openstreetmappy-christmas/)
http://www.openstreetmap.org/api/0.6/node/1/history
Same node & different tiles  : 

* version=5 :   lat="51.249182" lon="9.4316934"
* version=11:  lat="-31.638757" lon="-60.693853"
* version=13:  lat="48.566985" lon="13.4465242"

**Comment by lukasmartinelli** [comment]
All interesting ideas for #f

> probably a simple delete trigger is enought to catch this information.

Might work. Not sure whether imposm3 does update rows or completely delete and reinsert them.
In the extreme case I could also extend imposm3 even further to act on deleted rows. Btw. for #122 I was glad to have your Imposm 3 pull request from https://github.com/omniscale/imposm3/pull/86 at hand to find out how to implement a custom type.

> My other extreme test is the node number 1

True, good testing node. Your approaches defined above are also useful for #149 

> I have removed the osmupdate part from the ./src/import-osm/import.sh

Do you think it is kind of unintuitive that the `import-osm-diff` tries to update the PBF in the `import` folder? Is it perhaps better to explicitly let the user put a changes file in the `import` folder themselves and just apply the changes file.
Users can still use `osmupdate`.

**Comment by lukasmartinelli** [comment]
> As I remember Imposm3 diff use :
> 
> sql delete
> sql insert ( now this is ok - with timestamp )

We checked it with the audit trigger https://wiki.postgresql.org/wiki/Audit_trigger
and it really is like that.

```
-[ RECORD 1 ]-+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------schema_name   | public
table_name    | osm_poi_point
user_name     | osm
action_tstamp | 2016-03-15 13:45:10.584987+00
action        | D
original_data | (493,1234,"2016-12-09 06:57:37",HSR,"","","","","","","","","","","","","","","",school,0101000020110F0000E2EE0DE126C72DC1067E08CC91BF3441)
new_data      |
query         | DELETE FROM "public"."osm_poi_point" WHERE "osm_id" = $1
-[ RECORD 2 ]-+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
schema_name   | public
table_name    | osm_poi_point
user_name     | osm
action_tstamp | 2016-03-15 13:45:10.584987+00
action        | I
original_data |
new_data      | (494,1234,,HSR,"","","","","","","","","","","","","","","",school,0101000020110F0000E2EE0DE126C72DC1067E08CC91BF3441)
query         | INSERT INTO "public"."osm_poi_point" ("osm_id", "geometry", "timestamp", "name", "name_int", "name_fr", "name_de", "name_en", "name_es", "name_ru", "name_zh", "website", "housenumber", "street", "place", "city", "postcode", "country", "ref", "type") VALUES ($1, $2::Geometry, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
```

**Comment by ImreSamu** [comment]
(same time )

yes ..
a simple Delete trigger enough to catch .. the old records 

my draft code:

```SQL
DROP TABLE IF EXISTS changed_osm_poi_point;   
CREATE TABLE changed_osm_poi_point(
   id        SERIAL
  ,osm_id    bigint
  ,name      character varying 
  ,timestamp timestamp not null default current_timestamp
  ,geometry  geometry(Geometry,3857)   
);

ALTER TABLE changed_osm_poi_point
  OWNER TO osm;

CREATE OR REPLACE FUNCTION osm_poi_point_del_trigger()
  RETURNS trigger AS
$BODY$
BEGIN
     IF (TG_OP = 'DELETE') THEN
        INSERT INTO changed_osm_poi_point(
                    osm_id
                   ,name 
                   ,geometry       
                   )  
		VALUES(
                   OLD.osm_id
                  ,OLD.name 
                  ,OLD.geometry
		);
        RETURN OLD;
      END IF;
END ;
$BODY$ language plpgsql;
;


DROP TRIGGER IF EXISTS o2v_del_trigger ON osm_poi_point; 
CREATE TRIGGER o2v_del_trigger
  BEFORE DELETE
  ON osm_poi_point
  FOR EACH ROW
  EXECUTE PROCEDURE osm_poi_point_del_trigger();

```

**Comment by ImreSamu** [comment]
> Is it perhaps better to explicitly let the user put a changes file
> in the import folder themselves and just apply the changes file.

in my  dev machine the `osmupdate` [ sometimes is not working] (http://wiki.openstreetmap.org/wiki/Osmupdate#Known_issues)   :(  

And sometimes I reach the geofabric download limit.


I would like if  `import_pbf_diffs()`  will be separated smaller callable  functions

now
```
docker-compose run import-osm-diff
```

ideal for me 
```
docker-compose run import-osm-diff  ./import-osmupdate.sh
docker-compose run import-osm-diff  ./import-imposm3diff.sh
docker-compose run import-osm-diff  ./import-updatetimestamp.sh
docker-compose run import-osm-diff  ./import-merge_latest_diffs.sh
```

**Comment by lukasmartinelli** [comment]
> I would like if import_pbf_diffs() will be separated smaller callable functions

I like that separation. For diffs it is useful to have a more power at hand than a single Docker command that does everything magically.

**Comment by lukasmartinelli** [comment]
Okay this was a tough one.
We now detect the deleted dirty tiles. Currently we detect to many dirty tiles for deletions but this is because once an element is deleted we have no additional metadata apart from the geometry which means we can no longer use the zoom level views for deletes to check whether they really appear in the vector tiles.

Results for the test of @ImreSamu:

- 443 tiles in first run
- 482 tiles in second run (where deletes are detected)

This is still correct because the 482 tiles contain all 443 tiles of the first tile. Performance wise we can try to filter out deletes that are not really necessary (like deletes for POI on zoom level 14) - but for the case of deletes I would much rather be 100% correct and having too many false positives than having false negatives by optimizing it per layer.
