### ISSUE TITLE
City label problem in Mapbox streets-v8, light-v8, dark-v8

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#184]
For example:

1) "Zurich" label never appears on the map with streets-v8:
http://klokantech.github.io/osm2vectortiles-gl-styles/#11.26/47.3721/8.5414

2) Vatican city overrides label of Rome:

![nkcxp56osi](https://cloud.githubusercontent.com/assets/59284/13750645/b035cf5e-ea06-11e5-8a0c-f1b6410ca135.gif)

http://klokantech.github.io/osm2vectortiles-gl-styles/#5.99/41.893/12.483

@manuelroth where to schedule this?

**Comment by lukasmartinelli** [comment]
> Vatican city overrides label of Rome:

That's a different problem. Vatican city is a country and therefore is layered above
the city label of Rome. One way to solve it is to not put micro countries into vector tiles until a very high zoom level.

Work continues in #185

**Comment by lukasmartinelli** [comment]
> 1) "Zurich" label never appears on the map with streets-v8:
> http://klokantech.github.io/osm2vectortiles-gl-styles/#11.26/47.3721/8.5414

We never tested the streets-v8, light-v8 and dark-v8 vector maps. We need to check whether it could be filter constraint on the style. Because the data is there in the vector tiles.

What you did to port those styles is simply removing the dependency to Mapbox terrain data set, otherwise they remained unchanged right?

**Comment by klokan** [comment]
Yes - the styles are otherwise untouched. See commit:
https://github.com/klokantech/osm2vectortiles-gl-styles/commit/9b9d3ff0dd50e5a1d5647dbb33bb3a8bde183031

These styles were made primarily for the USB stick for Cebit (#72) and for basic offline use without dynamic server: http://klokantech.github.io/osm2vectortiles-gl-styles/

JSON styles hosted with TileServer-GL can use the original doubled fonts unmodified - as https://github.com/klokantech/tileserver-gl/ serves the fonts correctly combined together. It means you really need to only replace the URL to load the vector tiles (from a local "mbtiles://") and use local sprites and fonts.

When working on reviews it would be worth to check compatibility issues with the latest version of the styles at https://github.com/mapbox/mapbox-gl-styles - which are now using mapbox streets v7.

**Comment by lukasmartinelli** [comment]
I took a look at the style JSON in Mapbox Studio. The city labels also don't show up with the official Mapbox source. And I also saw that there are no longer any layer groups for example.

My guess is that we need to download the style.json from Mapbox Studio online not from the repo (this does look different than the one in the osm2vectortiles-gl-styles repo.

**Comment by klokan** [comment]
Thanks for looking into this. If we upgrade vector tiles to v7 compatibility we indeed should upgrade to the latest JSON GL styles as well...

> When working on reviews it would be worth to check compatibility issues with the latest version of the styles at https://github.com/mapbox/mapbox-gl-styles - which are now using mapbox streets v7.

**Comment by lukasmartinelli** [comment]
The city label problem was solved in #185. When we release the next rendering we will have to create the GL styles.

But this issue is for the old v1.0 version together with Mapbox GL styles where we cannot do much.
