### ISSUE TITLE
Vector Tiles Buffers too big

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#187]
- Mapbox specifies a buffer value in there [mapbox streets documentation](https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v7/)
- Apparently this value is too big, if we can reduce this value the tile size will probably shrink

**Comment by lukasmartinelli** [comment]
Made a comparison. Seems `road_label` have a too big buffer compared to the Mapbox streets vector tiles. For `poi_label` we might also decrease the buffer as v7 has done it, but there I would be more cautious. We should definitely tweak `road_label`.

| Layer                | Mapbox Streets v6 | Mapbox Streets v7 | OSM2VectorTiles v1 |
|----------------------|-------------------|-------------------|--------------------|
| #landuse             | 4                 | 4                 | 4                  |
| #waterway            | 4                 | 4                 | 4                  |
| #water               | 8                 | 8                 | 8                  |
| #aeroway             | 4                 | 4                 | 4                  |
| #barrier_line        | 4                 | 4                 | 4                  |
| #building            | 2                 | 2                 | 2                  |
| #landuse_overlay     | 4                 | 4                 | 4                  |
| #tunnel              | 4                 | -                 | 4                  |
| #road                | 4                 | 4                 | 4                  |
| #bridge              | 4                 | -                 | 4                  |
| #admin               | 4                 | 4                 | 4                  |
| #country_label       | 256               | 256               | 256                |
| #marine_label        | 256               | 256               | 256                |
| #state_label         | 256               | 256               | 256                |
| #place_label         | 128               | 128               | 128                |
| #water_label         | 64                | 64                | 64                 |
| #poi_label           | 128               | 64                | 128                |
| #road_label          | 8                 | 8                 | 64                 |
| #waterway_label      | 8                 | 8                 | 8                  |
| #housenum_label      | 64                | 64                | 64                 |
| #motorway_junction   | -                 | 8                 | -                  |
| #airport_label       | -                 | 64                | -                  |
| #rail_station_label  | -                 | 64                | -                  |
| #mountain_peak_label | -                 | 64                | -                  |

**Comment by lukasmartinelli** [comment]
I adapted the buffer value for `road_label`. Seems to save 10KB on avg. on z14 tiles, detailed tile size statistics will follow once we start rendering bigger areas again.

I guess the `poi_label` buffer label changes in *v7* because in *v7* they are pushing down the POIs that previously were in z14 down to z15. But that is just a guess.

But we cannot do that so we leave the value at the `128px` from v6.
