### ISSUE TITLE
Respect buffer in changed tiles detection

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#188]
If a geometry changes it might be that due to the large buffer value not only the tiles the geomtry is contained within need to be rerendered, but also the adjacent tiles because they contain the geometry as well as part of their buffer.

Buffers are not larger than one tile (< `256px`) so one solution would be that for each
dirty tiles all adjacent tiles need to be rerendered as well.

...nasty issue.

<img width="950" alt="collection_of_map_ _osm2vectortiles" src="https://cloud.githubusercontent.com/assets/1288339/13752854/dd16a908-ea10-11e5-939f-3624a3bfddde.png">

**Comment by klokan** [comment]
The function to calculate bbox for ZXY in Mercator defined in SQL could be improved to accept buffer size if pixels.

**Comment by lukasmartinelli** [comment]
> The function to calculate bbox for ZXY in Mercator defined in SQL could be improved to accept buffer size in pixels.

:+1: Genius idea!! Much simpler and also allows optimizing for buffer values that are not that large.
