### ISSUE TITLE
Some city labels aren't available at appropriate zoom levels

### ISSUE THREAD

**Issue by brewin** [osm2vectortiles/osm2vectortiles#193]
I live near Kansas City, and while experimenting with osm2vectortiles I noticed the label for it isn't available until zoom level 7. It is a major US city and is several times larger than Topeka, which is available at zoom level 6. I think it might be ranked incorrectly in the data source.

http://klokantech.github.io/osm2vectortiles-gl-styles/#6.41/38.960/-94.570

**Comment by lukasmartinelli** [comment]
Usually ranking for bigger cities should come for NaturalEarth which assigns importance ranks
to over 7000 cities in the worlds, if not we fall back to a ranking based on population.

In this case it seems oddly off.

Kansas City: http://www.openstreetmap.org/node/1856296860 with population `463202`.
Topeka: http://www.openstreetmap.org/node/25141246 with population `124331`.

**Comment by muesliq** [comment]
Same for São Paulo - 12 million inhabitants. The shown town of Sorocaba has 0,6 million inhabitants.

![screen shot 2016-03-30 at 13 50 38](https://cloud.githubusercontent.com/assets/1606618/14141385/f77fd394-f67e-11e5-8ffe-70bd94d028cd.png)

**Comment by brewin** [comment]
Washington, DC also. The nearby city of Alexandria, VA shows up instead.

Washington, DC population: 658,893
Alexandria, VA population: 148,892

**Comment by lukasmartinelli** [comment]
The population is only relevant for something called the `localrank`. The `localrank` is the importance of the label compared to the labels in close proximity, in case of city all cities in a cell in a grid are ranked by their population. So this will be correct for the cities mentioned here.

But for a city to be displayed at a low zoom level the important part that the `scalerank` is set and has a minimal value. Now the question is how to find out whether Sao Paulo has a good `scalerank`. Scaleranks are not derived from population but whether the city is well known/important.

We take the scale straight from Natural Earth (so does Mapbox), now the problem with the cities above is that the code that tries to merge OSM data with Natural Earth data does not pick up all important cities.
I am modifying the code in https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/update-scaleranks/update.sql to improve the matching from OSM to Natural Earth.

**Comment by lukasmartinelli** [comment]
Matching is slightly improved - hope we don't have many false positives.

Matched Natural Earth cities before:
- 5629 osm_place_point
- 1399 osm_place_polygon

Okay matching the additional `meganame` doesn't help much.

Matched Natural Earth cities after:
- 5633 osm_place_point (+4)
- 1400 osm_place_polygon (+1)

Matching the additional `gn_ascii` from Natural Earth helps more.

Matched Natural Earth cities after:
- 5805 osm_place_point
- 1447 osm_place_polygon


Matching the additional `nameascii`field from Natural Earth (after matching `gn_ascii`).

- 5809 osm_place_point (+4)
- 1448 osm_place_polygon (+1)
