### ISSUE TITLE
Thailand Bangkok tiles missing

### ISSUE THREAD

**Issue by go2coffee** [osm2vectortiles/osm2vectortiles#194]
I found four tiles listed below are missing at zoom 14, city Bangkok, Thailand.

http://klokantech-1.tileserver.com/osm-bright/14/12766/7559.png?key=WQ5sRntXphOrWgesmtmU
http://klokantech-2.tileserver.com/osm-bright/14/12767/7559.png?key=WQ5sRntXphOrWgesmtmU
http://klokantech-3.tileserver.com/osm-bright/14/12767/7560.png?key=WQ5sRntXphOrWgesmtmU
http://klokantech-0.tileserver.com/osm-bright/14/12767/7561.png?key=WQ5sRntXphOrWgesmtmU

**Comment by lukasmartinelli** [comment]
Probably related to #116.

**Comment by lukasmartinelli** [comment]
Will be dealt with in #111.
