### ISSUE TITLE
Missing labels for some states, provinces, and territories

### ISSUE THREAD

**Issue by brewin** [osm2vectortiles/osm2vectortiles#195]
I've noticed labels for some states, provinces, and territories are not shown at any zoom level using any style. I assume they're missing from the vector tiles.

Alaska, USA
Florida, USA
Puerto Rico, USA
Saskatchewan, Canada

**Comment by manuelroth** [comment]
Hi @brewin, thanks for your report. We have custom curated lists of [states](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-external/states.geojson), [seas](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-external/seas.geojson) and [countries](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-external/countries.geojson). You can simply add the missing items to the corresponding geojson and create a pull request.

**Comment by klokan** [comment]
@manuelroth shouldn't the above mentioned automatically appear on zoom levels like 5 or 6 - directly from Natural Earth?

There is a need for "seas" custom geojson probably - but aren't the states and countries sufficient in the Natural Earth Data itself?

**Comment by manuelroth** [comment]
@klokan The data like name, translations and geometry is based on OSM data. We extracted it with the [overpass api](https://overpass-turbo.eu/). These custom geojson's were created because we wanted to add our own scalerank. Neither OSM nor Natural Earth provide a good scalerank, because of this we decided to do this solution.

**Comment by manuelroth** [comment]
I just figured out, that Alaska and Florida are not included because we did not extract them correctly. I will create a pull request and add them.

**Comment by manuelroth** [comment]
Added the missing states Alaska, Florida and Saskatchewan. I did not add Puerto Rica, because it is not a state of america
