### ISSUE TITLE
Optimize diff import performance

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#197]
Through our fancy trigger solution in PR #191 the import process now takes several orders of magnitudes longer. This is necessary to support deletes #183  and detecting whether a row has really changed (whether the values in the database have been modified or not) #132.

The ten day diff before took only 4-7 hours of importing diffs and now it is taking 35hours and still not completed. We need to speed this up to get back into the one day time frame.

**Comment by klokan** [comment]
Modification of imposm3 required - to not do DELETE + INSERT in case there is no change in the data?
