### ISSUE TITLE
URGENT: osm2vectortiles.org DNS trouble

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#201]
Lukas,

the DNS servers for osm2vectortiles.org which you manage are not resolving now!
The project website is down.

```
$ ping osm2vectortiles.org
ping: cannot resolve osm2vectortiles.org: Unknown host
$ ping www.osm2vectortiles.org
ping: cannot resolve www.osm2vectortiles.org: Unknown host
```

Shall we move the DNS to sysadmin@klokantech.com and DNS servers manage by company - which has 24/7 monitoring set and somebody resolving potential issues?

**Comment by klokan** [comment]
I see DNS connectivity issues at:
https://status.digitalocean.com/

**Comment by lukasmartinelli** [comment]
> I see DNS connectivity issues at:
> https://status.digitalocean.com/

DNS is indeed managed by Digital Ocean. I can switch the nameservers but I would wait until they come back.

**Comment by lukasmartinelli** [comment]
Site was approximately 2 hrs down.
Digital Ocean DNS is working again - those poor sysadmins had a rough day I guess.
