### ISSUE TITLE
Include rendering date on website?

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#202]
The page http://osm2vectortiles.org/downloads shows no indicators when the data was rendered the last time. A date (plus version number?) would solve that.

**Comment by lukasmartinelli** [comment]
> The page http://osm2vectortiles.org/downloads shows no indicators when the data was rendered the last time. A date (plus version number?) would solve that.

Good idea! Thanks.

**Comment by muesliq** [comment]
Any forecast on when the next rendering will happen, btw?

**Comment by lukasmartinelli** [comment]
> Any forecast on when the next rendering will happen, btw?

Before june. We need to start rendering in may and after that switch to rendering weekly updates.
After we have the update process in place we no longer need the huge and costly rerendering effort - you will be able to upload the latest weekly world MBTiles file.

**Comment by lukasmartinelli** [comment]
> The page http://osm2vectortiles.org/downloads shows no indicators when the data was rendered the last time. A date (plus version number?) would solve that.

Put up the date and version on the site for the last rendering.

http://osm2vectortiles.org/downloads
