### ISSUE TITLE
Rename Open Streets to osm2vectortiles

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#215]
We gave the source project its own name which is confusing for users in hindsight imho.
We can just call it `osm2vectortiles.tm2source` instead of *Open Streets* especially since [Open Streets is quite a overloaded Google Search term](https://www.google.ch/search?q=open+streets&oq=open+streets) with many existing stuff.

Idea is to rename:
- The folder `open-streets.tm2source` to `osm2vectortiles.tm2source`
- In the `data.yml` source style
  - rename *title* and *description* to osm2vectortiles with a link to the hompeage and github project
  - Also add descriptions for each layer (like Mapbox Streets does it)

**Comment by klokan** [comment]
+1
