### ISSUE TITLE
Exporting tiles locally could be done concurrently

### ISSUE THREAD

**Issue by mlerner** [osm2vectortiles/osm2vectortiles#216]
Tilelive (used by export-local.sh to export tiles) has an option to perform operations concurrently: https://github.com/mapbox/tilelive/blob/master/bin/tilelive-copy#L14

This option could be added to the export script (with a sane default) and configured via an environment variable.

**Comment by lukasmartinelli** [comment]
> Tilelive (used by export-local.sh to export tiles) has an option to perform operations concurrently: https://github.com/mapbox/tilelive/blob/master/bin/tilelive-copy#L14
> 
> This option could be added to the export script (with a sane default) and configured via an environment variable.

We previously used *tl* instead of *tilelive-copy* which did this automatically. Thanks for pointing it out for tilelive-copy.

We have three levels of concurrent processing.

1. At the machine level (5-6)
2. At the worker level (worker processes per machine 4-5)
3. At the process level (tilelive-copy and tl concurrency)

**Comment by lukasmartinelli** [comment]
Just as update. Tweaking `concurrency` (from 10 to 20 for example) doesn't really effect performance.
I get just as many tiles per second with 20 (or higher) copy concurrency as with 10 for example.

I will close this as like always this is kind of a trial and error tweaking thing where I figure out the best values for the three concurrency levels (also depends on machines as well). I will post the settings used in #251 but tweaking the copy concurrency is not the silver bullet 😉 

**But thanks again for raising attention for the concurrency option in tilelive copy**.
