### ISSUE TITLE
Broken OSM Borders

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#221]
The high zoom levels where we take border data from OSM we have sometimes broken borders.
We can no longer use Natural Earth data for borders there because it is not detailed enough.

<img width="834" alt="collection_of_map_" src="https://cloud.githubusercontent.com/assets/1288339/14386411/ecb0826a-fda4-11e5-8fcb-a3e4e5dc2f65.png">

<img width="899" alt="collection_of_map_" src="https://cloud.githubusercontent.com/assets/1288339/14386469/38e58716-fda5-11e5-9104-ad8e08fd7d7b.png">

**Comment by manuelroth** [comment]
[https://osm.wno-edv-service.de/boundaries/](https://osm.wno-edv-service.de/boundaries/) provides OSM boundaries

**Comment by lukasmartinelli** [comment]
Hmm now Schaffhausen is good again on the global map - and Ireland as well.

dev.vectortiles.osm2vectortiles.org

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/14589493/a064dfdc-04e3-11e6-81ae-766b72374b62.png)

![cursor_and_compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/14589500/e1a7e44e-04e3-11e6-8cce-55dfd69074ca.png)

**Comment by manuelroth** [comment]
As the problems disappeared in our latest import this issue can be closed.
