### ISSUE TITLE
Allow configuration of label languages

### ISSUE THREAD

**Issue by hannesj** [osm2vectortiles/osm2vectortiles#226]
Currently the names are included in the same set of languages as in the Mapbox Streets. It would be nice if you could configure what languages you want to have imported into the database and included in the tiles in the compose file.

**Comment by lukasmartinelli** [comment]
> Currently the names are included in the same set of languages as in the Mapbox Streets. It would be nice if you could configure what languages you want to have imported into the database and included in the tiles in the compose file.

I understand the feature request completely. It is kind of a big deal however because for us language fields are just normal fields that we map and process.

To make this configurable we would need to make all of these parts dynamic or allow templating.

Probably the easiest way for someone else add another language like Finnish is to replace a language like Russian with Finnish by doing a search and replace for `name_ru` with `name_fi`?.

However multiple languages are probably most relevant for country names and place names imho. There are not as many data points for those labels like for example poi labels.
So we could theoretically add a lot more languages for countries and places.

**Comment by sfkeller** [comment]
Just to clarify the situation with labels: OSM collects the local situation, therefore tag name contains the local geographic name (=called "endonym" in toponymy). And there are very few objects which contain tag int_name, name_en, etc. Therefore, finnish geonames _in_ Finland are not excluded!

In OSMaxx project we handle labelling and names like this: Attribute "name" (contains endonym), "int_name" (contains english geoname if any), "label" (contains "transliterate(name)" unless one of the following tag values exist...:), "name_en", "name_fr", "name_es", "name_de".

**Comment by hannesj** [comment]
Yes, it is possible to just search and replace another language, but my wish was (for some time in the future), to be allowed to e.g. generate the yaml files by using some kind of templating where the required languages could specified. The generation is not a big priority for us, but I just wanted to document it somewhere. 

Just a couple words about the background. There exists four types of municipalities, monolingual and bilingual, both with Finnish and Swedish as the majority languages. In OSM the tag `name` is based on the majority language and both `name:fi` and `name:sv` exists for streets in bilingual municipalities. We would like to have street names rendered in both in Finnish and Swedish, as they can be quite different from each other. There is quite good data coverage, since the national road database has been imported with both names in place into OSM.

**Comment by sfkeller** [comment]
Ah ok. We have this situation of bilingual endomyms actually too in Switzerland (e.g. de/fr Biel/Bienne) and in Austria (South Tirol de/it). 
But believe me, a highly data model optimized for base maps like this, introducing templates (for names or other attributes) is a major enhancement and refactoring task.
For me it's more realistic for near future to combine base vector tiles like ours with other "thematic" vector tiles, coming from a generic vector tile generator.

**Comment by lukasmartinelli** [comment]
> Currently the names are included in the same set of languages as in the Mapbox Streets. It would be nice if you could configure what languages you want to have imported into the database and included in the tiles in the compose file.

Sorry @hannesj. We discussed it again and this is not in our scope and would make the project a lot more complex. Mapzen for example makes heavy use of templating in their tm2source project and imho you can then no longer read it very well and also you are unable to fire up Mapbox Studio and work with it there.

I really propose you use the search/replace approach if you create a finnish extract. 

> Probably the easiest way for someone else add another language like Finnish is to replace a language like Russian with Finnish by doing a search and replace for name_ru with name_fi?.

BTW. we would really be interested in seeing how it looks with two labels on one streets or how you create a style that supports that.
