### ISSUE TITLE
Field differences between osm2vectortiles and Mapbox Streets v7

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#227]
In Mapbox Streets v7 the field address was removed

**Comment by lukasmartinelli** [comment]
- In **#landuse_overlay** the `type` field is missing.
- In **#poi_label** the fields `address`, `website`, `network` are no longer present in Mapbox v7
- In **#road** the value for `layer` is only present in zoom levels greather or equal 13
