### ISSUE TITLE
Better Locality Effects for List Jobs

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#234]
**This is an optimization**. Right now tiles are sorted by their XYZ index and then split into jobs. This will result in a **scanline** pattern. It would be much better if we have a **pyramid** style locality effect so that PostGIS can keep the right stuff in the index all the time.

Tip by @klokan is to convert XYZ into [QuadKey](https://msdn.microsoft.com/en-us/library/bb259689.aspx) and then sort it which will give us good locality effects. Quite a cool trick imho.

**Comment by klokan** [comment]
Could be helpful:

```python

    def QuadTree(tx, ty, zoom ):
        "Converts XYZ tile coordinates to Microsoft QuadTree"
        
        quadKey = ""
        for i in range(zoom, 0, -1):
            digit = 0
            mask = 1 << (i-1)
            if (tx & mask) != 0:
                digit += 1
            if (ty & mask) != 0:
                digit += 2
            quadKey += str(digit)
            
        return quadKey
```

Derived from globalmaptiles.py at http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

**Comment by sfkeller** [comment]
You can also ask colleagues Heeb+Keller... :-)
