### ISSUE TITLE
Recent builds breaking tiles on missing markers

### ISSUE THREAD

**Issue by hyperknot** [osm2vectortiles/osm2vectortiles#235]
The recent builds of klokantech/tileserver-mapnik docker images have lots of broken tiles.

This is what I see in docker logs:
```
Mapnik LOG> 2016-04-12 10:23:02: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/leisure-12.svg
Mapnik LOG> 2016-04-12 10:23:02: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/building-12.svg
Mapnik LOG> 2016-04-12 10:23:02: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/amenity-12.svg
Mapnik LOG> 2016-04-12 10:23:02: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/tourism-12.svg
Mapnik LOG> 2016-04-12 10:23:02: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/pitch-12.svg
Mapnik LOG> 2016-04-12 10:23:03: Marker does not exist: /project/mapbox-studio-osm-bright.tm2/icon/leisure-12.svg
```

So if anyone is using the project in production, **do not upgrade your docker container**, or else it'll give you lots of broken tiles.

For example:
mapbox-studio-osm-bright/6/36/23.png

- It'd be important to make sure that broken tiles cannot happen just because some markers are missing. Tiles should be simply rendered without those markers.
- Actually, those markers are not even visible on zoom 6, why is Mapnik rendering them?
- Find out what has changed and why are those markers missing?

**Comment by klokan** [comment]
I don't see this problem on https://klokantech-1.tileserver.com/osm-bright/6/36/23.png?key=USE-YOUR-KEY

How to reproduce the error?
Can you test it properly and prepare a Pull Request with a fix of the problem please?

**Comment by hyperknot** [comment]
@klokan are you running a recent build on tileserver.com? To reproduce, just set up a VPS now and it'll produce the error.

**Comment by hyperknot** [comment]
The problem is clear, there are no such icons like "leisure-12.svg" in https://github.com/mapbox/mapbox-studio-osm-bright.tm2/tree/master/icon

The string "leisure" is not even present in mapbox-studio-osm-bright.tm2.

However Mapnik still gives this error message and breaks rendering.

**Comment by klokan** [comment]
Thanks @hyperknot for the report and details. We will try to reproduce.

Moving this ticket to https://github.com/klokantech/tileserver-mapnik/issues/14

It does belong to tileserver-mapnik project. Let's continue there, please.
