### ISSUE TITLE
Show important suburbs on lower zoom levels

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#238]
![compare_open_streets_with_mapbox_streets_](https://cloud.githubusercontent.com/assets/1288339/14472658/70c01f28-00f4-11e6-8ad2-f90175038523.png)

Must be something of these types.

![osm_bright_original___mapbox_](https://cloud.githubusercontent.com/assets/1288339/14472676/8750e5e2-00f4-11e6-83a9-2ce0e562110c.png)

**Comment by manuelroth** [comment]
This labels are of type suburb, I tried to describe to problem of showing the most important suburbs earlier in my pull request https://github.com/osm2vectortiles/osm2vectortiles/pull/248

**Comment by lukasmartinelli** [comment]
Put one hour into it. It is better we don't show suburbs at z10 than showing the wrong ones.
I cannot filter by localrank because it is not really accurate (since most suburbs don't have a population assigned the localrank doesn't help in ranking and ranking by area also doesn't help).
