### ISSUE TITLE
Place label duplicates

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#239]
This is because we now match the place polygons as well and make them to a point.
But to not suffer from duplicate labels we need to remove the duplicates (same problem as with roads).
Perhaps imposm mapping can solve it.

![cursor_and_compare_open_streets_with_mapbox_streets_](https://cloud.githubusercontent.com/assets/1288339/14472948/035aa33e-00f6-11e6-8089-173b3e4de7fc.png)

**Comment by lukasmartinelli** [comment]
Jup single table helps. But now the polygon points is now taken instead of the original point.

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/14476604/0773cbc2-0109-11e6-95a2-3cbb9169267f.png)

**Comment by lukasmartinelli** [comment]
> Jup single table helps. But now the polygon points is now taken instead of the original point.

No not true made a mapping mistake. The points even occur twice if in the same table - which makes perfect sense because there is no way we can match the point and polygon by the osm id (this is a different case as with the roads where we can look at a polygon as a closed linestring).

Because we cannot match by the osm id we also cannot remove the duplicates.
My suggestion is now that we only match the residential landuse in the **polygon** part of the **type_mappings**. Could that work @manuelroth?

Or we leave out the landuse=residential stuff and polygon matching altogether. Because it might always be that someone also tagged a neighbourhood with a point inside the residential polygon - and then we have the labels twice again. 
**Better to have good quality labels than too many ones imho**.

Or we do a distance-based name matching with looking for the same name within 10km to remove duplicates. But I don't really want to do that - as it is very vulnerable to false positives.

**Comment by manuelroth** [comment]
I suggest the following mapping. 

```yaml
type_mappings:
  point:
    place:
      city	
      town	
      village
      hamlet
      suburb
      neighbourhood
      island
      islet
      archipelago
      isolated_dwelling			
  polygon:
    place:
      island
      islet
      archipelago
    landuse:
      residential
    boundary:
      aboriginal_lands
```

**Comment by lukasmartinelli** [comment]
> I suggest the following mapping. islands, islets and archipelago are in polygon because the are most of the time mapped on the area.

Yes let's try this and compare again.

The only critical thing I see there is `landuse=residential` where people put a point with `place=neighbourhood` inside the polygon and then it will appear twice.

**Comment by manuelroth** [comment]
Just tested it, looks good on first sight. Ouu didn't thought about that. Let's keep this in mind, if we discover duplicated place_labels again. I will commit the changes on your branch `hotfix/single-place-label-table`. I have also some additional improvements to the layer views.

**Comment by manuelroth** [comment]
Found a nasty problem, if the type_mapping types are not written in plural it won't import anything.

```yaml
type_mappings:
  points:
    place:
      city  
      town  
      village
      hamlet
      suburb
      neighbourhood
      isolated_dwelling         
  polygons:
    place:
      island
      islet
      archipelago
    landuse:
      residential
    boundary:
      aboriginal_lands
```
polygons is correct, polygon not. @lukasmartinelli is this somewhere documented?
