### ISSUE TITLE
Rail station label per platform instead only once

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#241]
@manuelroth You know the section in the OSM wiki about this problem?

![cursor_and_compare_open_streets_with_mapbox_streets_](https://cloud.githubusercontent.com/assets/1288339/14473171/10870e3e-00f7-11e6-9e7b-dff2c2f752e7.png)

**Comment by manuelroth** [comment]
http://wiki.openstreetmap.org/wiki/DE:Tag:railway%3Dstation
> Es bietet sich an, einen Bahnhof als einen Punkt zu mappen. Bei einem Bahnhof mit nur einem Bahnsteiggleis kann es sinnvoll sein, diesen direkt auf den Schienenweg (railway=rail) zu setzen. Bei Bahnhöfen mit mehreren Gleisen bietet es sich an, diesen Punkt ungefähr in der Mitte des für den Bahnkunden relevanten Bereichs (Empfangsgebäude, Bahnsteige) zu setzen. Keinesfalls sollte ein Bahnhof durch mehrere Punkte (z. B. an jedem Bahnsteiggleis) getagged werdenǃ

**Comment by manuelroth** [comment]
Ok found out, why we have so many labels. We map railway=stop, which is way our labels are at the end of the platform. We should actually only map railway=station for the label.
