### ISSUE TITLE
Footpaths displayed as normal Streets

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#242]
Nitpicking..Some footpaths are mapped as normal streets.

![cursor_and_compare_open_streets_with_mapbox_streets_](https://cloud.githubusercontent.com/assets/1288339/14473320/ba7e1158-00f7-11e6-8741-9dd4260aa104.png)

**Comment by manuelroth** [comment]
Classification of street_limited was incorrect. Fixed in https://github.com/osm2vectortiles/osm2vectortiles/pull/286
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14785146/7f6deb72-0af9-11e6-8289-366037f11b4d.png)
