### ISSUE TITLE
Wrong z-order for certain roads

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#246]
There is a small problem at #18.17/47.39807/8.53234.
Could also be that we have older data than Mapbox (but it is just 10 days) or otherwise the streets
are layered differently.

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/14474739/d70e76a8-00fe-11e6-9aad-2f76f7f57b0b.png)

**Comment by manuelroth** [comment]
I thinks we can ignore this for now, checked other junctions for wrong z-order. Could find any errors.
