### ISSUE TITLE
Less tram/railway stations at lower zoom levels

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#252]
I guess this involves:

1. Checking at which zoom levels trains vs trams/subways appear
2. Perhaps we add a localrank as window function and then filter by localrank (only show top 3 to 4 on low zoom levels like for highway shields) to not show too many stations

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/14589627/f725603c-04e6-11e6-8425-2778f44758e1.png)

**Comment by manuelroth** [comment]
It seams Mapbox does not show tram stations at all.

**Comment by lukasmartinelli** [comment]
> It seams Mapbox does not show tram stations at all. I think the tram stations are a good orientation point we should keep them. We don't have a localrank currently, how is the localrank calculated for the highway shields?

**Let's show trams only at z14 at least**.

We can leave the localrank for now. z14 already helps a lot imho.

A more complicated localrank example for road labels.

```sql
rank() OVER (
                PARTITION BY LabelGrid(geometry, (CASE WHEN z(!scale_denominator!) >= 11
                                                       THEN 300
                                                       ELSE 200 
                                                   END) * !pixel_width!)
                ORDER BY road_localrank(type) ASC, round(MercLength(geometry)) DESC
            ) AS localrank
...
...sql
WHERE (z(!scale_denominator!) BETWEEN 8 AND 10 AND localrank < 2)
             OR (z(!scale_denominator!) BETWEEN 11 AND 12 AND localrank < 5)
             OR (z(!scale_denominator!) BETWEEN 13 AND 14)
```

Simpler example.

```sql
        rank() OVER (PARTITION BY LabelGrid(geometry, 200 * !pixel_width!)
                     ORDER BY scalerank ASC NULLS LAST,
                              population DESC NULLS LAST
        ) AS localrank
```

**Comment by lukasmartinelli** [comment]
> Let's show trams only at z14 at least.

This is already done in `rail_station_label.sql` I see.
For z12toz13 only class `rail` is shown.
