### ISSUE TITLE
Show more OSM landuse=wood on lower zoom levels

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#254]
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14598791/2ebc8972-0554-11e6-91cb-27ac4a58216c.png)

**Comment by lukasmartinelli** [comment]
Is this even possible to solve @manuelroth? The current status is that Mapbox somehow does have different data for the "green" areas than we do right?

**Comment by manuelroth** [comment]
- I don't see a straight forward solution for this. Tried to show more landuse on lower zoom levels, this resulted in way more features that Mapbox has. 
- Natural Earth does not provide a land cover table which we could use. 
- Generalization of the OSM landuse polygons with ST_SimplifyPreserveTopology does also not help much. The polygons get indeed simpler, but there are still too many of them.
- @klokan @ImreSamu do you maybe know of a open dataset which provides land cover data for lower zoom levels (z5 to z9, does not need to be very detailed but for the whole world)
- Or is there a PostGIS function which allows to combine multiple adjacent small geometries into big geometries?

**Comment by sfkeller** [comment]
@manuelroth wrote:
>  Or is there a PostGIS function which allows to combine multiple adjacent small geometries into big geometries? 
Yes; since PostGIS version 2.2.0: http://postgis.net/docs/manual-dev/ST_ClusterWithin.html

**Comment by manuelroth** [comment]
> Yes; since PostGIS version 2.2.0: http://postgis.net/docs/manual-dev/ST_ClusterWithin.html

Oh nice, so this groups the geometries by a distance and then ST_Union can be used to combine them to one geometry. I will give this a try, we would probably have to do this in a preprocessing step. I will just check if can come visually and size-wise close to Mapbox.

**Comment by manuelroth** [comment]
### Preparation
The following query creates a table containing the clustered landuse multipolygons. Detail explanation below:
```sql
CREATE TABLE landuse_clustered AS 
    SELECT ST_CollectionExtract(unnest(ST_ClusterWithin(geometry, 4000)),3) AS geometry 
    FROM osm_landuse_polygon_gen0
    WHERE landuse_class(type) IN ('wood');
```
**[ST_ClusterWithin](http://postgis.net/docs/manual-dev/ST_ClusterWithin.html)** - Clusters the geometries within the distance of 4000, returns an array of GeometryCollections
**[unnest](http://www.postgresql.org/docs/9.2/static/functions-array.html)** - Expands the array to a set of rows
**[ST_CollectionExtract](http://postgis.net/docs/ST_CollectionExtract.html)** - Returns a single multipolygon geometry for each GeometryCollection

Mapbox Tile Analysis:

| zoom level | landuse feature average |
|------------|------------------|
| 5          | 6                |
| 6          | 6                |
| 7          | 6                |
| 8          | 6                |
| 9          | 64 - 385         |
| 10         | 54 - 294         |

The analysis shows that from zoom level 5 to 8 there are constantly 6 landuse features present in the vector tiles. Hence the distance value of the ST_ClusterWithin function must be selected so that exactly 6 multipolygons result for this bbox. 

### Results

After playing around with it, I found that a distance of 4000 seams to result in around 6 features per tile. Need to verify this on a bigger data set. Created a pull request https://github.com/osm2vectortiles/osm2vectortiles/pull/269

OSM2VectorTiles Tile Analysis:

| zoom level | landuse feature average |
|------------|------------------|
| 5          | 5                |
| 6          | 8                |
| 7          | 3 - 10          |
| 8          | 1 - 2           |
| 9          | 147 - 421         |
| 10         | 17 - 75         |

Visual Result:

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14741540/338a74e6-0897-11e6-9288-199c92907145.png)

**Comment by lukasmartinelli** [comment]
Great work @manuelroth!!!

> The visual result is almost identical(I only imported the data of latvia to test)

Awesome! This look really close!!

**Comment by manuelroth** [comment]
Thanks, what would the gis open source community do without PostGIS. It's incredibly powerful.
