### ISSUE TITLE
Generate SQL code for trigger, table mgmt and dirty tile detection

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#255]
I think given a YAML definition like this.

```yaml
tables:
  admin_linestring:
    buffer: 4
    min_zoom: 2
    max_zoom: 14
```

We can generate the table tracking and table mgmt functions.

```sql
--The create_tracking_triggers() function
PERFORM recreate_osm_delete_tracking('osm_admin_linestring');
PERFORM recreate_osm_delete_tracking('osm_aero_linestring');

--The update_timestamp(timestamp) function
UPDATE osm_admin_linestring_delete SET timestamp=ts WHERE timestamp IS NULL;
UPDATE osm_admin_linestring SET timestamp=ts WHERE timestamp IS NULL;

--The drop_tables() function
DROP TABLE osm_admin_linestring CASCADE;
DROP TABLE osm_admin_linestring_delete CASCADE;

--The disable_delete_tracking() function
 ALTER TABLE osm_admin_linestring DISABLE TRIGGER USER;
--The enable_delete_tracking() function
ALTER TABLE osm_admin_linestring ENABLE TRIGGER USER;
```

Separate delete tables (instead of discriminating on the **table_name** column).

```
CREATE TABLE IF NOT EXISTS osm_delete_admin_linestring (
    osm_id bigint,
    geometry geometry,
    timestamp timestamp
);
```

The changed tiles calculation.

```sql
CREATE OR REPLACE FUNCTION admin_changed_tiles(ts timestamp)
RETURNS TABLE (x INTEGER, y INTEGER, z INTEGER) AS $$
DECLARE
    buffer_size CONSTANT integer := 4;
BEGIN
    RETURN QUERY (
        WITH geoms AS (
            SELECT osm_id, timestamp, geometry FROM osm_delete_admin_linestring
            UNION ALL
            SELECT osm_id, timestamp, geometry FROM osm_admin_linestring
        )
        SELECT DISTINCT t.tile_x AS x, t.tile_y AS y, t.tile_z AS z
        FROM geoms AS c
        INNER JOIN LATERAL overlapping_tiles(c.geometry, 14, buffer_size)
                           AS t ON c.timestamp = ts
        WHERE t.tile_z BETWEEN 2 AND 14
    );
END;
$$ LANGUAGE plpgsql;
```

We have a lot of tables that are source for the normal styling layer and the buddy label layer.
In this case we only have to calculate dirty tiles once (and use the higher buffer) to make sure both layers are covered.

Same is for generalized tables. We only need to detect dirty tiles for e.g. osm_landusage and because the generalized tables are all derived from it we don't need to calculate dirty tiles for them as well.

@manuelroth Your honest opinions about this :wink: ? You think it is a good idea or perhaps we just make it too complex by writing code that generates code.

**Comment by lukasmartinelli** [comment]
Buumm saves at least **308 lines of SQL** inside the layers.
But now the `generate_sql.py` file has gotten complidated and ugly. 
Will try to clean it up and move the code generation over to dynamic SQL (like in https://github.com/osm2vectortiles/osm2vectortiles/commit/892cb323decbc994d71639b718f0178b22ab44d3) and have the `generate_sql.py` just create a static view.

Looks like this. Quite readable imho.

```sql

CREATE OR REPLACE FUNCTION update_timestamp(ts timestamp) RETURNS VOID AS $$
DECLARE
    t osm_tables%ROWTYPE;
BEGIN
    FOR t IN SELECT * FROM osm_tables
    LOOP
        EXECUTE format('UPDATE %I SET timestamp=%L WHERE timestamp IS NULL;',
            t.table_name, ts
        );
    END LOOP;
END;
$$ language plpgsql
```

**Comment by lukasmartinelli** [comment]
This is how the generated `changed_tiles` function looks like. The buffer, min_zoom and max_zoom
are taken from the YAML file. The `changed_tiles_table` function will then query all tiles for that table (using `overlapping_tiles` **with the specified buffer value**) inside the valid **min_zoom - max_zoom** range.

The nice thing now is that we have a uniform approach for both deleted and inserted tiles. Correctness should still be the same - will need to check whether it results in more tiles to rerender.

```sql
    
CREATE OR REPLACE FUNCTION changed_tiles(ts timestamp)
RETURNS TABLE (x INTEGER, y INTEGER, z INTEGER) AS $$
BEGIN
    RETURN QUERY (
        SELECT * FROM changed_tiles_table('osm_mountain_peak_point', ts, 64, 12, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_place_geometry', ts, 128, 3, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_water_linestring', ts, 4, 8, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_poi_point', ts, 128, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_barrier_linestring', ts, 4, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_admin_linestring', ts, 4, 2, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_barrier_polygon', ts, 4, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_poi_polygon', ts, 128, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_housenumber_point', ts, 64, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_landuse_polygon', ts, 4, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_airport_polygon', ts, 64, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_rail_station_point', ts, 64, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_building_polygon', ts, 2, 13, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_housenumber_polygon', ts, 64, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_aero_polygon', ts, 4, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_airport_point', ts, 64, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_road_geometry', ts, 8, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_aero_linestring', ts, 4, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_water_polygon', ts, 64, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_mountain_peak_point_delete', ts, 64, 12, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_place_geometry_delete', ts, 128, 3, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_water_linestring_delete', ts, 4, 8, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_poi_point_delete', ts, 128, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_barrier_linestring_delete', ts, 4, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_admin_linestring_delete', ts, 4, 2, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_barrier_polygon_delete', ts, 4, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_poi_polygon_delete', ts, 128, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_housenumber_point_delete', ts, 64, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_landuse_polygon_delete', ts, 4, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_airport_polygon_delete', ts, 64, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_rail_station_point_delete', ts, 64, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_building_polygon_delete', ts, 2, 13, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_housenumber_polygon_delete', ts, 64, 14, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_aero_polygon_delete', ts, 4, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_airport_point_delete', ts, 64, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_road_geometry_delete', ts, 8, 5, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_aero_linestring_delete', ts, 4, 9, 14)
        UNION
        SELECT * FROM changed_tiles_table('osm_water_polygon_delete', ts, 64, 5, 14)
    );
END;
$$ language plpgsql;
```

**Comment by ImreSamu** [comment]
>Correctness should still be the same - will need to check whether it results in more tiles to rerender

My quess, that there will be some difference - at least with this tables:
*osm_admin_linestring
*osm_place_geometry
*osm_poi_point,
*osm_poi_polygon
*osm_water_linestring

I have created a simple QA sql scipt -to detect  imposm3 mapping problem.
the current problem:  the imposm3 tables have more record than needs for layers.
see output for hungary osm extract and code 
https://gist.github.com/ImreSamu/fb1cf6f78226aefb16b671ebf071afeb#file-sql_output-txt


my proposed solution: ( not tested yet! )
* osm_admin_linestring  : filtering with admin_level 2 and 4  ( need more modification ) 
 * alternative solutions: create 2 table  osm_admin2_linestring and osm_admin4_linestring 
* osm_place_geometry    : add filtering    name <> ''
* osm_poi_point,        : add filtering    name <> ''
* osm_poi_polygon       : add filtering    name <> ''
* osm_water_linestring  : add filtering    name <> ''

As I know it is not easy filtering  `name <> ''`  with imposm3
I have tested few solutions - probably the imposm3 patching the best:
https://github.com/ImreSamu/imposm3/commit/f1401d1fa2cb0114e010089a0c39b1bcdb71013f
so probably the folowing will work ( but I am not fully tested! )
`
    filters:
      exclude_tags:
      - [ "name", "__nil__" ]
`
the second best solution : normal SQL delete 



on the other side:
- I don't like the current v7 version, because don't show the some important POI-s without name tags.
for example  the amenity=pharmacy : 
* Wordwide    : 78% has a name ( http://taginfo.openstreetmap.org/tags/amenity=pharmacy#combinations )
* Switzerland : 86% has a name ( http://taginfo.openstreetmap.ch/tags/amenity=pharmacy#combinations )
* Hungary     : 66% has a name ( http://taginfo.openstreetmap.hu/tags/amenity=pharmacy#combinations )
Probably I need create more QA report in this topics.

**Comment by lukasmartinelli** [comment]
You're too fast @ImreSamu  ;)

> my proposed solution: ( not tested yet! )

Exactly that is what we had before with the zoom level views. There we really only matched what really was in the tiles. With the delete and update tracking we could no longer do this this nice.

> The approach is now that geometries that are in the DB and have changed will make the tile dirty (buffers are respected).

I would love having the `name <> ''` filter already in imposm3. I can merge your patch into https://github.com/osm2vectortiles/imposm3 (we already have our custom imposm fork - takes a long time until imposm3 team merges changes back upstream https://github.com/omniscale/imposm3/pull/94)

Really cool idea with https://gist.github.com/ImreSamu/fb1cf6f78226aefb16b671ebf071afeb#file-sql_output-txt. This shows exactly what is too much in the tables.
Sadly I just removed the layer views because we no longer need them but I should revert that just for the sake of this script. I'll run it on the server with world import.

I can then use the script to check what features are additionally introduced.
Although careful - many more features doesn't necessarily mean many more dirty tiles in the grand scale.

Btw. do you know what **use_single_id_space** in imposm3 means?
Is this the part that turns relations into negative osm ids?

It seems in the **osm_admin_linestring** we use only 7% of the imported data.
And POI and waterway we could certainly improve as well.
Cool that we exactly have 100% for some layers.

**Comment by lukasmartinelli** [comment]
We should move this discussion to another issue (like "Remove unused data in mapping").

**Comment by ImreSamu** [comment]
>Btw. do you know what use_single_id_space in imposm3 means?

main purpose is avoid conflicts of OSM_ID-s   ; see RelIdOffset info:
* https://github.com/omniscale/imposm3/blob/master/element/element.go#L113
* https://github.com/omniscale/imposm3/search?utf8=%E2%9C%93&q=RelIdOffset&type=Code

this is similar function like  new   `OSM ID Transformation à la Mapbox`  (  see #212 )

my opinion : 
* The Mapbox solution is better for the  [zigzag encoded](https://developers.google.com/protocol-buffers/docs/encoding#types )  vectortiles compression.

**Comment by lukasmartinelli** [comment]
Great insights - so we leave it like it is now. Didn't find any docs on it.

> main purpose is avoid conflicts of OSM_ID-s ; see RelIdOffset info:

**Comment by ImreSamu** [comment]
>Great insights - so we leave it like it is now. Didn't find any docs on it.

my research based opinion:
* the The Mapbox solution is perfect for  Vectortiles 
  * theoretically no osm_id collision.
  * and perfect for compressing

But now for imposm3 processing  need ` use_single_id_space: true`
* for   NO  osm_id collision       (  or not use  `type_mappings` )


see more:
* https://github.com/osm2vectortiles/osm2vectortiles/issues/281
