### ISSUE TITLE
Ensure to map only used data

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#257]
Discussion from #255. This is important because less mapped stuff **means less dirty tiles**.

What could help.

> osm_admin_linestring : filtering with admin_level 2 and 4 ( need more modification )
alternative solutions: create 2 table osm_admin2_linestring and osm_admin4_linestring
osm_place_geometry : add filtering name <> ''
osm_poi_point, : add filtering name <> ''
osm_poi_polygon : add filtering name <> ''
osm_water_linestring : add filtering name <> ''

To do the value filtering we can perhaps use imposm directly.

> As I know it is not easy filtering name <> '' with imposm3
I have tested few solutions - probably the imposm3 patching the best:
ImreSamu/imposm3@f1401d1
so probably the following will work ( but I am not fully tested! )
 filters: exclude_tags: - [ "name", "__nil__" ] 
the second best solution : normal SQL delete

Or just delete the data from the tables.

**Comment by ImreSamu** [comment]
The `osm_admin_linestring`  perfect filtering is not so easy. 

so I would like extending the imposm3 filtering more   -  in the next 48hours
 and create 100% filtering for every table.

**Comment by lukasmartinelli** [comment]
Okay our imposm3 fork now supports the advanced exclude tags.
So we can try to use `filters: exclude_tags: - [ "name", "nil" ]`.

**Comment by lukasmartinelli** [comment]
This is the report for the entire world (takes 1.5 hrs to run).
Pretty similar to the extracts actually. Also cool to see **a feature count on each table**!
Buildings, housenumbers and roads are the largest tables.

| tid                     | all_features | used_features | osmlist                                                                 | layerlist                             | percent | 
|-------------------------|--------------|---------------|-------------------------------------------------------------------------|---------------------------------------|---------| 
| osm_admin_linestring    | 902065       | 66023         | {osm_admin_linestring}                                                  | {admin_layer}                         | 7.32    | 
| osm_aero_*              | 189458       | 189458        | {osm_aero_linestring,osm_aero_polygon}                                  | {aeroway_layer}                       | 100.00  | 
| osm_airport_*           | 43661        | 43661         | {osm_airport_point,osm_airport_polygon}                                 | {airport_label_layer}                 | 100.00  | 
| osm_barrier_*           | 4824394      | 4824394       | {osm_barrier_linestring,osm_barrier_polygon}                            | {barrier_line_layer}                  | 100.00  | 
| osm_building_*          | 178777539    | 178777539     | {osm_building_polygon_gen0,osm_building_polygon}                        | {building_layer}                      | 100.00  | 
| osm_housenumber_*       | 60304686     | 60304686      | {osm_housenumber_point,osm_housenumber_polygon}                         | {housenum_label_layer}                | 100.00  | 
| osm_landuse_*           | 24037401     | 24037401      | {osm_landuse_polygon,osm_landuse_polygon_gen0,osm_landuse_polygon_gen1} | {landuse_overlay_layer,landuse_layer} | 100.00  | 
| osm_mountain_peak_point | 409599       | 409599        | {osm_mountain_peak_point}                                               | {mountain_peak_label_layer}           | 100.00  | 
| osm_place_*             | 5561449      | 2458275       | {osm_place_geometry}                                                    | {place_label_layer}                   | 44.20   | 
| osm_poi_*               | 15699606     | 7937380       | {osm_poi_point,osm_poi_polygon}                                         | {poi_label_layer}                     | 50.56   | 
| osm_rail_station_point  | 177970       | 177970        | {osm_rail_station_point}                                                | {rail_station_label_layer}            | 100.00  | 
| osm_road_geometry       | 94030374     | 94030374      | {osm_road_geometry}                                                     | {road_layer,road_label_layer}         | 100.00  | 
| osm_water_linestring    | 11624368     | 10158677      | {osm_water_linestring}                                                  | {waterway_layer,waterway_label_layer} | 87.39   | 
| osm_water_polygon_*     | 7888542      | 7888542       | {osm_water_polygon_gen1,osm_water_polygon}                              | {water_layer,water_label_layer}       | 100.00  |

**Comment by lukasmartinelli** [comment]
This imposm3 changes are so good @ImreSamu. Thanks. Hope they merge it upstream soon (PR take really long for imposm3 sadly).

I now do the name filtering and admin_level_filtering (like you suggested in your commit).
And that already helps a lot. Still need to find out what the reason for the many unused **waterway_linestring** features is. 

Before:


| tid                     | all_features | used_features | osmlist                                                                 | layerlist                             | percent | 
|-------------------------|--------------|---------------|-------------------------------------------------------------------------|---------------------------------------|---------| 
| osm_admin_linestring    | 8896         | 1713          | {osm_admin_linestring}                                                  | {admin_layer}                         | 19.26   | 
| osm_aero_*              | 927          | 927           | {osm_aero_linestring,osm_aero_polygon}                                  | {aeroway_layer}                       | 100.00  | 
| osm_airport_*           | 83           | 83            | {osm_airport_point,osm_airport_polygon}                                 | {airport_label_layer}                 | 100.00  | 
| osm_barrier_*           | 42754        | 42754         | {osm_barrier_linestring,osm_barrier_polygon}                            | {barrier_line_layer}                  | 100.00  | 
| osm_building_*          | 1854655      | 1854655       | {osm_building_polygon_gen0,osm_building_polygon}                        | {building_layer}                      | 100.00  | 
| osm_housenumber_*       | 586469       | 586469        | {osm_housenumber_point,osm_housenumber_polygon}                         | {housenum_label_layer}                | 100.00  | 
| osm_landuse_*           | 214806       | 214806        | {osm_landuse_polygon,osm_landuse_polygon_gen0,osm_landuse_polygon_gen1} | {landuse_overlay_layer,landuse_layer} | 100.00  | 
| osm_mountain_peak_point | 3742         | 3742          | {osm_mountain_peak_point}                                               | {mountain_peak_label_layer}           | 100.00  | 
| osm_place_*             | 24552        | 12364         | {osm_place_geometry}                                                    | {place_label_layer}                   | 50.36   | 
| osm_poi_*               | 183883       | 97283         | {osm_poi_point,osm_poi_polygon}                                         | {poi_label_layer}                     | 52.90   | 
| osm_rail_station_point  | 2805         | 2805          | {osm_rail_station_point}                                                | {rail_station_label_layer}            | 100.00  | 
| osm_road_geometry       | 940892       | 940892        | {osm_road_geometry}                                                     | {road_layer,road_label_layer}         | 100.00  | 
| osm_water_linestring    | 53611        | 39837         | {osm_water_linestring}                                                  | {waterway_layer,waterway_label_layer} | 74.31   | 
| osm_water_polygon_*     | 23652        | 23652         | {osm_water_polygon_gen1,osm_water_polygon}                              | {water_layer,water_label_layer}       | 100.00  | 



After:

| tid                     | all_features | used_features | osmlist                                                                 | layerlist                             | percent | 
|-------------------------|--------------|---------------|-------------------------------------------------------------------------|---------------------------------------|---------| 
| osm_admin_linestring    | 1716         | 1716          | {osm_admin_linestring}                                                  | {admin_layer}                         | 100.00  | 
| osm_aero_*              | 936          | 936           | {osm_aero_linestring,osm_aero_polygon}                                  | {aeroway_layer}                       | 100.00  | 
| osm_airport_*           | 81           | 81            | {osm_airport_point,osm_airport_polygon}                                 | {airport_label_layer}                 | 100.00  | 
| osm_barrier_*           | 44433        | 44433         | {osm_barrier_linestring,osm_barrier_polygon}                            | {barrier_line_layer}                  | 100.00  | 
| osm_building_*          | 1903832      | 1903832       | {osm_building_polygon_gen0,osm_building_polygon}                        | {building_layer}                      | 100.00  | 
| osm_housenumber_*       | 598921       | 598921        | {osm_housenumber_point,osm_housenumber_polygon}                         | {housenum_label_layer}                | 100.00  | 
| osm_landuse_*           | 218998       | 218998        | {osm_landuse_polygon,osm_landuse_polygon_gen0,osm_landuse_polygon_gen1} | {landuse_overlay_layer,landuse_layer} | 100.00  | 
| osm_mountain_peak_point | 3850         | 3850          | {osm_mountain_peak_point}                                               | {mountain_peak_label_layer}           | 100.00  | 
| osm_place_*             | 12382        | 12382         | {osm_place_geometry}                                                    | {place_label_layer}                   | 100.00  | 
| osm_poi_*               | 98304        | 98304         | {osm_poi_point,osm_poi_polygon}                                         | {poi_label_layer}                     | 100.00  | 
| osm_rail_station_point  | 2796         | 2796          | {osm_rail_station_point}                                                | {rail_station_label_layer}            | 100.00  | 
| osm_road_geometry       | 954961       | 954961        | {osm_road_geometry}                                                     | {road_layer,road_label_layer}         | 100.00  | 
| osm_water_linestring    | 54837        | 40971         | {osm_water_linestring}                                                  | {waterway_layer,waterway_label_layer} | 74.71   | 
| osm_water_polygon_*     | 24237        | 24237         | {osm_water_polygon_gen1,osm_water_polygon}                              | {water_layer,water_label_layer}       | 100.00  |

**Comment by lukasmartinelli** [comment]
@manuelroth The reason for the unused features in **osm_water_linestring** is that we map **drain** and **ditch** but do not use them in the layers (we exclude them).

Is this on purpose? I suppose ditches and drains are shown at the highest zoom level?

**Comment by manuelroth** [comment]
@lukasmartinelli Oh no, forgot to include them in the waterway/waterway_label view. Should I make a commit on the improved_mapping branch?

**Comment by manuelroth** [comment]
This is a very powerful tool, now we have way better view on what data we actually use in the vector tiles.

**Comment by lukasmartinelli** [comment]
> @manuelroth The reason for the unused features in osm_water_linestring is that we map drain and ditch but do not use them in the layers (we exclude them).
> 
> Is this on purpose? I suppose ditches and drains are shown at the highest zoom level?

Added them in commit https://github.com/osm2vectortiles/osm2vectortiles/commit/1a4546274b3301107d9bcfb01c5afe5544f670e5. Mapbox shows them in waterway.

**Comment by manuelroth** [comment]
Ok, thanks.

**Comment by lukasmartinelli** [comment]
Yes now we have 100% usage in all tables. This is huge.

**We now have only the values in the database that we really use in the vector tiles!**
No space is wasted and that makes our dirty tile model much better because now we can operate on the tables #232 and not the layer views.

| tid                     | all_features | used_features | osmlist                                                                 | layerlist                             | percent | 
|-------------------------|--------------|---------------|-------------------------------------------------------------------------|---------------------------------------|---------| 
| osm_admin_linestring    | 1716         | 1716          | {osm_admin_linestring}                                                  | {admin_layer}                         | 100.00  | 
| osm_aero_*              | 936          | 936           | {osm_aero_linestring,osm_aero_polygon}                                  | {aeroway_layer}                       | 100.00  | 
| osm_airport_*           | 81           | 81            | {osm_airport_point,osm_airport_polygon}                                 | {airport_label_layer}                 | 100.00  | 
| osm_barrier_*           | 44433        | 44433         | {osm_barrier_linestring,osm_barrier_polygon}                            | {barrier_line_layer}                  | 100.00  | 
| osm_building_*          | 1903832      | 1903832       | {osm_building_polygon_gen0,osm_building_polygon}                        | {building_layer}                      | 100.00  | 
| osm_housenumber_*       | 598921       | 598921        | {osm_housenumber_point,osm_housenumber_polygon}                         | {housenum_label_layer}                | 100.00  | 
| osm_landuse_*           | 218998       | 218998        | {osm_landuse_polygon,osm_landuse_polygon_gen0,osm_landuse_polygon_gen1} | {landuse_overlay_layer,landuse_layer} | 100.00  | 
| osm_mountain_peak_point | 3850         | 3850          | {osm_mountain_peak_point}                                               | {mountain_peak_label_layer}           | 100.00  | 
| osm_place_*             | 12382        | 12382         | {osm_place_geometry}                                                    | {place_label_layer}                   | 100.00  | 
| osm_poi_*               | 98304        | 98304         | {osm_poi_point,osm_poi_polygon}                                         | {poi_label_layer}                     | 100.00  | 
| osm_rail_station_point  | 2796         | 2796          | {osm_rail_station_point}                                                | {rail_station_label_layer}            | 100.00  | 
| osm_road_geometry       | 954961       | 954961        | {osm_road_geometry}                                                     | {road_layer,road_label_layer}         | 100.00  | 
| osm_water_linestring    | 54837        | 54837         | {osm_water_linestring}                                                  | {waterway_layer,waterway_label_layer} | 100.00  | 
| osm_water_polygon_*     | 24237        | 24237         | {osm_water_polygon_gen1,osm_water_polygon}                              | {water_layer,water_label_layer}       | 100.00  |

**Comment by sfkeller** [comment]
Nice comparison (tool). This discussion shows to me why it's so important to distinguish "data syle" (= mapping OSM data to schema) and "style" (= mapping schema to symbols or vt, graphic oriented). 
=> Would'nt it be even more clear and self-documenting to rename "all_features" and "used_features" to - say - "features_in_database" and "features_in_vector_tiles" - or - "db_features" and "vt_features" ?

**Comment by ImreSamu** [comment]
otherside: Quest for unused database columns :)
* osm_admin_linestring - `area`       ?  
* osm_airport_point    - `name_int`   ?  
* ...

**Comment by ImreSamu** [comment]
FYI 

>The osm_admin_linestring perfect filtering is not so easy.

The current version is very good, but not perfect for osm_admin_linestring
```yml
    filters:
      exclude_tags:
      - [ "admin_level", "__nil__" ]
      - [ "admin_level", "3" ]
      - [ "admin_level", "5" ]
      - [ "admin_level", "6" ]
      - [ "admin_level", "7" ]
      - [ "admin_level", "8" ]
      - [ "admin_level", "9" ]
      - [ "admin_level", "10" ]
    mapping:
      boundary:
      - administrative
      - maritime
``` 

because in Hungary   
*  `admin_level=11`   and `boundary=administrative`  http://www.openstreetmap.org/relation/4307870

and very hard to add all exceptions, typos ...
 
Not critical, but I have created an extended filtering version ,  with the following new experimental syntax : 
```
filters:
   exclude_tags
   - [ key, val]                       // AND key != val
   - [ key, __nil__]                   // AND key IS NOT NULL
   - [ key, __any__]                   // AND key IS NULL
   - [ key, val1,val2]                 // AND key not in ( val1,val2 )
   - [ key, val1,val2,val3, ... valn]  // AND key not in ( val1,val2,val3, ... valn)
   include_tags
   - [ key, val]                       // AND key = val
   - [ key, __nil__]                   // AND key IS NULL
   - [ key, __any__]                   // AND key IS NOT NULL
   - [ key, val1,val2]                 // AND key in ( val1, val2 )
   - [ key, val1,val2,val3, ... valn]  // AND key in ( val1,val2,val3, ... valn)
```
https://github.com/ImreSamu/imposm3/commit/0df03ae6a535271686e22326790e6010f2a8d249
this is allow much perfect mapping, like : 
 
```yml
    filters:
       include_tags:
       - ["admin_level", "2","4"]                            
    mapping:
       boundary:
       - administrative
       - maritime
```
( need more test )

**Comment by lukasmartinelli** [comment]
Great progress on imposm3. Adding more filtering options will help more people than just us.

> Not critical, but I have created an extended filtering version , with the following new experimental syntax :

Just my 2 cents. I would have expected that the filters work more like the mapping.
The `include_tags` will be included if it matches any of the criterias inside the `include_tags` not all of them.

```
filters:
   exclude_tags
   - [ key, val]                       // AND key != val
   - [ key, __nil__]                   // AND key IS NOT NULL
   - [ key, __any__]                   // AND key IS NULL
   - [ key, val1,val2]                 // AND key not in ( val1,val2 )
   - [ key, val1,val2,val3, ... valn]  // AND key not in ( val1,val2,val3, ... valn)
   include_tags
   - [ key, val]                       // OR key = val
   - [ key, __nil__]                   // OR key IS NULL
   - [ key, __any__]                   // OR key IS NOT NULL
   - [ key, val1,val2]                 // OR key in ( val1, val2 )
   - [ key, val1,val2,val3, ... valn]  // OR key in ( val1,val2,val3, ... valn)
```

**Comment by ImreSamu** [comment]
>Just my 2 cents. I would have expected that the filters work more like the mapping.

agree ..
the `include_tags` not a perfect name.  
this is an easy hack, and the imposm3 algorithm  in inside  **logical `AND`** - and to big work to change that to `OR`

What about renaming `include_tags`  to more precise name like:
*   `exclude_negated_tags`
*  `exclude_negate_tags`
*  `negate_exclude_tags`
*  `and_exclude_negated_tags`      ( contains the `and` word )
*   ....

so a little better  ... 

```
filters:
   exclude_tags
   - [ key, val]                       // AND key != val
   - [ key, __nil__]                   // AND key IS NOT NULL
   - [ key, __any__]                   // AND key IS NULL
   - [ key, val1,val2]                 // AND key not in ( val1,val2 )
   - [ key, val1,val2,val3, ... valn]  // AND key not in ( val1,val2,val3, ... valn)
   exclude_negated_tags
   - [ key, val]                       // AND key = val
   - [ key, __nil__]                   // AND key IS NULL
   - [ key, __any__]                   // AND key IS NOT NULL
   - [ key, val1,val2]                 // AND key in ( val1, val2 )
   - [ key, val1,val2,val3, ... valn]  // AND key in ( val1,val2,val3, ... valn)
```

**Comment by lukasmartinelli** [comment]
> this is an easy hack, and the imposm3 algorithm in inside logical AND - and too big work to change that to OR

Sure makes sense.

> What about renaming include_tags to more precise name like:

Very difficult thing to find a good name, I don't have a better one :/
`exclude_negated_tags` is not perfect but ok for me.
