### ISSUE TITLE
Used Features vs Mapped Features Analysis

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#258]
Incorporate the script from #255 https://gist.github.com/ImreSamu/fb1cf6f78226aefb16b671ebf071afeb#file-sql_output-txt from @ImreSamu into the `/tools` section so we can create reports by just running the Docker container.

**Comment by lukasmartinelli** [comment]
Can you @ImreSamu just commit the SQL script to the folder `/tools/mapping-qa-report` (or something like this) since it is your code?

https://gist.github.com/ImreSamu/fb1cf6f78226aefb16b671ebf071afeb#file-sql_output-txt

I will then hack the bash script, Docker container and docker-compose definition around it. This will help.

**Comment by ImreSamu** [comment]
Done ..   see  #259 

Modify , adapt or drop   as you like :)


I would like to create other QA scripts,  
* so it would be better if there will be some  `meta tables`   for the views
