### ISSUE TITLE
Stabilize and freeze mapping.yml and database schema

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#265]
**This issue will be aggregator for small schema issues/discussion**.
Since we're getting close to the rendering after which we can only change the mapping and schema stuff with big costs since the diffs rely on it **we should start freezing it and reviewing it one last time**.

We must hope that the still open map issues have all the data they need to be solved after that.

- [x] **Schema diagram** @lukasmartinelli should also create a database schema diagram now (we need one for the thesis like last time) which will also show us excess column names directly.
- [x] **Find out unused columns**

> otherside: Quest for unused database columns :)
  osm_admin_linestring - area ?
  osm_airport_point - name_int ?
   ...

**Comment by lukasmartinelli** [comment]
Working on the diagram in Google Drive. I could generate them (last time I did but they usually are to ugly to use in a thesis).

## Barriers

Nothing special here. Except it is one of the only layers that doesn't have a label laayer.

![barrier](https://cloud.githubusercontent.com/assets/1288339/14714340/e9c92760-07e4-11e6-893e-e68be5bfe2ea.png)

## Road

We do need the `is_ford`, `construction`, `tracktype`, `service`, `access` all for the `type` and `class` or `structure` values.

![road](https://cloud.githubusercontent.com/assets/1288339/14714343/ed5160aa-07e4-11e6-8346-4f717b9a6665.png)

## Water and Waterways

Wow there goes a lot of thought into making water appear.

- [ ] Perhaps we can use the Natural Earth and OSM Water tables (that are not from imposm) in the same zoom level views (create new ones)? What do you think @manuelroth? Now we pull data in the tm2source file and in the zoom level views.

![water](https://cloud.githubusercontent.com/assets/1288339/14714493/6fcc8b18-07e5-11e6-91c9-5efc7108acb1.png)

**Comment by manuelroth** [comment]
@lukasmartinelli thats a good idea will add it to the zoom level views

**Comment by lukasmartinelli** [comment]
>Won't add the new views to the layer_* view as this view is used for the changed_tile process.

Changed tile process does no longer work with the zoom level views but works with the tables directly since last PR.

You could safely extend the existing views.

**Comment by manuelroth** [comment]
> > Won't add the new views to the layer_* view as this view is used for the changed_tile process.
Changed tile process does no longer work with the zoom level views but works with the tables directly since last PR.

> You could safely extend the existing views.
Ohh right, so we could actually remove the layer_* views?- Because these were only needed for the changed_tile process

**Comment by lukasmartinelli** [comment]
I did remove them but readded them because we need them for the mapping-qa
report.

**Comment by lukasmartinelli** [comment]
After #268 the water diagram looks like this.

![water 2](https://cloud.githubusercontent.com/assets/1288339/14718752/c6b96e56-07f8-11e6-9466-74eabeb56f70.png)

**Comment by lukasmartinelli** [comment]
## Admin

Admin uses a complex combination of Natural Earth and OSM in order to give the best possible borders per zoom level.

![admin](https://cloud.githubusercontent.com/assets/1288339/14720876/d5cae644-0803-11e6-9feb-5dce323015c7.png)

## Housing

We once had the idea whether we could put housenumber_polygon and building_polygon into one table. But because we also have a point table it easier for the understanding to have two separate tables for housenumbers.

![building](https://cloud.githubusercontent.com/assets/1288339/14721133/15d7eae2-0805-11e6-9a29-f004b04d761b.png)

## Places

We still have some ranking problems. But I think we got all the fields that are relevant. Problem there is the scalerank matching.

![place](https://cloud.githubusercontent.com/assets/1288339/14721871/25b2e418-0809-11e6-9c95-9511ac17be84.png)

## Landuse

![landuse](https://cloud.githubusercontent.com/assets/1288339/14722123/43148d44-080a-11e6-98d3-643b0d939c1a.png)

- [ ] `landuse_overlay` missing

## POI

![poi](https://cloud.githubusercontent.com/assets/1288339/14722261/fbc7b2ee-080a-11e6-9256-d3ad3d38b905.png)

## Mountain Peak Label

![mountain_peak](https://cloud.githubusercontent.com/assets/1288339/14722375/8c120fc0-080b-11e6-96e0-b98a3c91392d.png)

## Rail Station Label

![railstation](https://cloud.githubusercontent.com/assets/1288339/14722518/30005524-080c-11e6-803a-7f7a8b19b7ec.png)
