### ISSUE TITLE
Tile analysis

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#271]
### Findings 
From zoom level 0 to 13 the only big difference between streets v7 and osm2vectortiles is the road layer, other layers look pritty good.

The following table compares the feature count of layer road between streets v7 and osm2vectortiles(v1.5). Similar to the layer landuse, they somehow combine the road linestrings from zoom level 2 to 10. 

| tile         | streets v7 | osm2vectortiles(v1.5) |
|--------------|------------|-----------------------|
| 5/16/11      | 2          | 41066                 |
| 6/33/22      | 3          | 71979                 |
| 7/67/44      | 3          | 28249                 |
| 8/133/89     | 10         | 27172                 |
| 9/268/179    | 16         | 11945                 |
| 10/536/358   | 18         | 8751                  |
| 11/1072/717  | 3053       | 8016                  |
| 12/2144/1434 | 1131       | 5404                  |
| 13/4290/2868 | 1087       | 2754                  |
| 14/8580/5737 | 685        | 2638                  |

On zoom level 14 I found some strange differences. The following table shows the feature count for layer building and housenum_label on **zoom level 14**: 

| layer          | streets v7  | osm2vectortiles |
|----------------|-------------|-----------------|
| building       | 1           | 3117            |
| housenum_label | not present | 7413            |

Mapbox combines all buildings to one huge multipolygon, whereas we have every single building polygon. I also found out, that the layer housenum_label is not present any more in streets v7 even though it is [documented](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#housenum_label). Cross checked this with alot of other tiles.

### Conclusion

- I don't think that we are mapping too many roads in the imposm3 mapping, I believe that mapbox does somehow combine these roads to one huge multilinestring(same goes for the building layer). And this must save a lot of space, otherwise they wouldn't do this. However I don't understand yet way this saves so much space. 
- **Missing housenum_label layer**: I  tried to style the layer housenum_label in mapbox studio, couldn't find it there. Either they removed it by intention and forgot to update the documentation or it is a mistake on their side. We should definitely consider removing it too, a lot of space could be saved.

**Comment by manuelroth** [comment]
To combine the roads/buildings to multiple bigger multilinestrings/multipolygons I could apply the same technique as for the landuse polygons.

**Comment by lukasmartinelli** [comment]
> Missing housenum_label layer: I tried to style the layer housenum_label in mapbox studio, couldn't find it there. Either they removed it by intention and forgot to update the documentation or it is a mistake on their side. We should definitely consider removing it too, a lot of space could be saved.

Just checked housenum label is still there but it appears only in z16. Mapbox has additional z15 and z16 where they can fit stuff in.
https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#housenum_label. 

<img width="715" alt="osm_bright_original___mapbox" src="https://cloud.githubusercontent.com/assets/1288339/14760897/6fb1d77a-0950-11e6-8e8a-1410f5bc27c4.png">

**Comment by manuelroth** [comment]
> Just checked housenum label is still there but it appears only in z16. Mapbox has additional z15 and z16 where they can fit stuff in (that's why there are not many buildings in z14)

Ohh right, thank you. I can see them on z16. But the layer building has still just 1 feature per tile (from z13 up to z16). I definitely think that they combine the points to multiple big multipoints.

**Comment by lukasmartinelli** [comment]
> To combine the roads/buildings to multiple bigger multilinestrings/multipolygons I could apply the same technique as for the landuse polygons. I will make a pull request with the implementation and investigate how this impacts the tile size.

I think at least in z14 we want the real building polygons not an aggregation of them.
Also to make them clickable, interact with them.
Perhaps for z13 we can do that (and then just set `underground` to false for the entire multipolygon).

If you just need to create one polygon per tile you can use [ST_Collect](http://postgis.net/docs/ST_Collect.html) only in the tm2source file (perhaps we don't need a separate table there).

For roads at z5, z6 it is okay to have just one multilinestring if it really does save space. Otherwise is just more complex. And if we do this we can also just st_collect all roads (since it is only motorways) and then set oneway=false and structure=none because at this low zoom level structure and oneway doesn't matter.


> And this must save a lot of space, otherwise they wouldn't do this. However I don't understand yet way this saves so much space.

Are the vector tiles you compared from Mapbox actually smaller?

**Comment by manuelroth** [comment]
I now have proof that combining many small geometries into mulitple bigger geometries does reduce the size of the vector tiles drastically. The data in the following table was collected from the same tile (6/22/33): 

|               | with clustering | without clustering |
|---------------|-----------------|--------------------|
| road features | 81              | 18895              |
| pbf size      | 161 kB          | 526 kB             |

The table was created with the same technique as for the landuse polygons:

```sql
CREATE TABLE osm_road_clustered_z5 AS
SELECT ST_CollectionExtract(unnest(ST_ClusterWithin(geometry, 5000)), 2) AS geometry, type              
FROM osm_road_geometry                                                                     
WHERE ST_Geometrytype(geometry) = 'ST_LineString' AND type IN ('motorway', 'trunk')
GROUP BY type;
```

**Comment by sfkeller** [comment]
Nice! But why do you need to check geometry type? Can't you omit this? 
``
WHERE ST_Geometrytype(geometry) = 'ST_LineString' 
``

**Comment by manuelroth** [comment]
@sfkeller In the table osm_road_geometry are geometries of type ST_LineString, ST_MultiPolygon and ST_Polygon. When I create the table without filtering the polygons and mulipolygons(plazas) out, the visual result on the map was very wired looking. Performance-wise this is not a big problem, because this  table is created in a preprocessing step.

**Comment by lukasmartinelli** [comment]
> We now have proof that combining many small geometries into mulitple bigger geometries does reduce the size of the vector tiles drastically. The data in the following table was collected from the same tile (6/22/33):

Well this look so promising that it is probably **worth doing it for all objects that don't have unique metadata** or where we can group on reasonable number of attributes, so let's try this on roads, buildings, landuse, barrier_line?

What you loose as well is the osm_id information (perhaps Mapbox does no longer include it as attribute because of this) but for this great benefit of size it is worth it.



Just some worry as a side note, if we create the table before everything we now have multiple very large multipolygons in the table. Now for higher zoom levels each tile will match this geometry and then Mapnik will need to cut out the stuff in the geometry that does fit in the vector tile e.g. it will throw away a lot of data and put more strain on the PostgreSQL connection. But don't know whether that makes it slower.

BTW. we have to test whether the queries got slower with the clustered tables. I just had some z5-z6 tile jobs that never finish - could perhaps be the landusage. Didn't look closer at it.

I play around whether i can do the collection directly in the vector tile query because it also doesn't require updating the tables.

> The table was created with the same technique as for the landuse polygons:

Table creation is still reasonably fast (10 minutes).

**Comment by sfkeller** [comment]
So the GEOMETRY type must be COLLECTION. And this is fast? Anyway; in this case you could also consider "ST_CollectionExtract(geometry collection, integer type)".

**Comment by manuelroth** [comment]
> Table creation is still reasonably fast (10 minutes).

Good news.

> I play around whether i can do the collection directly in the vector tile query because it also doesn't require updating the tables.

This would be great, I just worry that this makes the queries very slow. Because of this I created this a separate table after the import process.

**Comment by manuelroth** [comment]
> So the GEOMETRY type must be COLLECTION. And this is fast? Anyway; in this case you could also consider "ST_CollectionExtract(geometry collection, integer type)".

Table creation is still reasonably fast (10 minutes). What do you mean by "consider ST_CollectionExtract(geometry collection, integer type)"?

**Comment by sfkeller** [comment]
This would return (multi)linestrings only. See http://postgis.net/docs/ST_CollectionExtract.html . Not sure if this helps.

**Comment by manuelroth** [comment]
> This would return (multi)linestrings only. See http://postgis.net/docs/ST_CollectionExtract.html . Not sure if this helps.

It is already used in the query `ST_CollectionExtract(unnest(ST_ClusterWithin(geometry, 5000)), 2) AS geometry`

**Comment by lukasmartinelli** [comment]
> This would be great, I just worry that this makes the queries very slow. Because of this I created this a separate table after the import process.

In https://github.com/lukasmartinelli/osm-noise-pollution/blob/master/src/vector-datasource/data.yml
I use simply `st_collect` to group all results together and make a GEOMETRYCOLLECTION. And I do this for all roads on the planet on my machine in less than an hour. So could be that is still fast enough.
I know also understand why the tile size was so small there.. haha wondered back then why the size is so small.

I want to try something similar here. If we just use st_collect and grouped by e.g. `type` we get only one geometrycollection per vector tile per type. And st_collect is really fast.

```sql
 SELECT st_collect(st_buffer(geometry, 30)) AS geometry, 1 AS noise_level
FROM osm_railway
WHERE geometry && !bbox!
UNION ALL
SELECT st_collect(st_buffer(geometry, 60)) AS geometry, 2 AS noise_level
FROM osm_railway
WHERE geometry && !bbox!
```

**Comment by manuelroth** [comment]
> If we just use st_collect and grouped by e.g. type we get only one geometrycollection per vector tile per type
Sounds good, lets try this. Would be great if we could do this right inside the query.

**Comment by lukasmartinelli** [comment]
Whether you combine the building polygons or not does make a styling difference as you can see here.

<img width="1146" alt="compare_open_streets_with_mapbox_streets" src="https://cloud.githubusercontent.com/assets/1288339/14766371/35774506-0a07-11e6-891c-642ff7f6eb2e.png">

The `ST_CollectionExtract(unnest(ST_ClusterWithin(geometry, 5000)), 2)` query doesn't produce the desired result: for Switzerland each row in the clustered table contains the entire Switzerland again.
Replaced it with `ST_Collect` in the branch.

<img width="945" alt="sql_query_editor_and_tile_analysis_ _issue__271_ _osm2vectortiles_osm2vectortiles" src="https://cloud.githubusercontent.com/assets/1288339/14766373/5395fe6a-0a07-11e6-9274-8f05f1cbec30.png">

Tried out `ST_Collect` for roads, buildings and landusage. It get's slower for huge amounts of data like on z5 or z6. On z13, z14 (for buildings the queries are not remarkably slower).

**Comment by lukasmartinelli** [comment]
Render Switzerland again with geometry collections.  **When we measure we cannot measure only one PBF we need to measure the entire rendered MBTiles file**.

| extract        | With buildings,roads,landuse clustered | With roads,landuse clustered | 
|----------------|------|------|
| switzerland    | 475MB  | 454MB  |

Actually for buildings it seems that aggregating the buildings **does increase the filesize**.
We need to measure again whether it really helps to aggregate.

For landuse and roads I would need to test a different extract since only the low zoom levels are affected.

**Comment by manuelroth** [comment]
@lukasmartinelli That is really wired. Could you test this already with an other extract?

**Comment by manuelroth** [comment]
Created extracts of switzerland(only switzerland imported) to test whether the clustering reduces the mbtiles filesize. @lukasmartinelli did you have europa imported while doing the extracts?- The extracts seams to be a lot smaller, probably this is the reason. However I come to the same conclusion as you, clustering does not save a lot of space(less than 1%). Clustering of buildings saves the most space. 

| extract     | With road, landuse, building clustered | With road, landuse clustered | With road clustered | no clustering |
|-------------|----------------------------------------|------------------------------|---------------------|---------------|
| switzerland | 210 Mbyte                              | 223 Mbyte                    | 223 Mbyte           | 225M          |

The clustering does not have a big impact on the size of the entire mbtile file, but it reduces the size of individual big tiles (for example 6/33/22 went from 526 kbytes down to 161 kbytes). I would like to keep the clustering just to reach the goal of not having any tiles > 500 kbytes.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli did you have europa imported while doing the extracts?

Yep used europe. Therefore I have data for the full bbox.

> The clustering does not have a big impact on the overall size of the mbtile file, but it reduces the size of individual big tiles (for example 6/33/22 went from 526 kbytes down to 161 kbytes). I would like to keep the clustering just to reach the goal of not having any tiles > 500 kbytes.

Does `mbverify size -s 500000` show any tiles above 500KB now?

**Comment by manuelroth** [comment]
> Does mbverify size -s 500000 show any tiles above 500KB now?

mbverify does not show any tiles above 500KB with the clustered extracts.

> And does using ST_CollectionExtract over ST_Collect yield better results?

`ST_Collect` does return a GEOMETRYCOLLECTION this collection must be transformed to a Multi_* geometry with `ST_CollectionExtract`. If `ST_Collect` is used without ST_CollectionExtract the mbtile size is the same as with no clustering (225 Mbytes).

@lukasmartinelli would it be possible for you to create a bigger extract  (maybe germany or france) and verify the size with/without clustering and also verify if the >500KB tiles disappear. With this we could cross check, if my hypothesis is correct for a bigger extract.

**Comment by manuelroth** [comment]
Oh wait, I can do that myself. Germany should be possible on my server.

**Comment by lukasmartinelli** [comment]
> Oh wait, I can do that myself. Germany should be possible on my server.

:grin:  If you start the import now :)

> mbverify does not show any tiles above 500KB with the clustered extracts.

I am not the biggest fan of grouping the stuff together (just because we loose the osm id and make it more complicated) **but the no tiles above 500KB argument is just very very important and trumps everything**. :+1: 

> @lukasmartinelli would it be possible for you to create a bigger extract (maybe germany or france) and verify the size with/without clustering and also verify if the >500KB tiles disappear. With this we could cross check, if my hypothesis is correct for a bigger extract.

I will run Europe anyway. Gladly these changes are in the tm2source only.

**Comment by manuelroth** [comment]
> :grin: If you start the import now :)
😄 

> I am not the biggest fan of grouping the stuff together (just because we loose the osm id and make it more complicated) but the no tiles above 500KB argument is just very very important and trumps everything. :+1:

Yes, I am with you. It really just makes it more complicated. Let's both cross check this and make a decision afterwords.

**Comment by lukasmartinelli** [comment]
Really nice viz showing how the Protobuf drawing commands work.

https://www.mapbox.com/vector-tiles/specification/

So perhaps since it is encoded as one geometry we save a lot of Move commands and therefore smaller file size?

**Comment by manuelroth** [comment]
@lukasmartinelli Did create an extract of germany with and without clustering(road, landuse and buildings):

| clustering        | size |  time | number of tiles >500KB |
|----------------|------|------|-------|
| yes    | 2489MB  | 1h 34min | 0
| no      | 2511MB | 1h 32min | 3

Details about tiles >500KB:
```bash
6/33/21	1.2 MB
8/132/85	585.6 kB
8/133/85	651.3 kB
```
Came to the same conclusion as before, without clustering there are some tiles which are bigger than 500KB and with clustering these get smaller but it has no impact on the overall size of the mbtiles.

**Comment by manuelroth** [comment]
I think we should stay with clustering for landuse and roads. Not sure if we need clustering for buildings. I will make a last test with london to find out if there are tiles >500KB without clustering the buildings.

**Comment by sfkeller** [comment]
I announced an issue with some "big challengese in digital cartography". Now after some pondering, I think one of the enhancements worth to elaborate, are these issues of handling (schools/hospitals/aeroports/zoo/leisure parks/...) as one aggregated feature with a single name.

**Comment by lukasmartinelli** [comment]
> Came to the same conclusion as before, without clustering there are some tiles which are bigger than 500KB and with clustering these get smaller but it has no impact on the overall size of the mbtiles.

Thanks for the report!!

> I think we should stay with clustering for landuse and roads. Not sure if we need clustering for buildings(for germany it is not needed, as the >500KB tiles are on lower zoom levels). I will do a last test with london to find out whether there are tiles >500KB without clustering the buildings.

I like this solution. Because we only loose the OSM id on low zoom levels but in the highest zoom level 14 the data is identifiable by OSM id.
Let's do it like this.

**Comment by manuelroth** [comment]
> I like this solution. Because we only loose the OSM id on low zoom levels but in the highest zoom level 14 the data is identifiable by OSM id.
Let's do it like this.

Okay, the test with london also didn't showed any >500KB tiles without clustering of buildings. Just to write this down here for the future. Clustering the buildings also impacts the visual appearance.

Example with osm2vectortiles with clustering of buildings:

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14847621/e2ccab38-0c69-11e6-8324-151496969898.png)

Clustered building query:
```sql
SELECT osm_id_polygon(max(osm_id)) as osm_id,
ST_CollectionExtract(ST_Collect(geometry), 3) AS geometry,
building_is_underground(underground) AS underground
FROM (
    SELECT osm_id, geometry, underground
    FROM building_z13
    WHERE z(!scale_denominator!) = 13
    UNION ALL
    SELECT osm_id, geometry, underground
    FROM building_z14
    WHERE z(!scale_denominator!) = 14
) AS building
WHERE geometry && !bbox!
GROUP BY underground
```
