### ISSUE TITLE
Too prominent fountains/wells 

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#279]
In Bern this look a bit weird. Now this is already z14 so we cannot do much. Perhaps we shouldn't map fountains/wells as water? They are more like POIs.

In a better world a good style would actually only show water labels for big water areas.

<img width="907" alt="compare_open_streets_with_mapbox_streets" src="https://cloud.githubusercontent.com/assets/1288339/14769675/5d456534-0a5e-11e6-8780-d402ba57558e.png">

Sorry for the nitpicker issues :) Assigned them to you. Assign them back if you don't want them :)

**Comment by manuelroth** [comment]
No, thats alright these are all issues which can be solved in less than an hour and have a big visual impact. Just keep them coming if you find more of them 😄  

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14781305/03141040-0ae2-11e6-953c-1cd945ece5ce.png)

Result:
fountains/wells are now mapped as poi's.
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14781373/6daf9ea6-0ae2-11e6-90c5-af1388ed361b.png)
