### ISSUE TITLE
Update Documentation and Website

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#291]
A lot has changed from **v1.0** to the soon released **v1.5**.
This is really not urgent but at some point in time we have to rework the site documentation (but let's first create some thesis material).

Please provide other input what to document if you are keen to see special documentation.

## Docs

I think in the docs we should stop promoting both ways (rendering rasters and serving vector tiles) and now only **focus on serving vector tiles**. Since this is much easier.

We can still keep the old docs around but with v1.5 **we support Mapbox GL primarily** and don't test the maps on Mapnik.

- [x] Create clear get started tutorial using Mapbox GL
- [x] Focus on Mapbox GL and create separate section for rasters
- [x] Serve vector tiles on your own? Which server - https://github.com/klokantech/tileserver-gl ?
- [ ] Add Mobile SDK example projects (since we have several example projects from osm2vectortiles,klokantech and manuelroth

I initially wanted to suggest to move the developer documentation to GitHub wiki or something and just link to it but actually the Google Search indexes these pages and helps the page rank of osm2vectortiles and drives people to the project so we should probably still keep the dev docs there.

- [x] Update developer documentation (nearly everything is now outdated)
- [x] Improve README (provide clear starting point)
- [x] Add README to each component (we once had READMEs on each component to explain what it does - I really liked the explorative way this provided to new GitHub visitors)
- [ ] Add newest used keys #131 

## Maps

- [x] Add the additional vector maps for the other maps in Mapbox Studio

## Downloads

- [ ] Copy the downloads page and create kind of a **v1.0** version and put a link to it for older downloads
- [x] Replace the download page now with the new links to the downloads
- [x] Think of a way how we provide all updates? Perhaps a mirror structure similar to osm planet

## FAQ

- [ ] Update FAQ: What is the difference from other Vector Tile services?

**Comment by manuelroth** [comment]
- [ ] Document additional data described in #307 and how it can be styled

**Comment by lukasmartinelli** [comment]
We highlighted what is important to improve on the docs website.
We want to simplify the docs. At the moment it is way too complicated.

We think the developer docs section can probably better be covered by having good docs on GitHub for the people that want to work with the project and focus on the user docs.

There we want to create one very good tutorial showing how to serve your on vector tiles (without Docker, just tileserver-gl if possible) and then use them in a site.


![cursor_and_documentation_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/15106664/31a85b20-15cb-11e6-8a53-bef334b068d4.png)

**Comment by manuelroth** [comment]
- [ ] Document what kind of hardware is needed to render the entire world (define a scenario)
