### ISSUE TITLE
Thesis planing

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#292]
- Planing of the thesis with milestones and issues turned out to be very effective. So we want to keep this approach for the bachelor thesis. 
- Storing the latex source in a repository on github is also a must because we don't want to solely rely on [sharelatex](https://www.sharelatex.com). 
- Syncing changes between sharelatex and github is not necessary during the writing phase. We will just sync them at the end.
- I want to store and plan the bachelor thesis in a separat repository than [osm2vectortiles-thesis](https://github.com/osm2vectortiles/osm2vectortiles-thesis), so I created the [bachelor-thesis](https://github.com/osm2vectortiles/bachelor-thesis) repository and renamed the old thesis repo to [study-thesis](https://github.com/osm2vectortiles/study-thesis) to have a consistent naming.

**Comment by lukasmartinelli** [comment]
Our bachelor thesis tasks/discussions will continue in https://github.com/osm2vectortiles/bachelor-thesis so I will close this.
Thanks for setting it up.
