### ISSUE TITLE
Add Nairobi and Havanna to city extracts

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#293]
- Nairobi (Kenya): http://www.openstreetmap.org/relation/3492709
- Havanna (Cuba): http://www.openstreetmap.org/relation/5252057
- Alphabetically sort city extracts

**Comment by ImreSamu** [comment]
I propose a new tradition :)
* Every new `OSM2Vectortiles member` has to be a right to propose a new city extracts.

My choose : 
*  Budapest (Hungary) : http://www.openstreetmap.org/relation/1244004

Rationale: 
* the ideal for testing maps   -> always on the contributor  neighborhood 
* ( and )  a little reward  :)

**Comment by lukasmartinelli** [comment]
> Budapest (Hungary) : http://www.openstreetmap.org/relation/1244004

Would be nice to see something different than always Zurich in the examples as well :grin: 

If we can get a big list of bounding boxes for city extracts we can also do the same as for countries. Extract 200 cities and list them as searchable extracts on the site.

**Comment by manuelroth** [comment]
Great idea @ImreSamu. The current selection is very random, just chosen well-know cities of every continent. Do have other cities you miss?

**Comment by sfkeller** [comment]
Howto get BBOX with online tools?
1. Search location at http://osm.org, note relation OSM id (admin. boundaries always are r.).
2. Given OSM id relation get polygon: http://polygons.openstreetmap.fr/
3. On same site: If need a buffer, choose line. If need simplified polygon, generate simplified polygon.
4. To get BBOX, paste result to http://geojson.io/ and choose menu "Meta > Add bboxes".

**Comment by hannesj** [comment]
A possibility would be to use the list compiled by Mapzen for their metro extracts, which can be found [here](https://github.com/mapzen/metroextractor-cities/blob/master/cities.geojson)

**Comment by lukasmartinelli** [comment]
> A possibility would be to use the list compiled by Mapzen for their metro extracts, which can be found here

Ready made bounding boxes as GeoJSON including the name. That's actually all we need.

**Comment by hyperknot** [comment]
+1 for Budapest :-)

**Comment by ImreSamu** [comment]
automatic selection is a good idea. 

my _first_  proposal  -  for fine customization:

* with a basic filter  -   
 *  for capital cities 
    * ` [ population  >  0.5M AND  capital=yes  AND   [ area(city) / area(country) < 0,3 ]` ]
 *  and  for  the big cities .  
    *  `[  population >  2M    AND   [ area(city) / area(country) < 0,3 ] ]`
* with  
  * include(city list )
  * exclude(city list) 

the `[ area(city) / area(country) < 0,3 ]`  for  excluding  city-states ( like `Singapore`,  `Vatican` )

for example - now there are 2 versions in the downloading:
*  `Singapore` as a City 
*  `Singapore` as a Country
see  [create-extracts.sh](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/create-extracts/create-extracts.sh)
```
create_extract "singapore.mbtiles" "103.4666667" "1.0303611" "104.6706735" "1.6130449"
create_extract "singapore.mbtiles" "103.84417"   "1.28469"   "103.86235"   "1.30287"
```

**Comment by hannesj** [comment]
They have it available also as plain JSON, which should be simpler to import at https://github.com/mapzen/metroextractor-cities/blob/master/cities.json

**Comment by lukasmartinelli** [comment]
Cities and countries TSV I can then later parse in #294 to create extracts.

- https://github.com/osm2vectortiles/osm2vectortiles/blob/feature/mbtiles-extract-csv/src/create-extracts/country_extracts.tsv
- https://github.com/osm2vectortiles/osm2vectortiles/blob/feature/mbtiles-extract-csv/src/create-extracts/city_extracts.tsv

**Comment by sfkeller** [comment]
As soon as e.g. Havanna is showing up on http://osm2vectortiles.org/downloads/ we can tweet about supporting the Cuba Conference too :-) https://twitter.com/Mapbox/status/724616125301030913
