### ISSUE TITLE
proposal : refactoring  variable name "osm_id" to "id"

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#304]
Because some imposm3 internals - I propose renaming all "osm_id" to "id"

Pro:
- minus 1 variable per table 
- minus 1 index per table
- for Hungary - the public schema size ( after `docker-compose run import-osm` - without other imports )  
 * decreased from  644 MB -> to  599 MB  ( calculated by https://wiki.postgresql.org/wiki/Schema_Size )

Con:
- less user friendly in the code
- need massive refactor the code base ..  [ `grep osm_id src/* -r | wc -l`   ]

 
So I propose changing the mapping file from: 
```yml
  admin_linestring:
    fields:
    - name: osm_id
      type: id
```
      
to

```yml
  admin_linestring:
    fields:
    - name: id
      type: id
```
      
or a lazy programmer version:
*  ` sed -i "s/osm_id/id/g"  src/import-osm/mapping.yml  `      
      

## minimal testing:

Testing without other import 
```bash
docker-compose up -d postgis
sleep 10
rm -f ./import/*.pbf
cp ./hungary-latest.osm.pbf      ./import/hungary-latest.osm.pbf
docker-compose run import-osm
```

### current mapping version:

```sql
osm=# \d osm_admin_linestring
                                      Table "public.osm_admin_linestring"
   Column    |            Type             |                             Modifiers                             
-------------+-----------------------------+-------------------------------------------------------------------
 id          | integer                     | not null default nextval('osm_admin_linestring_id_seq'::regclass)
 osm_id      | bigint                      | 
 timestamp   | timestamp without time zone | 
 admin_level | integer                     | 
 maritime    | smallint                    | 
 area        | real                        | 
 geometry    | geometry(LineString,3857)   | 
Indexes:
    "osm_admin_linestring_pkey" PRIMARY KEY, btree (id)
    "osm_admin_linestring_geom" gist (geometry)
    "osm_admin_linestring_geom_geohash" btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326))) CLUSTER
    "osm_admin_linestring_osm_id_idx" btree (osm_id)

osm=# SELECT  pg_size_pretty( SUM(pg_total_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename)))::BIGINT ) FROM pg_tables WHERE schemaname ='public';
 pg_size_pretty 
----------------
 644 MB
(1 row)
```

### refactored version 
* minus 1 variable per table
* minus 1 index  per table
* public schema size decreased  644 MB ->  599 MB ( hungarian data )

```sql
osm=# \d osm_admin_linestring
          Table "public.osm_admin_linestring"
   Column    |            Type             | Modifiers 
-------------+-----------------------------+-----------
 id          | bigint                      | 
 timestamp   | timestamp without time zone | 
 admin_level | integer                     | 
 maritime    | smallint                    | 
 area        | real                        | 
 geometry    | geometry(LineString,3857)   | 
Indexes:
    "osm_admin_linestring_geom" gist (geometry)
    "osm_admin_linestring_geom_geohash" btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326))) CLUSTER
    "osm_admin_linestring_id_idx" btree (id)

osm=# SELECT  pg_size_pretty( SUM(pg_total_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename)))::BIGINT ) FROM pg_tables WHERE schemaname ='public';
 pg_size_pretty 
----------------
 599 MB
(1 row)
```

**Comment by manuelroth** [comment]
I think this is worth the hastle. Would love to see a PR for this. Easiest would be to change the zoom level views of all [layers](https://github.com/osm2vectortiles/osm2vectortiles/tree/master/src/import-sql/layers) to use `id AS osm_id`. With this you don't have to touch the [source project](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/osm2vectortiles.tm2source/data.yml) at all.

**Comment by lukasmartinelli** [comment]
Very good proposal. Does our imposm3 pro @ImreSamu  know whether the diff import still works with this?

Since it seems that you already managed to rename it once would be cool if you could create a branch on the osm2vectortiles repo with those changes.

> Easiest would be to change the zoom level views of all layers to use id AS osm_id. With this you don't   have to touch the source project at all.

Good idea we just have to rename the mapping and then all files inside `src/import-sql/layers`
and probably some other SQL files in `src/import-sql`. We can do that after we have the branch for the mapping with what already works for importing. 

```
$ grep osm_id src/* -r | wc -l 
$ 630
```

**Comment by ImreSamu** [comment]
Thank you! 

I will try to research more deeply - and I will create a new branch  with a proposed new changes 
[  in a next few days ]

**Comment by ImreSamu** [comment]
Code merged.  -  Mission completed.
