### ISSUE TITLE
Creating vector tiles throws numerous errors

### ISSUE THREAD

**Issue by mr** [osm2vectortiles/osm2vectortiles#309]
To recreate
1. Go to http://osm2vectortiles.org/docs/own-vector-tiles/
2. Run the commands in order
3. run `$ docker-compose up import-osm` (step 4)
4. First error: `function drop_tables() does not exist` (It keeps running after this so this may be intentional)
5. Second error:
```
import-osm_1            | Create osm_water_point table with precalculated centroids
import-osm_1            | DROP TABLE IF EXISTS osm_water_point CASCADE;
import-osm_1            | psql:water_point_table.sql:1: NOTICE:  table "osm_water_point" does not exist, skipping
import-osm_1            | DROP TABLE
import-osm_1            | CREATE TABLE osm_water_point AS
import-osm_1            | SELECT osm_id,
import-osm_1            |        topoint(geometry) AS geometry,
import-osm_1            |        timestamp,
import-osm_1            |        name, name_fr, name_en, name_de,
import-osm_1            |        name_es, name_ru, name_zh,
import-osm_1            |        area
import-osm_1            | FROM osm_water_polygon;
import-osm_1            | SELECT 1230
import-osm_1            | CREATE INDEX ON osm_water_point USING gist (geometry);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_water_point
import-osm_1            | USING btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326)));
import-osm_1            | CREATE INDEX
import-osm_1            | Update osm_place_polygon with point geometry
import-osm_1            | UPDATE osm_place_point
import-osm_1            | SET geometry = topoint(geometry)
import-osm_1            | WHERE ST_GeometryType(geometry) <> 'ST_Point';
import-osm_1            | UPDATE 72
import-osm_1            | Update scaleranks from Natural Earth data
import-osm_1            | UPDATE osm_place_point
import-osm_1            | SET scalerank = improved_places.scalerank
import-osm_1            | FROM
import-osm_1            | (
import-osm_1            |     SELECT osm.osm_id, ne.scalerank
import-osm_1            |     FROM ne_10m_populated_places AS ne, osm_place_point AS osm
import-osm_1            |     WHERE
import-osm_1            |     (
import-osm_1            |         ne.name ILIKE osm.name OR
import-osm_1            |         ne.name ILIKE osm.name_en OR
import-osm_1            |         ne.namealt ILIKE osm.name OR
import-osm_1            |         ne.namealt ILIKE osm.name_en OR
import-osm_1            |         ne.meganame ILIKE osm.name OR
import-osm_1            |         ne.meganame ILIKE osm.name_en OR
import-osm_1            |         ne.gn_ascii ILIKE osm.name OR
import-osm_1            |         ne.gn_ascii ILIKE osm.name_en OR
import-osm_1            |         ne.nameascii ILIKE osm.name OR
import-osm_1            |         ne.nameascii ILIKE osm.name_en
import-osm_1            |     )
import-osm_1            |     AND (osm.type = 'city' OR osm.type = 'town' OR osm.type = 'village')
import-osm_1            |     AND st_dwithin(ne.geom, osm.geometry, 50000)
import-osm_1            |     ) AS improved_places
import-osm_1            | WHERE osm_place_point.osm_id = improved_places.osm_id;
import-osm_1            | psql:update_scaleranks.sql:23: ERROR:  relation "ne_10m_populated_places" does not exist
import-osm_1            | LINE 6:     FROM ne_10m_populated_places AS ne, osm_place_point AS o...
import-osm_1            |                  ^
```

I've also tried doing things in a different order with import-osm occurring last. However when exporting, I get this error

```
export_1                | /usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
export_1                |         if (err) throw err;
export_1                |                  ^
export_1                |
export_1                | Error: Postgis Plugin: ERROR:  relation "landuse_z13toz14" does not exist
export_1                | LINE 1: SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHE...
export_1                |                                                 ^
export_1                | in executeQuery Full sql was: 'SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHERE "geometry" IS NOT NULL LIMIT 1;'
export_1                |
export_1                |     at Error (native)
export_1                |     at /usr/local/lib/node_modules/tilelive-tmsource/index.js:111:18
export_1                |     at Array.map (native)
export_1                |     at normalize (/usr/local/lib/node_modules/tilelive-tmsource/index.js:100:35)
export_1                |     at /usr/local/lib/node_modules/tilelive-tmsource/index.js:185:19
export_1                |     at tryToString (fs.js:414:3)
export_1                |     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
osm2vectortiles_export_1 exited with code 1
```

I think the instructions may be out of date.

**Comment by manuelroth** [comment]
@mr Yes, you are right the documentation is out of date. We will fix that in #291. Sorry for the inconvenience. I give you the instructions here and fix it in our website.

1. Run `docker-compose run import-external` - Imports external data (natrual earth)
2. `cd import` && `wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf` - Download some OSM data and put it in the import directory
3. Run `docker-compose run import-osm` - Imports the OSM data
4. Run `docker-compose run import-sql` - Imports SQL Utilities
5. Run `docker-compose run export` - Creates the vector tiles and puts an MBTiles file in the export folder
5. Run `docker-compose run serve` - Starts a webserver and serves from the MBTiles file

Please don't hesitate to right again if you experience another problem.

**Comment by manuelroth** [comment]
@mr Just updated the [documentation](http://osm2vectortiles.org/docs/own-vector-tiles/) for creating your own vector tiles. A more comprehensive update of your documentation will follow with #291.

**Comment by mr** [comment]
Thank you! Is there any documentation on how to serve with tileserver-gl instead of the normal tileserver?

**Comment by manuelroth** [comment]
Not yet, but this will be server we suggest and use in our updated tutorial.

**Comment by mr** [comment]
Ok, I will keep an eye out for that while I try to get tileserver-gl to work.

Oh, also all of my tiles render as completely black when i go to the test page from `docker-compose run serve`. Do you know if this is a problem with the mbtiles export or something with tileserver-mapnik? The other docker commands didn't throw errors.

**Comment by manuelroth** [comment]
You mean black like the following?
![bildschirmfoto 2016-05-02 um 22 26 49](https://cloud.githubusercontent.com/assets/1810384/14966924/00a0cabe-10b5-11e6-9b5b-e96f1773f63a.png)

For the data to be styled you need to download a style project and add it to the export folder.
1. `git clone https://github.com/mapbox/mapbox-studio-osm-bright.tm2.git`
2. Now run `docker-compose up serve` again and you should see your map with the bright style
![bildschirmfoto 2016-05-02 um 22 32 23](https://cloud.githubusercontent.com/assets/1810384/14967065/c9773662-10b5-11e6-8c28-def439560b81.png)

**Comment by mr** [comment]
No I mean it is entirely black. I thought it was a problem with the viewer,
but when I download /0/0/0.png the file is a 100% black square. Same for
zooming in or panning.

**Comment by manuelroth** [comment]
Did you update the BBOX environment variable to fit the extract?
In the export part of the `docker-compose.yml` file there is a BBOX variable this variable defines which area should be rendered during the export process.
```
export:
  image: "osm2vectortiles/export"
  command: ./export-local.sh
  volumes:
   - ./export:/data/export
   - ./osm2vectortiles.tm2source:/data/tm2source
  links:
   - postgis:db
  environment:
    BBOX: "8.34,47.27,8.75,47.53"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
```

**Comment by manuelroth** [comment]
Also if the MIN_ZOOM variable is set to 8, the above zoom levels (0-7) won't be rendered. So if you request a tile on zoom level 0 (/0/0/0.png) like you did, you will get a black square. Probably this is the problem.

**Comment by manuelroth** [comment]
Not a very good default value, should definitely be 0.

**Comment by lukasmartinelli** [comment]
Sorry for the inconvenience.

This issue is a very good example how we need to improve our public docs to be more straightforward and less complex. Thanks for handling @manuelroth

**Comment by manuelroth** [comment]
Yes, definitely. Would it make sense to combine the 3 import steps(import-external -> import-osm -> import-sql) to one big import?- They are all depending on each other anyway.

**Comment by manuelroth** [comment]
@mr Would you be up to give us feedback again once we prepared the new documentation?

**Comment by lukasmartinelli** [comment]
> Yes, definitely. Would it make sense to combine the 3 import steps(import-external -> import-osm -> import-sql) to one big import?- They are all depending on each other anyway.

These import steps are only detached so that we as developers can iterate on each container separately. For example import-external changes nearly never while import-osm now changed sometimes and import-sql will change very often. This makes it a bit impractical to always do the entire import again.
Also each container has different requirements to the image (ogr2ogr, imposm3 and psql).


I think we don't need to combine it further (but I also played with the thought).
I agree that it would make it easier for people to get started but as soon as you dig more into it it get's clearer why the separation makes sense. We just need to document it very well (started writing in the docs of each container about what requirements need to be met before it is run).

**Comment by mr** [comment]
I will gladly give feedback on new documentation. I'm very interested in getting this to work, so I'll be reading as much as I can. Is there a repo associated with the web documentation? If I ever manage to get tileserver-gl working I'd be willing to contribute.

I've changed MIN_ZOOM to 0, yet I'm still getting only black tiles. I've followed all the other instructions and they haven't thrown any errors. I also have not done the optional merging of lower zoom levels.

**Comment by manuelroth** [comment]
Thats good to hear. Our [project site](http://osm2vectortiles.org/) is running on [gh-pages](https://pages.github.com/) which is essentially just another branch ([gh-pages](https://github.com/osm2vectortiles/osm2vectortiles/tree/gh-pages)) in this repository.

Hm, have you tried requesting a tile on a higher zoom level(z8 or z14). What is the extract/city you are trying to look at?- By the way xyz coordinate can very easily be retrieved with this [website](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/)

**Comment by mr** [comment]
I've tried zooming in and I can see in the `docker-compose up serve` output returning 200 for higher zoom levels, but I don't think that's where the extract is. I'm using the extract at https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf, so I think the bbox for the default export is correct. Is there a way to have the server center on that bbox and zoom higher by default?

Also if I set MIN_ZOOM to 0, shouldn't I get at least one tile at z0 or z1 no matter where the extract is located? It should also be pretty obvious because of the external imports of water, labels, natural earth, etc.

**Comment by mr** [comment]
![358](https://cloud.githubusercontent.com/assets/2790016/14994332/56bf5004-113d-11e6-99d4-e506a3e50bb8.png)

10/536/358.png looks like this, so apparently it is rendering something. Is there an way I can easily zoom one of the maps to this area?

**Comment by manuelroth** [comment]
> Is there an way I can easily zoom one of the maps to this area?

Apparently there is not an easy way to do this. 

What you can do is click on source code of leaflet and copy the source code into an index.html file.
![tileserver_-_maps_rendered_from_vector_tiles](https://cloud.githubusercontent.com/assets/1810384/14996215/2c451610-1179-11e6-8886-8715f73f70ce.png)

Now you need to alter the parameters of the setView([long, lat], zoom_level) method, for zurich this would be `setView([47.3754914,8.5451405], 10)`:
![tileserver_-_maps_rendered_from_vector_tiles](https://cloud.githubusercontent.com/assets/1810384/14996263/6189a516-1179-11e6-8f36-defc6c6d5645.png)

Now click on the index.html file and you should see your map zoomed in to zurich.

**Comment by mr** [comment]
Thanks, looks like everything is generating correctly. If I ever manage to figure it out, I'll try to write a serve-gl, or something like that for tileserver-gl.
