### ISSUE TITLE
"docker-compose up export" step fails

### ISSUE THREAD

**Issue by fitsoft** [osm2vectortiles/osm2vectortiles#313]
Hello,
I have followed the instructions listed at http://osm2vectortiles.org/docs/own-vector-tiles/ with Zurich PBF and it worked (including the visualization).
However, to build my own tiles and for testing purposes, I am using Buenos Aires PBF (https://s3.amazonaws.com/metro-extracts.mapzen.com/buenos-aires_argentina.osm.pbf). Prior to running the export step, I change the BBOX line to BBOX: "-58.89,-34.96,-57.99,-34.29"  as indicated and the export step throws an error in tilelive-copy javascript file (please see attached image). 

I have also followed the instructions listed in the thesis and the same error pops up.

I don't quite understand why tilelive-copy is invoked at this point of the process. It is my understanding that tilelive-copy allows to extract a subset of tiles from an mbtiles database. At this point the actual mbtiles database has to be created. 

Any help on how to fix this error will be greatly appreciated. 

It is also worth noting that this is a great project! 

Regards,

Clara

![error](https://cloud.githubusercontent.com/assets/5429957/14985501/1cda5cc2-111e-11e6-8be5-a1e8b0333819.png)

**Comment by manuelroth** [comment]
Also had this error once, it is because bbox's starting with a negative number are not handled properly. I found a workaround, just add a space before the negative sign => `" -58.89,-34.96,-57.99,-34.29"`

**Comment by manuelroth** [comment]
We have to investigate, what causes this error.

**Comment by lukasmartinelli** [comment]
> Also had this error once, it is because bbox's starting with a negative number are not handled properly. I found a workaround, just add a space before the negative sign => " -58.89,-34.96,-57.99,-34.29"

It is exactly that. I think using the named parameter differently https://github.com/osm2vectortiles/osm2vectortiles/commit/01612da95fc31112df8c0183a0b73da373ac961b can fix it (doing something like this in the export Python script).

**Comment by manuelroth** [comment]
> It is exactly that. I think using the named parameter differently 01612da can fix it (doing something like this in the export Python script).

That was quick 👍

**Comment by fitsoft** [comment]
Hi Lukas, Manuel,

Thanks for the quick turnaround!
Now I passed that but even if I have a zoom range of 8 to 14, I get a PostGIS error: "relation "landuse_z5toz8" does not exist"

Any hint on this!?

Thanks!

**Comment by manuelroth** [comment]
You have to run `docker-compose run import-sql`

**Comment by fitsoft** [comment]
I've done that already with exit code 0 ...

**Comment by manuelroth** [comment]
Oh, now I get it. Can you make a `git pull`?- This is a very recent change.

**Comment by fitsoft** [comment]
doing it right now

**Comment by fitsoft** [comment]
Should I just repeat the export step or I would need to start from the beginning?

**Comment by manuelroth** [comment]
Just repeating the export step should work.

**Comment by fitsoft** [comment]
Ops! Same error:
Error: Postgis Plugin: ERROR:  relation "landuse_z5toz8" does not exist

**Comment by manuelroth** [comment]
Would you be up to do a quick skype call?- It is probably easier to troubleshoot. You should find me on skype with this email adresse: manuelroth@hotmail.ch

**Comment by manuelroth** [comment]
Did the `git pull` command fetch any new changes?

**Comment by fitsoft** [comment]
Hello Manuel, 

It did bring about 33 files changed. It did work now! Awesome! Thanks!

**Comment by manuelroth** [comment]
Oh, great to hear.

**Comment by fitsoft** [comment]
I have a short question: if I want to add new regions can I just repeat the steps from import-osm on?

**Comment by manuelroth** [comment]
> I have a short question: if I want to add new regions can I just repeat the steps from import-osm on?

No the process is not intended to add multiple independent regions. The idea is to import a pbf-extract and export as vector tiles. If you want to have multiple regions this is the way to do it.
