### ISSUE TITLE
Mapnik Timeouts

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#314]
While on the PostGIS side everything is happy and shiny I now get a lot of Mapnik copy timeouts.
Namely Mapnik is on 400% CPU consuming GBs of data but producing nothing and is eventually failing - while no expensive queries go onto PostGIS.

One example of such a tile is this in the middle of nowhere.

![geojson_io](https://cloud.githubusercontent.com/assets/1288339/15045924/7345c27a-12dd-11e6-9615-b5bffe8cc715.png)

Command to reproduce:

```bash
tilelive-copy --scheme 'pyramid' --minzoom 8 --maxzoom 14 --bounds='-22.5,79.6871841545,-21.09375,79.9359182463' --timeout=60000 --slow=60000 'tmsource:///tmp/project' 'mbtiles:///usr/src/app/ab1b9bc5f65b4bbbbb71994490e8516e06abdb14.mbtiles'
```

Investigated a bit by removing layers from tm2source to see what might be the problem.

- [x] removing water doesn't help
- [x] removing landuse doesn't help
- [x] removing waterway doesn't help
- [x] removing country_label, marine_label, state_label, place_label doesn't help
- [x] removing water_label doesn't help
- [x] removing aeroway, barrier_line, building, road doesn't help
- [x] removing landuse_overlay doesn't help
- [x] removing admin, poi_label, road_label, housenum_label, airport_label, rail_station_label doesn't help
- [x] removing waterway_label doesn't help

Okay at this point I just deleted everything except one layer the `rail_station_label`. At this point it works. So now I am adding the layers that might be the problem again as it seems it is not a single layer that is the problem.

Another crazy man's thought just switched the scheme from `pyramid` to `scanline`and then it actually starts faster (doesn't stall Mapnik at the beginning) and I see that all the z13 and z14 tiles require all about 30s of rendering time?!! until eventuall it times out as well.

So now the question is why do some tiles require 30s of rendering? Do they receive so much data that that Mapnik needs to much processing time (perhaps we forgot a where clause or something).

- [x] having just water using pyramid takes 1m and 10s
- [x] having just water using scanline takes 14s
- [x] having just water using pyramid takes 1m and 13 s

So scanline is better for a small bbox?

Continue with finding out what layer might be the problem by adding layers.

- [x] adding landuse and waterway to water with scanline takes takes 1m 14

So is either landuse or waterway the problem?

- [x] having just landuse using pyramid times out
- [x] having just water using pyramid takes 1m and 8s
- [x] having just waterway using pyramid takes 12s

So we now know that landuse is a good problem child for testing.

Let's do this differently again. Let's measure how much traffic flows from PostGIS into the worker when we just render this bbox.

It is a whooping **1.7 GB** and after that it times out (since I gave a copy timeout of 60s). That means something is really fishy.

Let's do this just for the layers.

- [x] having just waterway takes 10MB
- [x] having just water takes already 872MB
- [x] having just landuse takes even more 1.893GB  after which it times out
- [x] having just landuse with a timeout of 120s consumes 4.009 GB and also times out

So let's jump to some conclusions.

- Copy timeouts happen when Mapnik is waiting for the copy process from PostGIS to Mapnik and this takes longer than the specified timeout (per default 60s)
- The layer queries consume way too much input data aka they throw away nearly all data they receive

Actions.

- [x] Find out why landuse or water are consuming so much input data
- [x] Limit number of data transferred from PostGIS to Mapnik

**Comment by lukasmartinelli** [comment]
Assumption: Grouping the landuse stuff together might be the cause
Actually this is not the case. When I remove the grouping it still consumes 2.023 GB and times out.

Assumption: Do the layer queries have a bug?
The queries look good imho.
Let's find out at which zoom level this happens by limiting the tilelive copy command to certain zoom level ranges.
- z8-z9 is fast.
- z8-z12 is fast
- z8-z13 is slow

So the problem happens at z13.

Assumption: Are there very big landuse geometries?
So it might just be that there are huge landuse geometries that always need to be transferred.
For example the query below yields a 2.3MB glacier (which is not much but there are probably bigger ones) And 2.3 MB times 5000 is 14.828265 gigabytes

Testing this with query.

```sql
SELECT octet_length(ST_AsBinary("geometry")) AS geom_byte_size,"osm_id","class","type" FROM (
	  SELECT osm_ids2mbid(osm_id, true) AS osm_id, geometry, landuse_class(type) AS class, type
	    FROM (
	    SELECT osm_id, geometry, type
	    FROM landuse_z5toz6
	    WHERE z(68247.3) BETWEEN 5 AND 6
	    UNION ALL
	    SELECT osm_id, geometry, type
	    FROM landuse_z7toz8
	    WHERE z(68247.3) BETWEEN 7 AND 8
	    UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z9
	      WHERE z(68247.3) = 9
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z10
	      WHERE z(68247.3) = 10
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z11
	      WHERE z(68247.3) = 11
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z12
	      WHERE z(68247.3) = 12
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z13toz14
	      WHERE z(68247.3) BETWEEN 13 AND 14
	    ) AS landuse_z9toz14
	    WHERE geometry && ST_SetSRID('BOX3D(-2426493.46291292 15414520.4350735,-2421448.619046099 15419565.27894032)'::box3d, 3857)
	) AS data
```

But how can we make this better? 
Some geometry function that can clip/cut out a smaller part (aka the bounding box + buffer) from a big geometry and just return that? Like [ST_Intersection](http://postgis.net/docs/RT_ST_Intersection.html).

So if we try something like this (we need to add a buffer to ensure that the vector tile extent still works - so we just always take an entire tile as buffer - 256px).

```sql
ST_Intersection(geometry, ST_Buffer(!bbox!), !pixel_width! * 256)) AS geometry
```

The full query. It now just returns 9 bytes.
But whether that returns still useful data - have to test this with the postgis editor.

```sql
SELECT octet_length(ST_AsBinary("geometry")) AS geom,"osm_id","class","type" FROM (
	  SELECT osm_ids2mbid(osm_id, true) AS osm_id, 
	  ST_Intersection(geometry, ST_Buffer(ST_SetSRID('BOX3D(-2426493.46291292 15414520.4350735,-2421448.619046099 15419565.27894032)'::box3d, 3857), 200)) AS geometry,
	  landuse_class(type) AS class, type
	    FROM (
	    SELECT osm_id, geometry, type
	    FROM landuse_z5toz6
	    WHERE z(68247.3) BETWEEN 5 AND 6
	    UNION ALL
	    SELECT osm_id, geometry, type
	    FROM landuse_z7toz8
	    WHERE z(68247.3) BETWEEN 7 AND 8
	    UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z9
	      WHERE z(68247.3) = 9
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z10
	      WHERE z(68247.3) = 10
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z11
	      WHERE z(68247.3) = 11
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z12
	      WHERE z(68247.3) = 12
	      UNION ALL
	      SELECT osm_id, geometry, type
	      FROM landuse_z13toz14
	      WHERE z(68247.3) BETWEEN 13 AND 14
	    ) AS landuse_z9toz14
	    WHERE geometry && ST_SetSRID('BOX3D(-2426493.46291292 15414520.4350735,-2421448.619046099 15419565.27894032)'::box3d, 3857)
	) AS data
```

**Comment by lukasmartinelli** [comment]
> Some geometry function that can clip/cut out a smaller part (aka the bounding box + buffer) from a big geometry and just return that? Like ST_Intersection.

This might work. Consumes way less input data but sadly still times out (I guess because the queries are now much more expensive?).
Drawback is that PostGIS now is burning CPU (like 300% but that is the same CPU time Mapnik was wasting before). We now clip the data before we send it over the wire (aka the internal network interface).

**Comment by lukasmartinelli** [comment]
Glaciers are bad boys. Some of those geoms are 2.9MB big (times 5k tiles..).

```sql
select avg(octet_length(st_asbinary(geometry)))
from osm_landuse_polygon where st_area(geometry) > 10000000000
```

I am doing a controversial hack now https://github.com/osm2vectortiles/osm2vectortiles/commit/55151a06d1f6eecf6205280dde0f05549e7488a5 that impacts correctness. At z13 and z14 I just exclude gigantic glaciers and parks. This means that if you zoom into all the way down to z14 into the glaciers you suddenly will no longer see the glaciers. But at the moment this is the only thing that looks promising at solving this weird problem. This also impacts #42 

I am just rendering greenland now and this takes longer than the really data heavy Europe.

![cursor_and_tiles_a_la_google_maps__coordinates__tile_bounds_and_projection_-_conversion_to_epsg_900913__epsg_3785__and_epsg_4326__wgs84_](https://cloud.githubusercontent.com/assets/1288339/15092398/f1d86872-1468-11e6-8a5b-1c2b5bf9d3ac.png)

**Comment by ImreSamu** [comment]
one solution for big polygons .. 
*  https://github.com/mapzen/vector-datasource/blob/master/data/split_to_tiles.sql

**Comment by lukasmartinelli** [comment]
> one solution for big polygons ..

Might be more performant to slice it up before hand into large tiles (like a z11 grid) than doing `ST_Intersection` on the query directly (z13-z14).

I thought about slicing up the geometries, it is a good idea but I am a bit afraid of bugs like #300 occuring for landuse as well. Create a table like `osm_landuse_sliced_polygon` where we insert the landuse polygons with really large areas into (but then we also need to purge them from the source and generalized tables). 

BTW. also tried simplifying the large polygons but that doesn't really make them smaller.

**Comment by ImreSamu** [comment]
Good performance vs. The polygon outlines  ...  you have to choose one ! 

other method  ( adding ; just for a documenting purpose ) :
* ST_Subdivide()    http://blog.cartodb.com/subdivide-all-things/
 from the blog: _"Subdividing big things can make map drawing faster too, but beware: once your polygons are subdivided you’ll have turn off the polygon outlines to avoid showing the funny square boundaries in your rendered map."_
