### ISSUE TITLE
Is the "create your own vector tiles" process should be performable by a complete stranger?

### ISSUE THREAD

**Issue by burmisov** [osm2vectortiles/osm2vectortiles#316]
Thanks for a really great undertaking!
I'm having multiple different issues trying to perform the tile creation process. I've tried various versions in the last couple weeks, including release tags and the master branch recently, seen some changes to the instructions [on the site](http://osm2vectortiles.org/docs/own-vector-tiles/) and retried them. Switched to Zurich to be the dataset to eliminate possible data diff problems, but never really had luck to perform the whole process from beginning to the end.

I could file specific issues, but to save your time reading, could you please state:
1. Is it doable at all by a complete stranger? :)
2. What branch/tag should one currently use?
3. If one is to use docs from the website, then to which version does it correspond, if that even matters?
4. Maybe specify what type of hardware (server specs) one needs to do some useful stuff.

Thank you again, hoping to try my own vector tiles.

**Comment by manuelroth** [comment]
Hi Sergey, thanks for you feedback. 

> 1. Is it doable at all by a complete stranger? :)

Yes, we want that the process is doable by other people

> 2. What branch/tag should one currently use?

During the last weeks we made a lot of changes to the project, the master branch should be stable now.

> 3. If one is to use docs from the website, then to which version does it correspond, if that even matters?

The documentation will get an overhaul soon (#291), but the documentation about [creating your own vector tiles](http://osm2vectortiles.org/docs/own-vector-tiles/) is current.

> 4. Maybe specify what type of hardware (server specs) one needs to do some useful stuff.

Thats a good idea. We can give an approximation about how long the process takes for a give type of hardware for the entire planet. What do you mean by do some useful stuff (render the entire planet?)

Would you be up for a chat on skype?- Its probably the easiest way to troubleshoot the problems you experience. You can find me on skype with the following email address: manuelroth@hotmail.ch

**Comment by burmisov** [comment]
@manuelroth Many thanks for clarification!
Then maybe I'll try the process once again and come up with specific issues if they still arise.

Regarding the hardware thing - I guess maybe the entire planet is somewhat too large a task for an unexperienced stranger, but a city similar to Zurich would be a good place to start for hardware spec estimation.
