### ISSUE TITLE
Generated tiles have coordinates ouside extent

### ISSUE THREAD

**Issue by fitsoft** [osm2vectortiles/osm2vectortiles#318]
Hi, 
I generated tiles with osm2vectortiles project and then went back to decoding them with mapbox-vector-tile python package. I found something odd: there are negative coordinates and coordinates above the extent (4096). I am attaching an example tile and its corresponding decoded version 
(5728.txt).
[5728.gz](https://github.com/osm2vectortiles/osm2vectortiles/files/257393/5728.gz)
[5728.txt](https://github.com/osm2vectortiles/osm2vectortiles/files/257397/5728.txt)

Coordinates such as [-849, -2042], or [-2034, -1165] can be found in tile. 
The tile corresponds to zoom 14, x=8590 y=5728

I simply extracted the tile from the database, un-gzipped it and ran through the mapbox-vector-tile decode function.
I look forward to any clarification on this. Best regards,

Clara

**Comment by manuelroth** [comment]
Hi Clara,
this is a result of the buffer. A buffer on a layer allows you to include extra data around the outside of each tile. Depending on the data and desired styles this can be necessary to ensure seamless rendering across tile boundaries. A more detailed documentation can be found [here](https://www.mapbox.com/help/source-manual/#buffers).

**Comment by fitsoft** [comment]
Hi Manuel, thanks for the quick reply! By looking at the file osm2vectortiles/osm2vectortiles.tm2source/data.yml where the buffer settings seem to be, I don't see any buffer-size greater than 256 but in the tile I showed before there are coordinates in the -2000 range for example or above 5000, well above the 256 maximum. 
Maybe I should consider that the 256 may come from a lower zoom level and duplicate in size as I "zoom in"? 
Thanks,

Clara

**Comment by lukasmartinelli** [comment]
This is a bit counter intuitive. The buffer is measured in px relative to a
256px tile.

With a resolution of 4096 a buffer of 128px can stretch up to 2048 for
example.

**Comment by fitsoft** [comment]
Hello Lukas, 
Then in the esample you just gave I could have a coordinate take roughly values in the interval [-2048, 4096 + 2048] ?
Thanks,

Clara

**Comment by lukasmartinelli** [comment]
All great questions @fitsoft.

> Then in the esample you just gave I could have a coordinate take roughly values in the interval [-2048, 4096 + 2048] ?

Yes. Or with 256px even [-4096, 4096, 8192].

I don't know what the max number (if you can have more than 256px buffer) for the tile coordinate system is (4096 suggests 12 bits but you also need one bit for minus and one for 8192 so perhaps 14bit if 256px is the max buffer).
