### ISSUE TITLE
Tiles are not compatible with Mapbox Vector Tile v2 specification

### ISSUE THREAD

**Issue by hannesj** [osm2vectortiles/osm2vectortiles#326]
This breaks rendering when using mapbox-gl-native.

This is due to mojodna/tilelive-tmsource#9. After forking the repository and adding tilelive-bridge@2.3.1 and corresponding mapnik version as dependencies the tiles render correctly.

**Comment by lukasmartinelli** [comment]
> This breaks rendering when using mapbox-gl-native.

Oh oh this is a big one. So as of no the vector tiles we generate are not compatible with v2?!
I thought it is backwards compatible.

This is kind of a big one since would mean we need to rerender yet again which requires that @klokan would be willing to donate another infrastructure round.
At least it is now much faster thanks to #324.

But let' s not jump ahead. We will continue with what we have now so we can deliver.

> This is due to mojodna/tilelive-tmsource#9. After forking the repository and adding tilelive-bridge@2.3.1 and corresponding mapnik version as dependencies the tiles render correctly.

So we need to install it from https://github.com/hannesj/tilelive-tmsource?
Perhaps you can prepare a PR since you got it working 😁 🙇  ?

**Comment by hannesj** [comment]
They are mostly compatible, only some elements aren't rendered or look strange. This is due the more stringent validity requirements by v2. (changes are described [here](https://github.com/mapbox/vector-tile-spec/blob/master/CHANGELOG.md))

**Comment by lukasmartinelli** [comment]
> This is kind of a big one since would mean we need to rerender yet again which requires that @klokan would be willing to donate another infrastructure round.

Just discussed with @manuelroth. We don't want to render again before the bachelor thesis is finsihed (middle of June) since it is important that we don't have many more moving parts at this point in time.
Let's for sure keep this open.

**Comment by mojodna** [comment]
`tilelive-tmsource@0.5.0` now generates v2 vector tiles. Thanks @hannesj for the PR (and apologies for not merging it sooner).

**Comment by davidar** [comment]
This also causes some rendering artefacts with recent versions of mapbox-gl-js (mapbox/mapbox-gl-js#1606)

**Comment by klokan** [comment]
I am keen to make one more complete world rendering, with diff updates turned on - and fixed this as well as other reported issues.

Would it be doable in the first half of July at latest, @lukasmartinelli? Then we can manage the world USB sticks for FOSS4G.

**Comment by lukasmartinelli** [comment]
> I am keen to make one more complete world rendering, with diff updates turned on - and fixed this as well as other reported issues.
> 
> Would it be doable in the first half of July at latest, @lukasmartinelli? Then we can manage the world USB sticks for FOSS4G.

Happy you are willing to sponsor another run. I would love to do that. Thank you.
I want to try and first integrate those few schema changes that were proposed and then start asap.

Do we now that **NOW** we are compatible for sure? Or do we need to create test extract and test it again with native clients?

**Comment by klokan** [comment]
Great! Yes, it would be good to test properly before we start rerendering.

**Comment by manuelroth** [comment]
@lukasmartinelli this PR https://github.com/osm2vectortiles/osm2vectortiles/pull/366 needs to be merged first before we are able to create MVT v2 compatible vector tiles.

**Comment by hyperknot** [comment]
Just a small note, as I don't know what hardware the initial import is done on, but these might be great budget-friendly dedicated servers for the osm2vectortiles project, as you can rent them for one week and they have 64 GB RAM:
https://www.runabove.com/sandbox-servers.xml

Or these ones with SSDs:
https://www.runabove.com/i7-game-servers.xml

**Comment by stirringhalo** [comment]
@hyperknot I can't remember off-hand how many AWS VMs they are using, but I know they are all 8-core. I think it's 4 VMs.

The biggest issue is cores, and secondly storage. This is an embarrassingly parallel problem. You can scale this as large as you want to, but it is best to have a copy of the DB local to the workers (ie, on the same machine). The DBs need to be on SSD for good performance. RAM isn't a huge concern, I find 8GB is a decent sweet-spot for a few workers as Postgres is mostly using it for cache. The workers themselves use very little RAM.

So the most ideal setup would be many machines, lots and lots of cores, low RAM, and local SSD. You could do this easily with an adhoc cluster, but propagating the database to many machines could be a pain depending on your network and automation.

**Comment by lukasmartinelli** [comment]
> Just a small note, as I don't know what hardware the initial import is done on, but these might be great budget-friendly dedicated servers for the osm2vectortiles project, as you can rent them for one week and they have 64 GB RAM:
> https://www.runabove.com/sandbox-servers.xml
> 
> Or these ones with SSDs:
> https://www.runabove.com/i7-game-servers.xml

We are happy that @klokan is sponsoring the VMs needed for rendering OSM2VectorTiles.
However thanks for the tip, this sounds like a great offer to try my personal data projects.




> @hyperknot I can't remember off-hand how many AWS VMs they are using, but I know they are all 8-core. I think it's 4 VMs.
> 
> The biggest issue is cores, and secondly storage. This is an embarrassingly parallel problem. You can scale this as large as you want to, but it is best to have a copy of the DB local to the workers (ie, on the same machine). The DBs need to be on SSD for good performance. RAM isn't a huge concern, I find 8GB is a decent sweet-spot for a few workers as Postgres is mostly using it for cache. The workers themselves use very little RAM.
> 
> So the most ideal setup would be many machines, lots and lots of cores, low RAM, and local SSD. You could do this easily with an adhoc cluster, but propagating the database to many machines could be a pain depending on your network and automation.

All correct assumptions @stirringhalo. We are using 16core - 64 GB machines (but RAM could be lower - we just want the 16 cores). And distribute it by copying the DB (also correct assumption) to a local attached SSD (no network filesystem).

For updating we only need 1 machine - for rendering we used 4 to 8 machines (depends how fast we want it rendered). For the next run I will probably scale it up to even more since we are a bit in a hurry.

**Comment by klokan** [comment]
Rendering finished.
