### ISSUE TITLE
Docker Merge-jobs cannot find image

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#331]
Running docker-compose run merge-jobs tries to go out to docker.io and of course cannot find the image.

I have a successful run of exporting using RabbitMQ

I assume we are to run the local Dockerfile for merge-jobs after to amalgamate the results? Assuming RabbitMQ installed from a docker container (docker-compose up rabbitmq and docker-compose up export-workers ), could you clarify how to run in docker the merge-jobs tool?

How is that that you run it either with a local RabbitMQ or a docker rabbitmq?

**Comment by lukasmartinelli** [comment]
> I assume we are to run the local Dockerfile for merge-jobs after to amalgamate the results? Assuming RabbitMQ installed from a docker container (docker-compose up rabbitmq and docker-compose up export-workers ), could you clarify how to run in docker the merge-jobs tool?

Sorry we haven't published this Docker image yet. Published it now.
You can build all Docker images locally with running `make`.

https://hub.docker.com/r/osm2vectortiles/merge-jobs/

It should work with the local RabbitMQ.

**Comment by lukasmartinelli** [comment]
Image exists now.
