### ISSUE TITLE
Dependency issue for merge-jobs

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#332]
I see that the merge-jobs tool seems to have a dependency on Python3 due to "from urllib.request import urlretrieve"

Could this be clarified in the instructions? Or, could it be adapted to "from urllib import urlretrieve"?

**Comment by lukasmartinelli** [comment]
The script is used with the Docker image which uses Python:3.4.
https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/merge-jobs/Dockerfile

It is possible to make the urllib call work with Python2 and Python3. I guess this is the only thing that makes it incompatible.

**Comment by lukasmartinelli** [comment]
> The script is used with the Docker image which uses Python:3.4.
> https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/merge-jobs/Dockerfile
> 
> It is possible to make the urllib call work with Python2 and Python3. I guess this is the only thing that makes it incompatible.

It isn't worth it to spend time to make it compatible with Python 2 since it runs in a Docker container all the time anyway.

BTW @stirringhalo i put up the ansible script i use to setup the cluster https://github.com/osm2vectortiles/distributed-deployment

**Comment by stirringhalo** [comment]
Nice, I saw that. Something else to learn!
