### ISSUE TITLE
Cloud host for mbtiles has gone down

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#334]
As of 3:52 AM GMT it appears that the cloud host for the mbtiles is inaccessible

**Comment by lukasmartinelli** [comment]
Thanks for reporting. 1 hour ago I had the same error but now it seems to work again, this is sadly out of our control.

But from what I saw only the big planet files was down.. weird.

**Comment by manuelroth** [comment]
I think this is resolved now. Seams to work properly again. Will close this issue.
