### ISSUE TITLE
Procedure for rendering the planet

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#337]
Would now be a good time to semi-formally organize the documentation for the procedure for rendering the planet as well as the processing limitations?
What I've gathered thus far is:

1) You're using AWS/some sort of cloud services to generate the first planet.mbtiles
2) After that, you use "docker-compose up changed-tiles" to get a task list and only render those changed tiles
3) You do rolling updates to keep up with OSM pbf
4) Only if the base mapping changes do you redo the planet mbtiles

Have I hit the major points?

I'd be happy to help organize/document this if I get the important points in bullet form. I'll use PRs to integrate the documentation.

**Comment by lukasmartinelli** [comment]
> 1) You're using AWS/some sort of cloud services to generate the first planet.mbtiles
> 2) After that, you use "docker-compose up changed-tiles" to get a task list and only render those changed tiles
> 3) You do rolling updates to keep up with OSM pbf
> 4) Only if the base mapping changes do you redo the planet mbtiles

You got it on first try! That's exactly how it works.

> Would now be a good time to semi-formally organize the documentation for the procedure for rendering the planet as well as the processing limitations?

Totally. The repo is lacking them here. We do not have official documentation how this works so far.
Would be very happy to accept documentation PRs. 
We explain the concepts in the thesis a bit but not on the level where you can execute it. On a much higher level to pick out only the academic interesting parts.

Man thanks for your exploring and not giving up!!

![](https://media.giphy.com/media/queuu4OMRoj6M/giphy.gif)

**Comment by stirringhalo** [comment]
Hey, see the [wiki](https://github.com/osm2vectortiles/osm2vectortiles/wiki/Next-Steps). I highlighted a bunch of things in bold that are specific to AWS or things I haven't run/tested yet.

As I can see it now, I think you're missing the docker container on docker.io for diff updates (it's not documented) as well as for changed-tiles.

**Comment by lukasmartinelli** [comment]
We will try to work on all this issues you file. At the moment we are busy writing the thesis and try to not get distracted too much 😉  But after that we have more time for docs issues on the webpage itself.

> Hey, see the wiki. I highlighted a bunch of things in bold that are specific to AWS or things I haven't run/tested yet or aren't documented enough for me to jump off from. Hope it's a good start!

Excellent work there. We will extend it.
I think another thing that stands out is that generating the jobs is too complicated and could be integrated directly into the generate jobs script for example (so you don't have to know about pipecat).

> As I can see it now, I think you're missing the docker container on docker.io for diff updates (it's not documented) as well as for changed-tiles. Also, could you make a dockerfile available for import-osmupdate.sh as that would be the easiest way to keep a PBF updated?

The Docker import image is reused for all the things. To update the PBF I run `docker-compose run import-osm bash import-osmupdate.sh` after a successful diff import. You can run bash scripts inside a docker container.
We can add a separate docker compose entry so you can run `docker-compose run update-osm-pbf` or something like that.

> What are your thoughts on Docker swarm for orchestrating? I'm relatively new to Docker so I'm playing catchup.

I wanted to use it but to managing the hosts was simple enough to do with plain SSH automation as you only have to execute a few docker compose commands to get the worker started and working through

**Comment by stirringhalo** [comment]
> We will try to work on all this issues you file. At the moment we are busy writing the thesis and try to not get distracted too much :wink: But after that we have more time for docs issues on the webpage itself.

No worries, been there, done that. Good luck!

> Excellent work there. We will extend it.

Awesome :)

> I think another thing that stands out is that generating the jobs is too complicated and could be integrated directly into the generate jobs script for example (so you don't have to know about pipecat).

Makes sense.

> The Docker import image is reused for all the things. To update the PBF I run docker-compose run import-osm bash import-osmupdate.sh after a successful diff import. You can run bash scripts inside a docker container. We can add a separate docker compose entry so you can run docker-compose run update-osm-pbf or something like that.

Ah I had trouble getting the docker-compose run import-osm bash import-osmupdate.sh (or something similar). But I'm learning lots about this whole docker thing so something not working is probably me not understanding how it works.

> I wanted to use it but to managing the hosts was simple enough to do with plain SSH automation as you only have to execute a few docker compose commands to get the worker started and working through

Have you heard of the [GNU Parallel](http://www.gnu.org/software/parallel/) tool? It's a cheap and dirty way to automated SSH logins across the cluster. I've used it extensively to treat both local machines and networked machines as nodes on a cluster. With shared storage (S3/mock-s3/NFS), it's a handy way to login and execute some script and get the results back on the shared storage. Key-based logins can be a chore however to setup but it makes sense where you have many cloud instances and don't necessarily want the complexity of a full docker swarm or something else.

**Comment by lukasmartinelli** [comment]
Documentation about it is now captured in the  [usage guide](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/USAGE.md).

@stirringhalo What do you think  about close down the initial "next steps" wiki page https://github.com/osm2vectortiles/osm2vectortiles/wiki/Next-Steps since all of it is captured in the usage guide?

**Comment by stirringhalo** [comment]
Done
