### ISSUE TITLE
City request

### ISSUE THREAD

**Issue by cascafico** [osm2vectortiles/osm2vectortiles#341]
Hi,
I'd like to see Udine, Italy in cites list. Just admin_level=8

**Comment by lukasmartinelli** [comment]
Will be happy to do that.
Can you add the bounding box of Udine to the CSV file and make a PR?

https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/create-extracts/city_extracts.tsv 

You can use this tool to find out the bounding box.
http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=5.538062,47.236312,15.371071,54.954937&tab=1&proj=EPSG:4326&places=2

**Comment by klokan** [comment]
or this tool: http://boundingbox.klokantech.com/ - choose CSV as format.

**Comment by lukasmartinelli** [comment]
> I'd like to see Udine, Italy in cites list. Just admin_level=8

Udine works now @cascafico. Try it out :)
