### ISSUE TITLE
Timeouts (tilelive-copy?)

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#342]
I realized this may not be the place to ask about tilelive-copy but have you experienced issues with tilelive-copy timing out after 300s?

I did a run processing 0 0 0 at job-zoom=6, and I received a timeout after 300s about a third into the rendering. I have just changed the job-zoom=4 to see if I receive the same issue. But it might take awhile to get there.

I suspect it's one of those "complicated" tiles?

**Comment by stirringhalo** [comment]
Here's the traceback:

> export-worker_3         | Traceback (most recent call last):
> export-worker_3         |   File "export_remote.py", line 233, in <module>
> export-worker_3         |     main(args)
> export-worker_3         |   File "export_remote.py", line 227, in main
> export-worker_3         |     args['--bucket'],
> export-worker_3         |   File "export_remote.py", line 185, in export_remote
> export-worker_3         |     channel.start_consuming()
> export-worker_3         |   File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
> export-worker_3         |     self.connection.process_data_events(time_limit=None)
> export-worker_3         |   File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
> export-worker_3         |     self._dispatch_channel_events()
> export-worker_3         |   File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
> export-worker_3         |     impl_channel._get_cookie()._dispatch_events()
> export-worker_3         |   File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
> export-worker_3         |     evt.body)
> export-worker_3         |   File "export_remote.py", line 181, in callback
> export-worker_3         |     raise e
> export-worker_3         | subprocess32.TimeoutExpired: Command '['tilelive-copy', '--scheme', 'pyramid', '--minzoom', '6', '--maxzoom', '14', '--bounds=-180.0,83.9792594989,-174.375,84.5413610731', '--timeout=40000', 'tmsource:///tmp/project', u'mbtiles:///usr/src/app/6301c97fbd0bd8bd085787a79a7e602d08757e31.mbtiles']' timed out after 300 seconds
> osm2vectortiles20_export-worker_3 exited with code 1

**Comment by lukasmartinelli** [comment]
> I realized this may not be the place to ask about tilelive-copy but have you experienced issues with tilelive-copy timing out after 300s?

This can indeed happen (even though 300s is a very big timeout). #314 
This happens if in 10min zero progress in rendering tiles has been made.
Usually this has to do with copy operations taking too long due to the sheer volume of queries.
What also helps here is to run less workers sometimes.

Also PR #324  is not merged yet - this also helps.

> I suspect it's one of those "complicated" tiles?


But actually those are always very problematic areas that have a very specific reason that they timeout (polygons need to be split into smaller ones or other things).

Image of "complicated" tiles (some of them have been solved):

![](https://cloud.githubusercontent.com/assets/1288339/15303532/8f0bd376-1bb8-11e6-908e-51e69ca90387.png)

**Comment by stirringhalo** [comment]
Ahh, fair enough! I use smaller job-zooms (8 IIRC) and upped the maximum timeout. I wonder why the middle of the Indian ocean.. Might be that French island with a glacier.
