### ISSUE TITLE
Adjust center metadata for extracts + reupload

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#345]
While uploading the zurich_switzerland.mbtiles v2 into MapBox hosting for trying the online Studio editing, it complains about the "center not beeing within bounds".

It seems the lat/lon is switched now in the metadata:
```
center|47.379,8.5375,10
bounds|8.275,47.225,8.8,47.533
```

The downloadable extracts should be valid MBTiles accepted by MapBox.

**Comment by klokan** [comment]
v1 zurich.mbtiles has:
```
center|8.5367150000,47.3774550000,10
bounds|8.448060,47.320230,8.625370,47.434680
```

**Comment by lukasmartinelli** [comment]
Extracts uploading..works now with newest Udine upload.

![udine_italy___mapbox](https://cloud.githubusercontent.com/assets/1288339/16054027/a27e8718-326b-11e6-9f96-6768e106370a.png)

![empty___mapbox](https://cloud.githubusercontent.com/assets/1288339/16054136/278cf2dc-326c-11e6-9698-b5f08f5ec89b.png)
