### ISSUE TITLE
Missing require in tileserver-gl-light

### ISSUE THREAD

**Issue by sabas** [osm2vectortiles/osm2vectortiles#346]
On my Ubuntu 14.04 vps (node 0.10.25) gave
```
TypeError: Object function Object() { [native code] } has no method 'assign'
    at /usr/lib/node_modules/tileserver-gl-light/src/serve_data.js:28:14
```

As I saw on this issue https://github.com/facebook/fixed-data-table/issues/120

I did an ```npm install -g object-assign``` and added to serve_data.js ```Object.assign = require('object-assign')```

**Comment by lukasmartinelli** [comment]
Thanks a lot for this report!
Since you already solved how about making a pull request to https://github.com/osm2vectortiles/tileserver-gl-light?

We would love that!!

**Comment by sabas** [comment]
I'll try, I'm not so good in NodeJS :-)

**Comment by lukasmartinelli** [comment]
Great. Thanks for your contribution Stefano.
