### ISSUE TITLE
You rock!

### ISSUE THREAD

**Issue by mickael-kerjean** [osm2vectortiles/osm2vectortiles#348]
Hello,

Nothing more than a big thanks. This project is just great! Now everyone can get a lightweight map experience that actually feel good for the end user and without any proprietary layer.

Super exciting!

**Comment by manuelroth** [comment]
Thanks mickael, this is very motivating. It is great to see more and more people getting interesting in our project. It confirms the need for a free and open vector tile set.

**Comment by stephan75** [comment]
Finding better word than those from Mickael is hard,

I also tried to express my appreciation for all your work, see https://github.com/osm2vectortiles/osm2vectortiles/issues/327#issuecomment-221549370

So what do you think about an announcement in any form you like and want about release progress?

Or are things still to early?

**Comment by manuelroth** [comment]
> Finding better word than those from Mickael is hard,

> I also tried to express my appreciation for all your work, see #327 (comment)

> So what do you think about an announcement in any form you like and want about release progress?

> Or are things still to early?

Sorry for not replying to your comment stephan, we appreciate all the interest. We would love to announce the second version of the OSM2VectorTiles tile set in some way. I will write to the people at OSMBlog and WeeklyOSM, maybe they can mention us in their next post. Thanks for the hint.

**Comment by stirringhalo** [comment]
Totally agree with Mickael, this project has been awesome to follow and even better to setup and use with the great help you've all been providing!
