### ISSUE TITLE
North/South pole timeouts still occurring with split geometries

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#350]
I figured out that most of my tiling did actually complete, the timeouts are occurring just for the north and south pole. I have about 13700 of 16384 tiles completed. I had a look at all the messages in the failed-jobs queue and noted that they were about all for above/below +/-65 degrees  and all the way west and east.

The version of osm2vectortiles I used was a modified fork of your master and your split-polygons branch with manually applied landuse_split_polygon_table.sql.

I used "build: src/..." in my docker-compose.yml to ensure my changes were being built into the images. I had also used a bbox of "-180, -85,180,85" in docker-compose.yml.

I currently have one worker ticking through the jobs, and it's simply timing out at 1/s, 6hours to completion on zoom level 7 jobs.

I suspect it's some issue with the intersection grid at the poles as there are substantial distortions at the poles. I think the quote from http://postgis.net/docs/ST_Area.html:

> For geometry, a 2D Cartesian area is determined with units specified by the SRID. For geography, area is determined on a curved surface with units in square meters.

is key and suggests that the geometries must be interpreted as a geography so that ST_AREA will be correctly determined at the poles. Near the equator it's a reasonable assumption but not at high latitudes. From what I can tell, doing an st_area(geography(st_transform(geometry,4326))) in landuse_split_polygon_table.sql on line 37 will do the trick but I will test it for you.

Since the naiive ST_Area without considering the geography will exaggerate the area, it suggests that there may be an over segmentation of polygons near the poles, such that there are simply too many features to union in the view.

Edit: Similar changes will have to be made in landuse.sql and landuse_overlay.sql. Hopefully I will have it fully tested in the next 24 hours. It'll be interesting to see if performance suffers as these are just views with a fair bit of PostGIS manipulation. Materialized views or saving the area might be best moving forward.

Would it be better to simply count the nodes with st_npoints so you avoid the sluggish geometry transformations as that's what's actually import to the overly complex geometry issue? Or would you rather in keeping with what you already have, use the st_area(geography(st_transform...?

**Comment by lukasmartinelli** [comment]
Thanks for digging in!! Great stuff.

> The version of osm2vectortiles I used was a modified fork of your master and your split-polygons branch, ensuring indexes were created for the osm_landuse_split tables and osm_road tables. I had run into trouble getting the split to work properly, so I had manually apply landuse_split_polygon_table.sql, and ensured that landuse.sql and landuse_overlay.sql were correct. The only significant difference between your current master and my import is that I ran the split polygons operation after the layer creation in prepare.sh however that should be of little consequence as they are all views anyways.

Makes sense, I get it.

> I've inspected the landusages views and they are all defined as expected. I have 56891 rows in my osm_landuse_split_polygon table using a planet pbf from March 28th.

That's correct.

> I'm not sure how to export all the messages to csv as I do know I have to non-destructively consume them first.

Like this.

```
pipecat consume results --autoack --non-blocking > results_backup.json
cat results_backup.json | pipecat publish results
```

> I currently have one worker ticking through the jobs, and it's simply timing out at 1/s, 6hours to completion on zoom level 7 jobs. At the end of export-workers messages mentioning deprecation of minzoom and maxzoom, it sits there as the progress is effectively nil.

To deal with these problems later one approach is to ensure that workers are timing out fast (this is not configurable **yet** however - I modified the Python `export_remote` script to do that). This way you can at least render all the tiles that don't have any problems.

> I suspect it's some issue with the intersection grid at the poles as there are substantial distortions at the poles. I think the quote from http://postgis.net/docs/ST_Area.html:

Hmm, yes `ST_Area` is inaccurate at the poles, so no wonder there are many split polygons there. I only had problems with the south pole by the way, north pole worked.

> is key and suggests that the geometries must be interpreted as a geography so that ST_AREA will be correctly determined. From what I can tell, doing an st_area(geography(st_transform(geometry,4326))) in landuse_split_polygon_table.sql on line 37 will do the trick but I will test it for you.

So with this we can avoid slicing polygons that are not huge actually?

I guess it might be that we now have problems with rendering the poles since the polygon slicing is applied. Last time I rendered I applied the polygon slicing after the poles have been rendered for the most part.

If you can give me the tile index that is timing out I can hunt it down in the future.
The best way to test it as I found is to choose the local bbox where the problem is and then start figuring out which layer and then go to the cause. It is really nasty with these timeouts. 

The next thing I will work on regarding timeouts will be #330, I guess there the problem is with the large lake bodies (completly different what we experience here).

**Comment by stirringhalo** [comment]
> Thanks for digging in!! Great stuff.

No prob, this is when the GIS nerd kicks in. The ST_AREA with geography vs geometry was a nuance I hadn't known about as I typically dealt with very small areas near each other. 

> Like this.

Awesome, thanks!

> To deal with these problems later one approach is to ensure that workers are timing out fast (this is not configurable yet however - I modified the Python export_remote script to do that). This way you can at least render all the tiles that don't have any problems.

Yep, I added the shovel plugin to RabbitMQ so I could automatically move failed-jobs to the back of the jobs queue. That way I run through all of them, and even handle other errors that might've crept in. Works well.

> Hmm, yes ST_Area is inaccurate at the poles, so no wonder there are many split polygons there. I only had problems with the south pole by the way, north pole worked.

I saw a couple of northern latitudes. I suspect that was the big glacier feature over Greenland.

>> st_area(geography(st_transform(geometry,4326)))

> So with this we can avoid slicing polygons that are not huge actually?

Yes! I tested it on features that we a high latitudes (using the y-coord of the centroid to identify them). At high latitudes, it was sometimes a factor of 25 different in the reported area between st_area(geometry) and st_area(geography(st_transform(geometry,4326))), which is extreme but expected. So I think there was substantial over-segmenting. I suspect the UNION ALL with all those features is what's killing it.

Do you think there's any timeouts due to overly large line features? That's one of the other advantages of the st_npoints approach, it handles lines and points too. Choose a reasonable number of points to handle and split anything above it on the z9 grid you have.

As an aside, do you think using materialized views would make a difference and reduce some of the Postgres load? I haven't dug into the specific queries that are made against it but it might make a difference on the more complex layers such as landuse/overlay or roads.

If I get a chance tomorrow, I'll send you the bboxes and see if the redoing of the splitting with the fix worked. I suspect it will make a huge difference.

**Comment by stirringhalo** [comment]
Okay, got the changes to osm_landuse_split_polygons made. I've modified the views now to reflect the new way to calculate area, and I will do a run through with the st_area(geography(st_transform(geometry,4326))) approach.

Once I tried the new way, the number of rows in osm_landuse_split_polygon dropped from 56891 to 48870.

Still testing this, looks like export-workers is still timing out but I've might've missed something.

**Comment by stirringhalo** [comment]
Here's all my failed jobs, almost entirely +/- 60 latitude. There's a few around 40-43 latitude but I suspect those are the known issue tiles with the #330 . Also appears to be a failed tile in Mali
[died.txt](https://github.com/osm2vectortiles/osm2vectortiles/files/316316/died.txt)

**Comment by stirringhalo** [comment]
I can't seem to get the rendering going again, it's hung-up on export-worker still. I can see the queries going to PostGIS still

I suspect it's the now too complicated landuse.sql and landuse_overlay.sql layers. I tested the old view and new view approach and found queries were taking significantly longer (1s vs 15s or so).

I am testing using materialized views for landuse.sql and landuse_overlay.sql to see if I can take some load off PostGIS. It'll increase the diskspace and time to import slightly.

**Comment by stirringhalo** [comment]
I identified one issue, the range query in the landuse and landuse_overlay layers is very expensive. If you drop all rows with the area st_area(geography(st_transform(geometry,4326)))>1000000000 from osm_landuse_polygon, osm_landuse_gen0, osm_landuse_gen1 and index on the remainder, you save a factor of 10 from select queries on those views. From 40s down to 4s. I think there could be some enhancements made to the create view selects, but they are unnecessary when the 1000000000 limit exists

**Comment by lukasmartinelli** [comment]
Sorry for late answers. You're great man.

![](https://media0.giphy.com/media/l4KicZMLUTB2ldUvS/200.gif)

> Yes! I tested it on features that we a high latitudes (using the y-coord of the centroid to identify them). At high latitudes, it was sometimes a factor of 25 different in the reported area between st_area(geometry) and st_area(geography(st_transform(geometry,4326))), which is extreme but expected. So I think there was substantial over-segmenting. I suspect the UNION ALL with all those features is what's killing it.

`UNION ALL` should have no performance impact. `UNION` does.






> As an aside, do you think using materialized views would make a difference and reduce some of the Postgres load? I haven't dug into the specific queries that are made against it but it might make a difference on the more complex layers such as landuse/overlay or roads.

We use precalculated tables (same as materialized views) to precalculate the centroid for labels.
This is worth it if the same geometry is requested over and over again. If it is only request once (when the tile is rendered then precalculating doesn' thelp).

> Here's all my failed jobs, almost entirely +/- 60 latitude. There's a few around 40-43 latitude but I suspect those are the known issue tiles from #330 . There also appears to be a failed tile in Mali. I'm using an extended timeout (100000) IIRC so I probably have fewer timed-out jobs.
> died.txt

Thanks.

> I suspect it's the now too complicated landuse.sql and landuse_overlay.sql layers. I tested the old view and new view approach and found queries were taking significantly longer (<1s vs 30s or so).

Hmm the **polygon splitting no longer seems like the silver bullet it once seems**. At the moment it look like it makes everything even more complex. By introducing it we know have performance side effects.

Best way would be to use ST_Subdivide https://blog.cartodb.com/subdivide-all-things/ as @ImreSamu  mentioned. However only works with PostGIS 9.5 - and we can only do this if we ever do a rerender since we need to stick with a DB format if we only want to work with updates.

> I identified one issue, the range query in the landuse and landuse_overlay layers is very expensive. If you drop all rows with the area st_area(geography(st_transform(geometry,4326)))>1000000000 from osm_landuse_polygon, osm_landuse_gen0, osm_landuse_gen1 and index on the remainder, you save a factor of 10 from select queries on those views. From 40s down to 4s. I think there could be some enhancements made to the create view selects, but they are unnecessary when the 1000000000 limit exists.

Ahh ok. We can get the `area` already precalculated from imposm3...to speed it up.
I am open to a completly new approach for dealing with the large polygons (at the moment it feels hacky with this extra table that is only used for the large ones).

**Comment by stirringhalo** [comment]
Ha, no worries!

After all this, I'm not even sure if my rendering is still working properly.

> UNION ALL should have no performance impact. UNION does.

Came to the same conclusion, the difference was negligible. If there was many landuse polygons at the poles it may have been significant, guess not.

> We use precalculated tables (same as materialized views) to precalculate the centroid for labels.
This is worth it if the same geometry is requested over and over again. If it is only request once (when the tile is rendered then precalculating doesn' thelp).

Yep, realized the same. I added some indexes to landuse_class to try to narrow down the performance issue. No dice, definitely the only solution was the removal of the large features from the gen0,gen1, etc tables. Wanted to determine if there was an expensive calculation somewhere that was killing performance.

> Ahh ok. We can get the area already precalculated from imposm3...to speed it up.
I am open to a completly new approach for dealing with the large polygons (at the moment it feels hacky with this extra table that is only used for the large ones).

I wonder what imposm3 uses to calculate area and how well it works at the poles. Though at this point it's irrelevant.

> Best way would be to use ST_Subdivide https://blog.cartodb.com/subdivide-all-things/ as @ImreSamu mentioned. However only works with PostGIS 9.5 - and we can only do this if we ever do a rerender since we need to stick with a DB format if we only want to work with updates.

Seeing as we can fairly easily upgrade to Postgres9.5/Postgis2.2 with docker (I see the elegance now!) and changing it appears to be fairly trivial (my hack will simply make new tables, avoiding r, I will in the next day or two, depending on my free time, test it out on Greenland. I have enough mbtiles to test the later stages of import, so I can move on for now and come back to this later.

**Comment by stirringhalo** [comment]
Just as a follow up, I've been testing with ST_Subdivide with a custom docker image. So far the results are inconclusive, but I'm running another test to hopefully identify whether render performance has improved. I'm using the same AOI of -22.5,79.6871841545,-21.09375,79.9359182463 from #314 . My OSM pbf is solely of Greenland.

I've been testing by renaming osm_landuse_polygon, osm_landuse_polygon_gen1, osm_landuse_polygon_gen0 to a temporary name and then doing a "CREATE TABLE ___ AS SELECT id,timestamp,type,st_subdivide(geometry) as geometry from ___". I do notice with this operation that the number of features increases greatly, and the max(st_npoints(geometry)) is never higher than the limit in st_subdivide.

Without ST_Subdivide, it times out. With ST_Subdivide(geometry,128) on osm_landuse_polygon, osm_landuse_polygon_gen0 and osm_landuse_polygon_gen1, it usually completes with no timeout but still occasionally does with the default timeout settings. It is still slow as instead of one ginormous feature to open, there's many small ones. I didn't do any new indexing on the ST_Subdivided tables just yet (well I did in early tests but still wasn't conclusive) but I will in the next more formalized test. Though it may not matter much on the small tables.

I've noticed my generated .mbtile for that area (zoom 0-14) is blank however, with no contents. I'm not sure where that issue may be coming from but this is promising. I imagine doing the same operation on ne_*m_lakes may help too.

**Comment by stirringhalo** [comment]
[Subdivide.sql](https://github.com/osm2vectortiles/osm2vectortiles/files/320392/subdivide.txt) . Run this after import-osm and before import-sql. A VACUUM ANALYZE is probably needed at the end.

[Dockerfile for PostGIS 9.5 with GEOS3.5 version to provide ST_SUBDIVIDE](https://github.com/osm2vectortiles/osm2vectortiles/files/320393/Dockerfile.txt)

I think tuning can be done on how many points to subdivide too, might save some of the DB time, as well as size of indexes and tables. May influence the size of the MBtiles.

**Comment by lukasmartinelli** [comment]
> Subdivide.sql . Run this after import-osm and before import-sql. A VACUUM ANALYZE is probably needed at the end.
> 
> Dockerfile for PostGIS 9.5 with GEOS3.5 version to provide ST_SUBDIVIDE . Pgtune was disabled for now.
> 
> I think tuning can be done on how many points to subdivide to, might save some DB time, as well as size of indexes and tables. May influence the size of the MBtiles.

Great @stirringhalo. You are really digging into this.
Also thankful that you got the GEOS3.5 to work - I failed at that.
The good thing is that I can import my latest PBF (with the diffs applied) into the new PostGIS 9.5 container to try it out.

Do you want to create a Pull request/branch then I can try out those changes there?

Also I don't want to copy your code and paste it in my name since you did it.

**Comment by stirringhalo** [comment]
You know what, I suspect it might be a **bug in tilelive-copy**. Something is mis-calculating the jobs/progress in a region and truncating the .mbtiles.

Here's why:
1. I continued testing the st_subdivide branch and noticed no difference in timeouts. They were still occurring.
2. I decided to focus down on zoom level 14, so I set min_zoom and max_zoom to 14.
2. I decided to start digging into the other options for tilelive-copy like concurrency, parts, slow, etc. With slow, I could watch the progress and saw with the Greenland. I compared the following two bboxes:

-22.5,79.6871841545,-21.09375,79.9359182463 (Original Greenland tile, it timesout normally)
-25.5,79.6871841545,-24.09375,79.9359182463 (Slightly further inland, same dimensions so should be same number of tiles, doesn't seem to timeout normally and generated a complete mbtile)

With "slow" set to 10 in export-local.sh, I could track the actual tiles being processed. I noticed both bboxes seemed to progress and not hang-up. But, if you track the official progress messages, the coastline bbox stops at 103-139 tiles. After about 30s, it then jumps to 100% completion. The output mbtile is truncated to that last job.

If I ignore the progress reports however and look at the slow tiles as an indicator, I get a similar number of tiles "processed" as the inland region. **So the mbtiles are being truncated!** . I used scanline method to watch as it didn't seem to generate duplicate tiles in the slow output

Granted, both tests were with st_subdivide. Later I will generate a PR without st_subdivide with some basic diagnostics. Once we narrow down the issue further, then I'll submit an issue to tilelive-copy.

**Comment by lukasmartinelli** [comment]
> If I ignore the progress reports however and look at the slow tiles as an indicator, I get a similar number of tiles "processed" as the inland region in the same ballpark time. So the mbtiles are being truncated somehow . I will parse the output slow tiles better, removing duplicates, so I get a more accurate number.

Sorry that phenomenon is known. In greenland and also at the south pole  certain tiles there is **zero data**.
This means in **all layers there is not a single feature**. In this case tilelive-copy **does not store the tile**. That is why you see a "truncated" MBTiles.

<img width="766" alt="95c4f950-1bb7-11e6-8715-a44d11b5172c" src="https://cloud.githubusercontent.com/assets/1288339/16192409/6ddc77ae-36e9-11e6-8cc8-cd23ba2c17bc.png">

**Comment by stirringhalo** [comment]
*facepalm*

Makes perfect sense!

**Comment by lukasmartinelli** [comment]
> facepalm
> 
> Makes perfect sense!

Hey man I wasted so much time until I myself found this out.
I apologize you had to go through the same hoops.
