### ISSUE TITLE
error when docker-compose up import-osm

### ISSUE THREAD

**Issue by pertile** [osm2vectortiles/osm2vectortiles#353]
Hi, I'm trying to generate the mbtiles, I made all of the process but my tiles.mbtiles is a 0 KB file. So I started again. Please if you could give me any hint for solving this.

1) _docker-compose up -d postgis_ ends with
osm2vectortiles_postgis_1 is up-to-date
2) _docker-compose up import-external_ ends with
osm2vectortiles_import-osm_1 exited with code 1
3) _docker-compose up import-osm_ ends with 
WARNING: The AWS_S3_HOST variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
Starting osm2vectortiles_cache_1
Starting osm2vectortiles_pgdata_1
osm2vectortiles_postgis_1 is up-to-date
Starting osm2vectortiles_import-osm_1
Attaching to osm2vectortiles_import-osm_1
import-osm_1 | ERROR:  function drop_tables() does not exist
import-osm_1 | LINE 1: SELECT drop_tables()
import-osm_1 |                ^
import-osm_1 | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
import-osm_1 | DROP TABLE
import-osm_1 | CREATE TABLE
import-osm_1 | 2016/06/17 19:17:51 lowlevel.go:200: unmarshaling error (header): proto: osmpbf.BlobHeader: wiretype end group for non-group
osm2vectortiles_import-osm_1 exited with code 1

**Comment by stirringhalo** [comment]
Which osm.pbf are you using?

**Comment by pertile** [comment]
I downloaded a pbf around  my city

**Comment by stirringhalo** [comment]
> I downloaded a pbf around  my city

Where from? If you provide a link to it, we can potentially test it. Perhaps it's a bad pbf. Also, which operating system are you using (though it shouldn't matter)?

**Comment by pertile** [comment]
I will try with http://download.geofabrik.de/south-america/argentina-latest.osm.pbf. When import-osm end, is there a database I should see in my postgresql?

**Comment by stirringhalo** [comment]
Yes, depending on your OS you will need to modify the below:

1. docker ps -a  , you will see a pile of rows, where you should see something like 0.0.0.0:[NUMBER]->5432/TCP

Use that number to connect with psql like so: `psql -h localhost -p [NUMBER] -U osm -d osm` . If you type \dt+, you should see many tables with a size greater than a few thousand bytes.

Next time you run everything, run `docker-compose up postgis` without "-d". That way you can see the status messages for Postgres and identify any problems.
