### ISSUE TITLE
POI labels may be null ( v7 )

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#357]
interesting ...
According the [current v7 spec](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#changelog)

```text
POI labels: the name field of the poi_label layer may be null
 (in v6, nameless POIs were not included). 
Nameless POIs will have never have a maki value of marker (the generic default).
```

so probably we need to remove the filters 
https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-osm/mapping.yml#L840

**Comment by lukasmartinelli** [comment]
> POI labels: the name field of the poi_label layer may be null
>  (in v6, nameless POIs were not included). 
> Nameless POIs will have never have a maki value of marker (the generic default).

True.. size impact should be small since its only points (and names fields take usually space which are NULL now). Would also be included in the localrank algorithm (unnamed POIs are less important).

I can remove it in the test import I'm doing for #352
