### ISSUE TITLE
`#place_label ` Capital ( capital=yes not remapped to capital=2 )

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#358]
According to [Mapbox spec `#place_label`.Capitals)](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#place_label):   _`National capitals are 2, and 3 through 6 represent capitals of various sub-national administrative entities._

So I expect  "Budapest" capital=yes   re-mapped to capital=2   but now it is empty
 - http://taginfo.openstreetmap.ch/keys/capital#values   "Bern"
 - http://taginfo.openstreetmap.hu/keys/capital#values   "Budapest"
( probably the similar problem with other capitals  "Bern" / "Vaduz" )
 
The current imposm3 `integer` mappings drops the `capital=yes` values: 
```yml
 - key:  capital
   name: capital
   type: integer
```

Proposal: 

ver1: ( need full re-load )
- imposm3 - `capital` string mapping [ type: string ]
- re-mapping : ~   IF capital='yes' THEN capital='2' 
  - [data.yml](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/osm2vectortiles.tm2source/data.yml#L678) 

ver2: ( quick  fix )
- IF type=city capital=null and admin_level=2   THEN capital=2

But the ver2 is probably not perfect - my experimental test case: `Sucre` vs. `La Paz` ) 
- https://en.wikipedia.org/wiki/Sucre   is the constitutional/official capital of Bolivia, 
 - http://www.openstreetmap.org/node/313764484    
    - place=city  
    - admin_level=2  
    - capital=yes
- https://en.wikipedia.org/wiki/La_Paz  is the administrative capital of Bolivia  
 - http://www.openstreetmap.org/node/1975648720   
   - place=city  
    - admin_level=2  
    -  ( and no capital tag )  ->   so ver2  will generate a  false-positive  capital=2 from this data

ver2 test case found via overpass test: 
 - [ `type:node and place=city and admin_level=2 and capital!=yes`  ]

Summary:
- please re-test with this script
```sql
   SELECT capital, count(*) AS count 
   FROM osm_place_point
   GROUP BY capital
   ORDER BY capital;
```

- and my proposal :  go -> `ver1`

**Comment by lukasmartinelli** [comment]
Thanks for the detailed research. Ugly that we have to correct obsolete OSM mappings but ok.
We can do another schema import if we rerender for #326 so v1 is possible. 

> imposm3 - capital string mapping [ type: string ]
> re-mapping : ~ IF capital='yes' THEN capital='2'

What I don't like is that we then have to turn the string capital into a int for all other capital levels.
What about this mapping?:

```yaml
- name: capital
  type: int
  key: capital
- name: is_capital
  type: bool
  key: capital
```

And then do `CASE WHEN is_capital THEN 2 ELSE capital`

**Comment by ImreSamu** [comment]
> What about this mapping?

perfect.  ( but later we can create a special imposm3 mapping - for this case ) 


We can also use the  ["admin_centre" information] (http://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members)  to add missing `capital` infos.    For example: http://www.openstreetmap.org/node/35295150 ( name=Lausanne,  place=city )
is  part of:
 - Relation Vaud [r1702421](http://www.openstreetmap.org/relation/1702421) (as admin_centre)
  - admin_level=4  and boundary=administrative
 - Relation Ancien district de Lausanne [r6205453](http://www.openstreetmap.org/relation/6205453) (as admin_centre)
  - admin_level=6 and boundary=historic
 - Relation Lausanne [r1685018](http://www.openstreetmap.org/relation/1685018) (as admin_centre)
  - admin_level=8  and  boundary=administrative

currently no `capital` osm key for "Lausanne", 
but we can assign "capital"="4"   (  from the  parent `Relation Vaud` : `admin_level=4 )
