### ISSUE TITLE
Is there a tag mapping table?

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#363]
I remember there was a mapping table showing which layers are included in Osm2vectortiles. I can't find it anymore. Does it still exist somewhere?

**Comment by muesliq** [comment]
That's where I looked (in Mapbox Studio) but I couldn't find landuse=residential, which should be available as of #307.

**Comment by muesliq** [comment]
Ok, I understood now how this works. A little difficult to find out, the zoom levels for each layer.

**Comment by lukasmartinelli** [comment]
> That's where I looked (in Mapbox Studio) but I couldn't find landuse=residential, which should be available as of #307.

It should be in the `landuse` layer.

> Ok, I understood now how this works. A little difficult to find out, the zoom levels for each layer.

Yes. A one size fits all diagram :/
