### ISSUE TITLE
3rd Planet Rendering

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#368]
Doing a 3rd rendering due to #326.

Planet timestamp: **2016-06-20 14:58:14**
Import time: 13h imposm + 4h precalculation + 0.5h import-sql

**Comment by ImreSamu** [comment]
I have started analyze the new version:
- created a new test method  https://github.com/osm2vectortiles/osm2vectortiles/pull/370
- selected `switzerland-160601` data from Geofabrik 
- and generated 2 versions  (old: 443c7a5   vs. new: 2904e5a )
- compared the output with simple `textfile compare` tools.

What I found 
-  different numbers of  `(count( distinct osm_id ))`  / views    --->   need more research:
 - 443c7a5-22a1861e2b0e30364306763178356fd4-switzerland-160601--R001.txt  `uniq_id` col
 - 2904e5a-22a1861e2b0e30364306763178356fd4-switzerland-160601--R001.txt  `uniq_id` col
- example `landuse_z9`      
  - old  443c7a5   `uniq_id=`    7831       `(count( distinct osm_id ))`
  - new 2904e5a  `uniq_id=`    8230       `(count( distinct osm_id ))`

NOW :
- I am checking my test code ...
- and thinking what is changed ...

**Comment by lukasmartinelli** [comment]
> I have started analyze the new version:

Great

> different numbers of (count( distinct osm_id )) / views ---> need more research:

We have a lot more unnamed POIs  now #357.

> example landuse_z9

This makes sense due to the subdividing.

**Comment by ImreSamu** [comment]
@lukasmartinelli 
not easy to debug ...
but I have found a strange thing:

Landuse problem  :
* osm_id: [-8818325](http://www.openstreetmap.org/way/8818325) 
  *  in the `landuse_z5toz6`
 *   missing from  the `landuse_z7toz8` 
  *  in the `landuse_z9`
  *  in the `landuse_z10` 
  *  ...


```sql
  osm_id  |            t             |     st_area()    |  area  
----------+--------------------------+------------------+--------
 -8818325 | osm_landuse_polygon      | 502549.741585023 | 502550
 -8818325 | osm_landuse_polygon_gen1 | 492359.970306903 | 502550
 -8818325 | osm_landuse_polygon_gen0 | 550089.108481817 | 502550
 -8818325 | landuse_z5toz6           | 550089.108481817 |       
 -8818325 | landuse_z9               | 550089.108481817 |       
 -8818325 | landuse_z10              | 550089.108481817 |       
 -8818325 | landuse_z11              | 492359.970306903 |       
 -8818325 | landuse_z12              | 502549.741585023 |       
 -8818325 | landuse_z13toz14         | 502549.741585023 | 
```

current code  ; probably an area filter is missing from the `landuse_z5toz6`
```sql
CREATE OR REPLACE VIEW landuse_z5toz6 AS
    SELECT id AS osm_id, geometry, type
    FROM osm_landuse_polygon_subdivided_gen0
    WHERE landuse_class(type) = 'wood';

CREATE OR REPLACE VIEW landuse_z7toz8 AS
    SELECT id AS osm_id, geometry, type
    FROM osm_landuse_polygon_subdivided_gen0
    WHERE landuse_class(type) IN ('wood', 'residential')
      AND area > 1000000;
```

proposed code ..    and don't know the correct number ...  so please replace the 20101001 value ...  

```sql
CREATE OR REPLACE VIEW landuse_z5toz6 AS
    SELECT id AS osm_id, geometry, type
    FROM osm_landuse_polygon_subdivided_gen0
    WHERE landuse_class(type) = 'wood'
        AND area > 20101001;    --- ??? just a big random number ,  please replace ...  

CREATE OR REPLACE VIEW landuse_z7toz8 AS
    SELECT id AS osm_id, geometry, type
    FROM osm_landuse_polygon_subdivided_gen0
    WHERE landuse_class(type) IN ('wood', 'residential')
      AND area > 1000000;
```

**Comment by lukasmartinelli** [comment]
Good it is in z5 so it doesn't affect the worker rendering.

**Comment by ImreSamu** [comment]
### V2 vs. V3   landuse_z9   

Sometimes, 
* the `ST_Area( ST_SimplifyPreserveTopology(..))` is less than the original area -and this made a lot of differences ..   in the FILTERS ... 

[Example](http://www.openstreetmap.org/way/24456875)

OLD   (  not in the  `osm_landuse_polygon_gen1` ,  `landuse_z9` , `landuse_z10`  )
*  IF  `( (ST_Area( ST_SimplifyPreserveTopology(. ,50 )))   ) `   >  500000         ??
*  IF   499821.313229277   >  500000      **====>  FALSE**

```sql
  osm_id   |            t             |     st_area      
-----------+--------------------------+------------------
 -24456875 | osm_landuse_polygon      |  518755.58416851
 -24456875 | osm_landuse_polygon_gen1 | 499821.313229277
 -24456875 | landuse_z11              | 499821.313229277
 -24456875 | landuse_z12              |  518755.58416851
 -24456875 | landuse_z13toz14         |  518755.58416851
(5 rows)
```

NEW   and the correct !
*  IF   `area`    >  500000     ??
*  IF 518756    >  500000   **====> TRUE**

```sql
  osm_id   |            t             |  area  |     st_area      
-----------+--------------------------+--------+------------------
 -24456875 | osm_landuse_polygon      | 518756 |  518755.58416851
 -24456875 | osm_landuse_polygon_gen1 | 518756 | 499821.313229277
 -24456875 | osm_landuse_polygon_gen0 | 518756 | 373871.896598971
 -24456875 | landuse_z9               |        | 373871.896598971
 -24456875 | landuse_z10              |        | 373871.896598971
 -24456875 | landuse_z11              |        | 499821.313229277
 -24456875 | landuse_z12              |        |  518755.58416851
 -24456875 | landuse_z13toz14         |        |  518755.58416851
(8 rows)
```

Summary: 
*  Differences exists , 
 * but, the new data is better  and consistent.

**Comment by ImreSamu** [comment]
probably the most of the differences caused by the  `ST_Area( ST_SimplifyPreserveTopology(..))`
and sometimes it is added more layers  ( `new_more`  ), and  sometimes the opposite ( `new_less`  ) ..  

```sql
         new_more         |         new_less         | count |    avg_oldsumarea    |   avg_newsumarea    
--------------------------+--------------------------+-------+----------------------+---------------------
 {landuse_z10}            |                          |     2 |  494673.185000000000 | 506308.425000000000
 {landuse_z10,landuse_z9} |                          |    77 |  503636.569480519481 | 499136.174805194805
 {landuse_z11}            |                          |  1286 |   54571.799813374806 |  51437.336967340591
 {landuse_z7toz8}         |                          |   156 | 1006398.427179487179 | 992488.533333333333
 {landuse_z9}             |                          |   349 |  532264.967191977077 | 515288.751977077364
                          | {landuse_z10}            |    38 |  489284.804736842105 | 496802.466578947368
                          | {landuse_z10,landuse_z9} |    28 |  552432.312500000000 | 492980.784642857143
                          | {landuse_z7toz8}         |   105 |  991525.200666666667 | 975871.633238095238
(8 rows)
```

And the average area ( 'avg_oldsumarea', 'avg_newsumarea' )  is similar than in the filters ..
*   50000 ,  99000,  500000 ,  1000000
```              '
*  'landuse_z7toz8'    ,  'osm_landuse_polygon_subdivided_gen0;   area > 1000000   '
*  'landuse_z9'        ,  'osm_landuse_polygon_subdivided_gen0;   area > 500000    '
*  'landuse_z10'       ,  'osm_landuse_polygon_subdivided_gen0;   area > 99000     '
*  'landuse_z11'       ,  'osm_landuse_polygon_subdivided_gen1;   area > 50000     '
*  'landuse_z12'       ,  'osm_landuse_polygon_subdivided     ;   area > 10000     '
*  'landuse_z13toz14'  ,  'osm_landuse_polygon_subdivided     ;   
```

**Comment by klokan** [comment]
Rendering finished.

**Comment by lukasmartinelli** [comment]
> proposed code .. and don't know the correct number ... so please replace the 20101001 value ...

Addressed that in https://github.com/osm2vectortiles/osm2vectortiles/commit/9090f93a838e52f358daf4c9e5b9ce48f2a7dbc1

>  Differences exists , but, the new data is better and consistent.

Thanks for the grunt work to find that out!!

**Comment by davidar** [comment]
Is this rendering available to download yet? http://osm2vectortiles.org/downloads/ still seems to link to the old MVTv1 tiles.
