### ISSUE TITLE
tileserver-gl-light: missing streets-v9.json

### ISSUE THREAD

**Issue by clintharris** [osm2vectortiles/osm2vectortiles#371]
(Reporting here since issues are disabled for https://github.com/osm2vectortiles/tileserver-gl-light)

Seeing this with v1.0.3:
```
tileserver-gl-light lilongwe_malawi.mbtiles
...
Error: Cannot find module '...../node_modules/tileserver-gl-light/styles/streets-v9.json'
```
This file doesn't exist in https://github.com/mapbox/mapbox-gl-styles either.

**Comment by clintharris** [comment]
Update: `streets-v9.json` can be found here: https://github.com/mapbox/mapbox-gl-styles/tree/v9/styles

**Comment by clintharris** [comment]
Ah, I see now that these files were removed due to copyright issues as part of [this commit](https://github.com/osm2vectortiles/mapbox-gl-styles/commit/36d9c6c14943d2ae8c8d484cb6f8b2be373be786).

Not sure if the preferred resolution is to modify the code to no longer reference those styles or to add documentation with info about about the need to independently retrieve those styles...

**Comment by klokan** [comment]
See: https://github.com/osm2vectortiles/mapbox-gl-styles/issues/3

@michaelsteffen is a lawyer from MapBox. You can discuss with him about the legal usage of the removed styles.

**Comment by manuelroth** [comment]
@clintharris Thanks for the report, I am working on a fix for the bug. Also enabled the issues section on the tileserver-gl-light repository.

**Comment by lukasmartinelli** [comment]
> @clintharris Thanks for the report, I am working on a fix for the bug. Also enabled the issues section on the tileserver-gl-light repository.

Fixed it @manuelroth. https://github.com/osm2vectortiles/tileserver-gl-light/commit/28112f01dc4e126340c49414d34f90a9bccde2bf

**Comment by manuelroth** [comment]
@lukasmartinelli nice, thank you.

**Comment by clintharris** [comment]
@lukasmartinelli Thanks for the quick fix!
