### ISSUE TITLE
Using nginx & tileserver-gl-light

### ISSUE THREAD

**Issue by karussell** [osm2vectortiles/osm2vectortiles#374]
Thanks for this nice project - I enjoyed the talk at FOSSGIS :) !

Is it possible to use nginx in front of tileserver-gl-light to e.g. use https config from nginx? When I tried to configure nginx** then the bright.json contained localhost references making it failing to load the rest. Would you mind to share some insights? Maybe there is an option when starting the server to influence the served host?

**
```   
 location /tiles-test {
         proxy_pass      http://localhost:8080;
         proxy_redirect  off;
 }
```

**Comment by karussell** [comment]
Now I got a bit further via downloading the bright.json and directly specifying the https URL there (three changes necessary) and furthermore changing the nginx config to:

```
        location /public/tiles-test {
                proxy_pass      http://localhost:8080;
                index index.html;
                proxy_redirect  off;
                rewrite ^/public/tiles-test(.*) $1 break;
        }
```

Still it says 'Blocked loading mixed active content "http://localhost:8080/data/osm2vectortiles/0/0/0.pbf"'. Where can I change this URL?

**Comment by manuelroth** [comment]
Great, that you enjoyed our talk at FOSSGIS. [tileserver-gl-light](https://github.com/osm2vectortiles/tileserver-gl-light) is not meant for production use cases, therefore there is and will be no option to configure the port. We only built it to get people started quickly. 

If you intend to create a production ready vector map, please consider building your own tileserver. The mbtiles files available on the [downloads section](http://osm2vectortiles.org/downloads/) are basically only a sqlite database (with columns x,y,z, tile), this means you can build a server which reads of this sqlite database. [Tobin Bradley](https://github.com/tobinbradley) has created a great example based on NodeJS. Check it out [here](https://github.com/tobinbradley/mbtiles-server/blob/master/server.js#L36). 

We are not interested in helping people to build there own tileserver, as the intention of this project is to create vector tiles based on OpenStreetMap.

**Comment by klokan** [comment]
@klokantech can support commercial support for installation of tileservers.

tileserver-gl-light is a port of tileserver-gl: https://github.com/klokantech/tileserver-gl.
The light variant does not serve raster tiles. @klokantech team is now working on bringing the functions from the "light" fork back to the master branch of the project (details to be discussed with @manuelroth and @lukasmartinelli soon).

We use the tileserver-gl behind NGINX - with HTTPS in production in several of our projects. For example: http://boundingbox.klokantech.com/, http://epsg.io/map#srs=4326&x=8.679199&y=47.085085&z=7&layer=streets, soon we are going to port the OldMapsOnline style and use it also on http://www.oldmapsonline.org/ with over 125k visitors a month and in all our larger projects.

The TileServer-GL project is going to be presented and formally announced at FOSS4G.
Follow: https://github.com/klokantech/tileserver-gl and our twitter @klokantech
