### ISSUE TITLE
Database files are incompatible with server

### ISSUE THREAD

**Issue by pertile** [osm2vectortiles/osm2vectortiles#376]
Hi, as I had problems trying to generate my tiles I decided to remove and purge my postgresql and postgis. Now I can't get **docker-compose up postgis** works. This is the message I get:
federico@federico-Aspire-E5-571:/etc/osm2vectortiles$ sudo docker-compose up postgis
WARNING: The AWS_S3_HOST variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
Starting osm2vectortiles_pgdata_1
Starting osm2vectortiles_postgis_1
Attaching to osm2vectortiles_postgis_1
postgis_1 | FATAL:  database files are incompatible with server
postgis_1 | DETAIL:  The data directory was initialized by PostgreSQL version 9.4, which is not compatible with this version 9.5.3.
osm2vectortiles_postgis_1 exited with code 1

Could you give me a hint about how to solve this?

**Comment by manuelroth** [comment]
We have recently [moved from Postgres 9.4 to 9.5](https://github.com/osm2vectortiles/osm2vectortiles/commit/ed0d2d27b5027267388e7edba982b6e7214889c5). I suppose that you need to delete the `pgdata` container as well. As the error message notes that the database was initialized by PostgreSQL 9.4.

**Comment by pertile** [comment]
Output is exactly the same after I run
_sudo docker-compose pgdata_

**Comment by lukasmartinelli** [comment]
If everything else fails.

```
docker-compose stop
docker-compose rm -v
docker-compose pull
# this ensures you have latest - even though you should already get them with pull
make
# continue import process from scratch
```
