### ISSUE TITLE
Broken renderings under Chrome

### ISSUE THREAD

**Issue by ratrun** [osm2vectortiles/osm2vectortiles#386]
Map rendering under actual Chrome versions currently show artefacts because the outdated v0.18.0/mapbox-gl.js is used. 
See the following screenshot from http://osm2vectortiles.org/maps/ 
![brokenchromerendering](https://cloud.githubusercontent.com/assets/6134544/17153594/b0e8139a-537d-11e6-8c2c-f7d8025ff0ac.PNG)

The problem can be solved by using v0.21.0/mapbox-gl.js .

**Comment by lukasmartinelli** [comment]
Fixed in https://github.com/osm2vectortiles/osm2vectortiles/commit/511add4a74278c52bf1f8e135743af998803c40e.

Thanks for the suggestion @ratrun.
