### ISSUE TITLE
Vector tile source "mapbox" layer "admin" does not use vector tile spec v2

### ISSUE THREAD

**Issue by iamvdo** [osm2vectortiles/osm2vectortiles#388]
Playing with the "Get Started" tutorial from website, then update to mapbox-gl-js 0.21, I get this error:

`Vector tile source "mapbox" layer "admin" does not use vector tile spec v2 and therefore may have some rendering errors.`

I'm using the "planet_z0-z8.mbtiles" file

Maybe related to #326 ?

**Comment by efi** [comment]
For me it's the same with the newest mapbox-gl-js version and `germany.mbtiles`. 

And it does not just report the "admin" layer, the browser console says:
```
Vector tile source "mapbox" layer "landuse" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "water" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "road" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "admin" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "place_label" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "country_label" does not use vector tile spec v2 and therefore may have some rendering errors.
Vector tile source "mapbox" layer "waterway" does not use vector tile spec v2 and therefore may have some rendering errors.
```
sporadically as I zoom and pan (in the area covered by the dataset).

But so far no strange rendering bugs occured.

**Comment by lukasmartinelli** [comment]
Thanks @efi and @iamvdo 

Ok I found the reason.  The master node in the cluster didn't have the latest Docker image and therefore rendered the layers from z0 to z8 in v1 spec and all the jobs it got assigned.

I wrote a script that iterated through all z8 tiles and checks whether it is v1 or v2 spec (if it is v1 spec this means the entire subpyramid is v1 and that it has been rendered by the bad node).
I will now reschedule those jobs to rerender with the latest export image.

By replacing z0 to z8 with v2 spec most people will never see this warning but there are still 111 tiles that are in v1 spec if we don't take action.

Will inform you guys back in this issue when the planet is available again.
The v1 111 tiles is the only thing missing now.

**Comment by klokan** [comment]
Thank you a lot @lukasmartinelli for the report! Great progress with the @klokantech rendering cluster.

Looking forward to having all tiles in the planet in V2 spec...

**Comment by lukasmartinelli** [comment]
The new planet `3d4cb571d3d0d828d230aac185281e97` with replaced v1 spec pyramids is uploaded. We can also put this on the CDN.

More details about what was done to replace the v1 tiles can be found in #380.

**Comment by lukasmartinelli** [comment]
> The new planet 3d4cb571d3d0d828d230aac185281e97 with replaced v1 spec pyramids is uploaded. We can also put this on the CDN.

Is the CDN already updated @klokan ?
