### ISSUE TITLE
Water bodies with tag landuse=reservoir

### ISSUE THREAD

**Issue by efi** [osm2vectortiles/osm2vectortiles#390]
In OSM data, this is a a somewhat-but-not-really deprecated way to describe (among others) lakes that are used for controlled water storage: http://wiki.openstreetmap.org/wiki/Tag:landuse=reservoir

The VectorTiles should reflect this tag usage and (maybe unless `covered=yes` is present) treat this similar to a normal lake.

Example:
http://www.openstreetmap.org/way/7997604
= http://maps.stamen.com/watercolor/#17/51.29759/12.40117
= https://tangrams.github.io/carousel/?refill#17/51.29759/12.40117

**Comment by lukasmartinelli** [comment]
Implemented - for the next release. Actually the `landuse=reservoir` should also be tagged `natural=water` then it would already be rendered. So it is a tagging mistake we need to handle (that happens pretty often).

> The VectorTiles should reflect this tag usage and (maybe unless covered=yes is present) treat this similar to a normal lake.

I exclude covered reservoirs.
