### ISSUE TITLE
High zoom level tile source

### ISSUE THREAD

**Issue by briancalvium** [osm2vectortiles/osm2vectortiles#395]
I've successfully ran through the docker process to generate a (very) small region on my local machine, but even using the GISgraphy sources, I've only been able to get zoom levels up to 14. Is there a source for higher zoom levels? we ultimately want to have small (3-4 sq. km) regions available offline on mobile devices at very high detail.

JIC, I started with the GB.pbf file from GISGraphy, ran through the docker process, and exported using: 
`docker-compose run   -e BBOX="-2.670708,51.43943,-2.62466,51.454649" -e MIN_ZOOM="12" -e MAX_ZOOM="18" export`

and ended up with levels 12-14. Is there somewhere in the osm2Vector process that limits it to 14, or is that source data only to 14?

It looks like the example map on the main website has pretty high detail. Does that use zoom levels higher than 14?

**Comment by klokan** [comment]
Vector tiles are typically overzoomed - so by default the OSM2VectorTiles project vector tile schema have maxzoom 14 - but you can display and draw the maps, streets, houses, etc. down to zoomlevel 22. No need to render vector tiles deeper.

If you want to change the schema / style for the vector tiles check https://github.com/osm2vectortiles/osm2vectortiles/tree/master/osm2vectortiles.tm2source

**Comment by briancalvium** [comment]
Thanks for the quick reply! I'm using the mapbox SDK on iOS/Android, and it seems like overzoom isn't fully supported. The tiles that are already loaded look great over-zoomed, but it doesn't load new tiles when panning once over-zoomed (it looks for, and cannot find, tiles at zoom 15+ for instance). It's a little hard to tell what exactly is in the data from GISgraphy - if I wanted to try changing the schema, would I essentially modify data.yml and add SELECT clauses for the higher zoom levels to all of those UNION ALLS?

**Comment by klokan** [comment]
Try "OSM2VectorTiles" on iOS or Android (search AppStore / Play). It demos the zoom 14 vector tiles (online and offline) over zoomed without limits.

**Comment by briancalvium** [comment]
Looks good! But, is that using MapTiler behind the scenes, or is there just some style.json flag I don't know about? (maybe this now is a mapbox question... but as you guys seem to have it going... )
