### ISSUE TITLE
Mismatched dates on download page

### ISSUE THREAD

**Issue by roblight** [osm2vectortiles/osm2vectortiles#396]
The [download page](http://osm2vectortiles.org/downloads/) states:

> Full Planet and extracts were last updated on **7/20/2016**

However the download link points to a **6/20/2016** file:

> https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/planet_2016-06-20_3d4cb571d3d0d828d230aac185281e97_z0-z14.mbtiles

**Comment by lukasmartinelli** [comment]
Thanks @roblight . Okay that's a parsing fail. I actually try to parse the date from the file now.
Sometihng is wrong in the JS that replaces the date.

```javascript
var planetUrl = planetDownload.value;
        var segments = planetUrl.split('_').reverse();
        var hash = segments[1];
        var date = segments[2];

        var dateSegments = date.split('-');
        var planetRenderDate = new Date(dateSegments[0], dateSegments[1], dateSegments[2]);

        document.querySelector("#md5sum").innerHTML = hash;
        document.querySelector("#timestamp").innerHTML = planetRenderDate.toLocaleDateString();
```

**Comment by roblight** [comment]
@lukasmartinelli your welcome!  Thank you for the prompt response.

**Comment by roblight** [comment]
Does this mean the latest planet file is 6/20/2016?  I seem to recall the last planet download I did had a date around 7/14/2016.  Thanks again!

**Comment by lukasmartinelli** [comment]
> Does this mean the latest planet file is 6/20/2016? I seem to recall the last planet download I did had a date around 7/14/2016. Thanks again!

It displayed  7/14/2016 because it was reuploaded at that day (with MVT v2 support) - now we display the actual render date (well as reported it still has a big) which is 6/20/2016.

Will soon render the updates for  the last 2 months. We were busy fixing MVT 2 problems so far.

**Comment by roblight** [comment]
Cool, thanks for the info.  Does the date in the filename correspond to the OSM source data as found on planet.openstreetmap.org?

**Comment by lukasmartinelli** [comment]
> Cool, thanks for the info. Does the date in the filename correspond to the OSM source data as found on planet.openstreetmap.org?

Yes it is directly the date that is found in the PBF of the imported planet file (or the last diff that was applied).

**Comment by lukasmartinelli** [comment]
Fixed. The month in a Javascript Date object is zero based 👊 😆 

<img width="483" alt="downloads_ _osm2vectortiles" src="https://cloud.githubusercontent.com/assets/1288339/17526421/7f2135b8-5e67-11e6-9a2c-d5ebf1c1d0b3.png">
