### ISSUE TITLE
osm2vectortiles_import-osm_1 exited with code 1

### ISSUE THREAD

**Issue by e11137** [osm2vectortiles/osm2vectortiles#406]
Hi, I'm trying to generate the france tiles but unfortunatly the script import osm exit with an error.

docker-compose up -d postgis -> OK
docker-compose up import-external -> OK
docker-compose up import-osm -> KO
docker-compose run  -e BBOX="-5.1636,47.4374,-0.9723,48.8882"  -e MIN_ZOOM="8"  -e MAX_ZOOM="14" export -> KO
the process finsih but without landuse and lancovers
Is it normal or I forgot a step during the process?

[Aug 19 16:38:47] [INFO] [PostGIS] Analysing osm_road_geometry took: 802.781541ms
import-osm_1            | [Aug 19 16:38:47] [INFO] [PostGIS] Clustering on geometry took: 14m51.005871639s
import-osm_1            | [Aug 19 16:38:47] [INFO] Imposm took: 47m16.846064331s
import-osm_1            | Create osm_water_point table with precalculated centroids
import-osm_1            | DROP TABLE IF EXISTS osm_water_point CASCADE;
import-osm_1            | DROP TABLE
import-osm_1            | CREATE TABLE osm_water_point AS
import-osm_1            | SELECT id,
import-osm_1            |        topoint(geometry) AS geometry,
import-osm_1            |        timestamp,
import-osm_1            |        name, name_fr, name_en, name_de,
import-osm_1            |        name_es, name_ru, name_zh,
import-osm_1            |        area
import-osm_1            | FROM osm_water_polygon;
import-osm_1            | psql:water_point_table.sql:1: NOTICE:  table "osm_water_point" does not exist, skipping
import-osm_1            | SELECT 0
import-osm_1            | CREATE INDEX ON osm_water_point USING gist (geometry);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_water_point
import-osm_1            | USING btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326)));
import-osm_1            | CREATE INDEX
import-osm_1            | Update osm_place_polygon with point geometry
import-osm_1            | UPDATE osm_place_point
import-osm_1            | SET geometry = topoint(geometry)
import-osm_1            | WHERE ST_GeometryType(geometry) <> 'ST_Point';
import-osm_1            | UPDATE 0
import-osm_1            | UPDATE osm_poi_polygon
import-osm_1            | SET geometry = topoint(geometry)
import-osm_1            | WHERE ST_GeometryType(geometry) <> 'ST_Point';
import-osm_1            | UPDATE 0
import-osm_1            | UPDATE osm_housenumber_polygon
import-osm_1            | SET geometry = topoint(geometry)
import-osm_1            | WHERE ST_GeometryType(geometry) <> 'ST_Point';
import-osm_1            | UPDATE 0
import-osm_1            | Subdividing polygons in osm
import-osm_1            | /\* OSM Landuse Polygons */
import-osm_1            | DROP TABLE IF EXISTS osm_landuse_polygon_subdivided_gen0 CASCADE;
import-osm_1            | psql:subdivide_polygons.sql:3: NOTICE:  table "osm_landuse_polygon_subdivided_gen0" does not exist, skipping
import-osm_1            | DROP TABLE
import-osm_1            | DROP TABLE IF EXISTS osm_landuse_polygon_subdivided_gen1 CASCADE;
import-osm_1            | DROP TABLE
import-osm_1            | DROP TABLE IF EXISTS osm_landuse_polygon_subdivided CASCADE;
import-osm_1            | psql:subdivide_polygons.sql:4: NOTICE:  table "osm_landuse_polygon_subdivided_gen1" does not exist, skipping
import-osm_1            | DROP TABLE
import-osm_1            | psql:subdivide_polygons.sql:5: NOTICE:  table "osm_landuse_polygon_subdivided" does not exist, skipping
import-osm_1            | CREATE TABLE osm_landuse_polygon_subdivided_gen0 AS SELECT id,timestamp,type,area,st_subdivide(geometry,1024) AS geometry FROM osm_landuse_polygon_gen0;
import-osm_1            | SELECT 0
import-osm_1            | CREATE TABLE osm_landuse_polygon_subdivided_gen1 AS SELECT id,timestamp,type,area,st_subdivide(geometry,1024) AS geometry FROM osm_landuse_polygon_gen1;
import-osm_1            | SELECT 0
import-osm_1            | CREATE TABLE osm_landuse_polygon_subdivided AS SELECT id,timestamp,type,area,st_subdivide(geometry,1024) AS geometry FROM osm_landuse_polygon;
import-osm_1            | SELECT 0
import-osm_1            | SELECT UpdateGeometrySRID('osm_landuse_polygon_subdivided_gen0','geometry',3857);
import-osm_1            |                             updategeometrysrid  
import-osm_1            | --------------------------------------------------------------------------
import-osm_1            |  public.osm_landuse_polygon_subdivided_gen0.geometry SRID changed to 3857
import-osm_1            | (1 row)
import-osm_1            | 
import-osm_1            | SELECT UpdateGeometrySRID('osm_landuse_polygon_subdivided_gen1','geometry',3857);
import-osm_1            |                             updategeometrysrid  
import-osm_1            | --------------------------------------------------------------------------
import-osm_1            |  public.osm_landuse_polygon_subdivided_gen1.geometry SRID changed to 3857
import-osm_1            | (1 row)
import-osm_1            | 
import-osm_1            | SELECT UpdateGeometrySRID('osm_landuse_polygon_subdivided','geometry',3857);
import-osm_1            |                          updategeometrysrid  
import-osm_1            | ---------------------------------------------------------------------
import-osm_1            |  public.osm_landuse_polygon_subdivided.geometry SRID changed to 3857
import-osm_1            | (1 row)
import-osm_1            | 
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen0 USING btree(id);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen1 USING btree(id);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided USING btree(id);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen0 USING btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326)));
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen1 USING btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326)));
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided USING btree (st_geohash(st_transform(st_setsrid(box2d(geometry)::geometry, 3857), 4326)));
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen0 USING gist (geometry);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided_gen1 USING gist (geometry);
import-osm_1            | CREATE INDEX
import-osm_1            | CREATE INDEX ON osm_landuse_polygon_subdivided USING gist (geometry);
import-osm_1            | CREATE INDEX
import-osm_1            | ANALYZE osm_landuse_polygon_subdivided_gen0;
import-osm_1            | ANALYZE
import-osm_1            | ANALYZE osm_landuse_polygon_subdivided_gen1;
import-osm_1            | ANALYZE
import-osm_1            | ANALYZE osm_landuse_polygon_subdivided;
import-osm_1            | ANALYZE
import-osm_1            | Update scaleranks from Natural Earth data
import-osm_1            | UPDATE osm_place_point
import-osm_1            | SET scalerank = improved_places.scalerank
import-osm_1            | FROM
import-osm_1            | (
import-osm_1            |     SELECT osm.id, ne.scalerank
import-osm_1            |     FROM ne_10m_populated_places AS ne, osm_place_point AS osm
import-osm_1            |     WHERE
import-osm_1            |     (
import-osm_1            |         ne.name ILIKE osm.name OR
import-osm_1            |         ne.name ILIKE osm.name_en OR
import-osm_1            |         ne.namealt ILIKE osm.name OR
import-osm_1            |         ne.namealt ILIKE osm.name_en OR
import-osm_1            |         ne.meganame ILIKE osm.name OR
import-osm_1            |         ne.meganame ILIKE osm.name_en OR
import-osm_1            |         ne.gn_ascii ILIKE osm.name OR
import-osm_1            |         ne.gn_ascii ILIKE osm.name_en OR
import-osm_1            |         ne.nameascii ILIKE osm.name OR
import-osm_1            |         ne.nameascii ILIKE osm.name_en
import-osm_1            |     )
import-osm_1            |     AND (osm.type = 'city' OR osm.type = 'town' OR osm.type = 'village')
import-osm_1            |     AND st_dwithin(ne.geom, osm.geometry, 50000)
import-osm_1            |     ) AS improved_places
import-osm_1            | WHERE osm_place_point.id = improved_places.id;
import-osm_1            | UPDATE 0
import-osm_1            | ERROR:  invalid input syntax for type timestamp: "(invalid timestamp)"
import-osm_1            | LINE 1: DELETE FROM osm_timestamps WHERE timestamp='(invalid timesta...
import-osm_1            |                                                    ^
osm2vectortiles_import-osm_1 exited with code 1

**Comment by ImreSamu** [comment]
Hi @e11137 ,

>   ERROR: invalid input syntax for type timestamp: "(invalid timestamp)"

Your problem maybe related to https://github.com/osm2vectortiles/osm2vectortiles/issues/397

Are you unsing  http://download.geofabrik.de/europe/france.html extract ?

Can you post the output of the : 
*  ` osmium fileinfo  france.osm.pbf   ` 
*   `osmconvert france.osm.pbf   --out-timestamp `  

//   replace  `france.osm.pbf`  with your input osm pbf file ;

**Comment by xtompok** [comment]
Exactly the same problem, using osmosis cutted rectangle from geofabrik file. Outputs of osmconvert:

$ osmconvert praha.osm.pbf --out-statistics
timestamp min: 2005-11-14T23:54:09Z
timestamp max: 2016-09-22T19:23:05Z
lon min: 12.0905901
lon max: 18.8592160
lat min: 48.5518135
lat max: 51.0557036
nodes: 6462067
ways: 467282
relations: 27347
node id min: 172508
node id max: 4413814325
way id min: 4947
way id max: 443820391
relation id min: 2162
relation id max: 6597388
keyval pairs max: 279
keyval pairs max object: node 424313803
noderefs max: 1838
noderefs max object: way 149801414
relrefs max: 2895
relrefs max object: relation 2793464
$ osmconvert praha.osm.pbf --out-timestamp
(invalid timestamp)

Original file
$ osmconvert czech-republic-latest.osm.pbf --out-timestamp
2016-09-22T19:28:03Z

The script should check this in the beginning not fail at the end of the processing
