### ISSUE TITLE
can not find any pbf when import-osm

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#410]
I had put the "planet-latest.osm.pbf " file in ./import floder in the source floder but when I excute "docker-compose run import-osm"  it tunrs out  "can not find any osm pbf .  please monut  /data/import to floder contains pbf"

**Comment by ImreSamu** [comment]
Hi!

The example tutorial - with `zurich_switzerland.osm.pbf`  is working ?
* see:  http://osm2vectortiles.org/docs/own-vector-tiles/

**Comment by stirringhalo** [comment]
It should be "docker-compose up import-osm"!

**Comment by bearnxx** [comment]
it did not work neither :( @ImreSamu

**Comment by bearnxx** [comment]
it turns out the same result. any other ways?

**Comment by stirringhalo** [comment]
Odd, how is your import directory structured (is there only one osm2vectortiles folder you are using) and is your docker-compose.yml file unmodified?

**Comment by bearnxx** [comment]
I have only on osm2vectortiles folder. (/home/bear/osm2vectortiles)   and I have put the pbf file in /home/bear/osm2vectortiles/import.  I didn't modifiedmy docker-compose.yml . how should it go? @stirringhalo

**Comment by ImreSamu** [comment]
@bearnxx 
Can you post the output of the following commands?
- `cat /etc/*-release`
- `cat /proc/version`
- `docker version`
- `docker-compose version`
- `docker run debian:jessie /bin/echo 'Hello world'`

my quess
*   maybe this is a Docker problems ..  see similar errors: 
  * https://github.com/docker/docker/search?utf8=%E2%9C%93&q=%22Error+resolving+syscall+name%22+&type=Issues

If you don't using the latest `docker`  and `docker-compose` - can you upgrade and [check again](http://osm2vectortiles.org/docs/own-vector-tiles/)?
* https://github.com/docker/docker/releases  ( v1.12.1 )
* https://github.com/docker/compose/releases  ( 1.8.0 )

**Comment by bearnxx** [comment]
[root@localhost osm2vectortiles]# cat /etc/*-release
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 
=============================================

[root@localhost osm2vectortiles]# cat /proc/version
Linux version 3.10.0-229.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Fri Mar 6 11:36:42 UTC 2015
===============================================

[root@localhost osm2vectortiles]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64
===========================================

[root@localhost osm2vectortiles]# docker info
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 6
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:3-137629586-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.961 GB
 Data Space Total: 107.4 GB
 Data Space Available: 13.76 GB
 Metadata Space Used: 9.404 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 7.627 GiB
Name: localhost
ID: Y3AP:WBOT:JNR6:DUIF:JHIF:G4Z6:UENO:U6PB:HNDB:TRGW:TBST:UGOC
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
=====================================================

[root@localhost osm2vectortiles]# docker-compose version
docker-compose version 1.8.0, build 94f7016
docker-py version: 1.9.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
==================================================

@stirringhalo   @ImreSamu

**Comment by ImreSamu** [comment]
@bearnxx 
> I think it should be some config problem not a lower version docker problem

* maybe this is a [ seccomp ]  security problem ? 
 * https://github.com/docker/docker/blob/master/docs/security/seccomp.md
 * docker v12 has a centos seccomp patch:  https://github.com/docker/docker/pull/22344  ( but i am not a centos user ..  so this is only a guess .. )


you can test your docker configurations .  
*  if the simple  docker  volume ( '-v   Bind mount a volume')   is not  working , then the osm2vectortiles also not working ...



the `vt.sh`  should list your ./import directory   ( and the pbf file ! )
```
cat vt.sh
#!/bin/bash
vimport=$(pwd)/import 
docker run -it --rm -v $vimport:/data/import debian:jessie ls -la /data/import
```

**Comment by bearnxx** [comment]
[root@localhost osm2vectortiles]# docker run -it --rm -v $vimport:/data/import debian:jessie ls -la /data/import
Unable to find image 'debian:jessie' locally
Trying to pull repository docker.io/library/debian ... 
jessie: Pulling from docker.io/library/debian
357ea8c3d80b: Already exists 
Digest: sha256:ffb60fdbc401b2a692eef8d04616fca15905dce259d1499d96521970ed0bec36
Status: Downloaded newer image for docker.io/debian:jessie
2016/08/30 13:29:22 Error resolving syscall name execveat: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name getrandom: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name memfd_create: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name renameat2: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name sched_getattr: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name sched_setattr: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name seccomp: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name cacheflush: could not resolve name to syscall - ignoring syscall.
2016/08/30 13:29:22 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
ls: cannot open directory /data/import: Permission denied

I have disabled the selinux. it did'tn work too.
I think it must be the ContOS7 Problem.  I decide to change to your  Linux distributions. So which one are you using now? 

@ImreSamu

**Comment by hyperknot** [comment]
I think the #1 os for Docker host is Ubuntu LTS, that is 16.04 today.

**Comment by ImreSamu** [comment]
@bearnxx :
> I think it must be the ContOS7 Problem.

sometimes a simple Docker reinstall ( or upgrade )  helps  ( but sometimes not )
https://docs.docker.com/engine/installation/linux/centos/

>So which one are you using now?

I am using `Ubuntu 16.04`  
and
* docker version : 1.12.1
* docker-compose version: 1.8.0

**Comment by bearnxx** [comment]
I change my OS to Ubuntu16.04 . All is well~~~  :) @ImreSamu  @stirringhalo   thank you for your help

**Comment by stirringhalo** [comment]
Yep, to confirm I used 16.04 and it works perfectly!

**Comment by jaskiratr** [comment]
I'm using docker on Windows machine and I get same error.
Reference: #499 

Should I consider switching to Ubuntu instead?
