### ISSUE TITLE
Trying to create tiles to zoom 20 (User error)

### ISSUE THREAD

**Issue by mtfurlan** [osm2vectortiles/osm2vectortiles#417]
What I want is to render Michigan(ish, tile 8,11,5 according to [the tool linked in the generate jobs readme](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/)) from zoom 15 to 20, as I can download up to zoom 14, so I'm trying to follow the instructions in `USAGE.md`.

I've been having some issues with the documentation so far, and I'll make a pull request later with suggested edits once I have something that actually works.

What I want right now is to confirm that I finally know what I'm doing before I waste even more time processing vector tiles I don't need.

What I expected to work:
```
docker-compose run \
  -e TILE_X=8 -e TILE_Y=11 -e TILE_Z=5 \
  -e JOB_ZOOM=14 -e MAX_ZOOM=20 \
  generate-jobs
```
It didn't work. (It looks like it just would have generated jobs for level 14?)
 `generate_world_jobs.sh` doesn't take MAX_ZOOM as an argument. `generate_jobs.py` however, does, which is what I had read and made bad assumptions on.

So what I need to do is modify `generate_world_jobs.sh` to pass MAX_ZOOM, 

```
...
+ readonly MAX_ZOOM=${MAX_ZOOM:-"14"}
...
- python generate_jobs.py pyramid "$TILE_X" "$TILE_Y" "$TILE_Z" --job-zoom="$JOB_ZOOM" > $jobs_file
+ python generate_jobs.py pyramid "$TILE_X" "$TILE_Y" "$TILE_Z" --job-zoom="$JOB_ZOOM" --max-zoom="$MAX_ZOOM" > $jobs_file
...
```
and run
```
docker-compose run \
  -e TILE_X=8 -e TILE_Y=11 -e TILE_Z=5 \
  -e JOB_ZOOM=15 -e MAX_ZOOM=20 \
  -e WORLD_JOB="false"
  generate-jobs
```
Should this work?

Also in my last try, the rabbitmq docker container restarted on it's own, once I got to the merge step. I was able to just loop through all the mbtiles in the AWS bucket, but any idea why the rabbitmq docker container restarted instead of just crashing, or better yet not crashing?

**Comment by lukasmartinelli** [comment]
May I ask why you want to render vector tiles until z20? Are you including a lot of extra data at high zoom levels?


Are you running it on multiple machines or on a single one?

If you are running it on a single machine I suggest you use the local export.

```
docker-compose run \
   # bounding box of michigan
  -e BBOX="19.6875,40.97989806962015,20.390625,41.50857729743933" \
  -e MIN_ZOOM="14" \
  -e MAX_ZOOM="20" \
  export
```

If you are running on multiple machines we will further investigate.
Your approach is correct, the Docker container does not pass on max zoom it seems so adding it is good.

So you want to create jobs at zoom level 14 that will render down from z14 to z20 for all z15 descendants from your z5 tile `8/11/5`.

```
python generate_jobs.py pyramid 8 11 5 --job-zoom=14 --max-zoom=20
```

This returns will return you `4^(15-5)= 1048576` jobs where each job renders `4^(20-14)=4096` tiles.

So you want to render 4 billion z15 tiles?

You get jobs like these. From a quick checks that seems correct.

```json
{"id": "322a315fa30c4a5925a422e6ef80e719d24e0bea", "pyramid": {"tile": {"max_zoom": 20, "y": 11286, "min_zoom": 15, "x": 8296}, "bounds": {"west": -88.857421875, "north": 48.763431137917955, "south": 48.756188762805515, "east": -88.846435546875}}, "type": "pyramid"}
```


> Also in my last try, the rabbitmq docker container restarted on it's own, once I got to the merge step. I was able to just loop through all the mbtiles in the AWS bucket, but any idea why the rabbitmq docker container restarted instead of just crashing, or better yet not crashing?

Never had a RabbitMQ crash so far. We were running it for several weeks.

**Comment by ImreSamu** [comment]
@mtfurlan :   for the ZOOM > 14 topic ..

Probably you have  to modify the  [osm2vectortiles.tm2source/data.yml] (
https://github.com/osm2vectortiles/osm2vectortiles/blob/master/osm2vectortiles.tm2source/data.yml)  meta file ... because the current implementation  max zoom level = 14  ;

so you have to modify  and adapt every SQL WHERE filters ( near `z(!scale_denominator!)` ); 


 for example
```
   WHERE z(!scale_denominator!) BETWEEN 13 AND 14
```
to

```
   WHERE z(!scale_denominator!) >= 13
```

**Comment by mtfurlan** [comment]
@lukasmartinelli  I'm sorry, I just had a fundamentally wrong approach to my problem. I don't need the extra data, I just needed higher zoom and I was using the mapbox gl style wrong, so it was just requesting higher zoom tiles, so I thought "Well, better figure out how to make higher zoom tiles"

That was a lot of time I didn't need to spend.

I'll try to make a pull request for USAGE.md this evening.

Thanks for the quick response to my wrong approach.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli I'm sorry, I just had a fundamentally wrong approach to my problem. I don't need the extra data, I just needed higher zoom and I was using the mapbox gl style wrong, so it was just requesting higher zoom tiles, so I thought "Well, better figure out how to make higher zoom tiles"
> 
> That was a lot of time I didn't need to spend.
> 
> I'll try to make a pull request for USAGE.md this evening.
> 
> Thanks for the quick response to my wrong approach.

Coming from raster tiles this is completely understandable. The overzooming is like magic with vector tiles the first time you see it. We should perhaps educate people better in our repo and on the website.
