### ISSUE TITLE
Ignore Water Tiles: Optimize MBTiles in post-processing

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#42]
For the size of MBTiles it is crucial that we do not include vector tiles for empty ocean tiles.

Does Mapbox serve the Ocean tiles?
Check out how MaskLevel tiles works?
If tiles below a empty tile are requested, Mapnik renders from the mask level.

**Comment by sfkeller** [comment]
For the sake of minimizing resources (i.e. disk space and processing time) I just wanted to ask a similar question regarding tiles of a larger region provided either as boolean "mask" or even a mask with more than one value. This becomes virulent with vectors but could be applied also to raster tiles:
How are empty/missing tiles handled (at either server or client side) so that they are rendered with a dataset wide single value (like ocean blue) - or even rendered using an arbitrary value (like ocean/rain forest/ice) fetched from some "meta tile/layer")?

**Comment by klokan** [comment]
Check: "maskLevel tiles" at https://github.com/mapbox/tilelive-vector
It seems it is enough to set on the source a maskLevel attribute and tilelive-vector will ignore any empty tiles bellow that zoom level (and such tiles does not need to be present inside of the MBTiles).

**Comment by lukasmartinelli** [comment]
I want to exclude the water tiles at the job level. The `enqueue-jobs` component will ask the PostGIS database whether the tile bounding box touches any land polygons: If it does, the job is not even "scheduled". And the `maskLevel` tile implementation of tilelive-vector will then do the rest.

![openstreetmap](https://cloud.githubusercontent.com/assets/1288339/10757243/eb46a66a-7ca9-11e5-9206-b717c89daccc.png)

**Comment by klokan** [comment]
If done this way, then it must run on non-generalised land polygons and we must really trust these land polygons...

- Does such decision happens only on the top tile of a job - so it enforces our `maskLevel` to the top level of parallel job metapyramids +1?
- It also brings dependency on postgresql to enqueue-job :-(.

I wonder if it would not be better to run this test inside of the `export` job? There we have postgresql anyway, we could make the test on a zoom level defined in advance (docker's sysenv MASKLEVEL +1?) or the minzoom of the job, whatever is max, and set the job independently of the top level zoom of the job metapyramid. It would also allow non-paralelised rendering on a single docker instance to ignore the water tiles bellow maskLevel... Isn't it more elegant?

I wonder if there is a point and title "Atlantic ocean", we will ignore it. Question is if this is an issue visually for zooms deeper then maskLevel. Probably not. We could check on MapBox tiles how they do that...

Other approach would be to decide based on the bytesize / md5 or number of layers of a produced vector tile - so if an empty vector is detected, cancel all rendering bellow this particular tile in the renderer `export` process. But this approach is dangerous because it is very style dependant. I like to land polygon overlap more.

BTW It seems the vector MBTiles produced by tilelive supports the internal symlinks. If you look inside with sqlite3 the tiles table is just a view for images - where the real .pbf blobs are stored.
This is normally used to store an empty PNG tile blob just once and use the same tile_id on multiple XYZ positions. This needs to be handled in the merge phase - and will be probably used for upper zoom levels (up from maskLevel) automatically by tilelive?
```sql
$ sqlite3 zurich.mbtiles
sqlite> .tables
geocoder_data  grid_key       grids          keymap         metadata
grid_data      grid_utfgrid   images         map            tiles
sqlite> .schema tiles
CREATE VIEW tiles AS
    SELECT
        map.zoom_level AS zoom_level,
        map.tile_column AS tile_column,
        map.tile_row AS tile_row,
        images.tile_data AS tile_data
    FROM map
    JOIN images ON images.tile_id = map.tile_id;
sqlite> .schema map
CREATE TABLE map (
   zoom_level INTEGER,
   tile_column INTEGER,
   tile_row INTEGER,
   tile_id TEXT,
   grid_id TEXT
);
sqlite> .schema images
CREATE TABLE images (
    tile_data blob,
    tile_id text
);
```

**Comment by lukasmartinelli** [comment]
> BTW It seems the vector MBTiles produced by tilelive supports the internal symlinks. If you look inside with sqlite3 the tiles table is just a view for images - where the real .pbf blobs are stored.
> This is normally used to store an empty PNG tile blob just once and use the same tile_id on multiple XYZ positions. This needs to be handled in the merge phase - and will be probably used for upper zoom levels (up from maskLevel) automatically by tilelive?

I saw the same. For empty MBTiles there is just one blob record in the `image` table and all records in the `map` table reference it.

**Comment by lukasmartinelli** [comment]
> If done this way, then it must run on non-generalised land polygons and we must really trust these land polygons...

We just found another problem. Admin zones that lap over land polygons could perhaps be affected if I query the land polygons only. But the land polygons we are using now are not generalized.

> Other approach would be to decide based on the bytesize / md5 or number of layers of a produced vector tile - so if an empty vector is detected, cancel all rendering bellow this particular tile in the renderer export process. But this approach is dangerous because it is very style dependant. I like to land polygon overlap more.

Yes I thought about this as well. We already have the vectortiles of the world down to z10 and I could check there and see whether a tile is empty or not and then decide to not schedule it.

**Comment by klokan** [comment]
I still strongly believe the decisions should be done inside of `export` docker, not in the `enqueue-jobs` as you suggested...

**Comment by klokan** [comment]
BTW Both mapbox-streets v5 and v6 has `maskLevel: 8` defined in TileJSON (see: https://github.com/geometalab/osm2vectortiles/issues/25#issuecomment-151569602)
We should target the same one...

**Comment by lukasmartinelli** [comment]
> I wonder if it would not be better to run this test inside of the export job? There we have postgresql anyway, we could make the test on a zoom level defined in advance (docker's sysenv MASKLEVEL +1?) or the minzoom of the job, whatever is max, and set the job independently of the top level zoom of the job metapyramid. It would also allow non-paralelised rendering on a single docker instance to ignore the water tiles bellow maskLevel... Isn't it more elegant?

Thought about it. I'll move the logic into the `export` component.

In message based workflows I usually like to control the flow from a single point not from the workers themselves but in this case your proposed approach has indeed more pros than cons.

Pros:
- `enqueue-jobs` component can stay stateless 
- Scalability is easier to achieve because queries are distributed (making that many queries for the job zoom level will take some time)
- Works for a single docker instance as well.
- `export` container knows more about the tile he needs to render than the `enqueue-jobs` component because he also knows the style etc.

Cons:
- It makes the rendering process more complex. Now it is just "Render that BBOX".
- No single control point

I really have to test whether the land polygon overlap works. I am no longer sure it will be that simple but hope so. In the end I want the fastest solution to implement to save the most work in rendering while still serving the correct tiles.

Perhaps not every job needs to produce a MBTiles file. A MBTiles with a single z8 tile containing nothing is the same as not merging it at all.

**Comment by klokan** [comment]
MapBox hosting serves the water tiles for deep water zoom - these contains the 'water' layer with 'osm-id' at z14:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/14/8146/11773.vector.pbf?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ
but the tile is exactly the same (binary identical) as when deep zoomed-in to z20:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/20/521375/753503.vector.pbf?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ

surprisingly the tile at maskLevel=8 so z8:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/8/127/183.vector.pbf?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ
differs from z14 above or from z9 in the binary form:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/9/254/366.vector.pbf?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ

Would be interesting to see the dumps of these tiles (how they differ) - another practical use-case for #12, if we would have it...

**Comment by lukasmartinelli** [comment]
Well thats suprising. They should reuse the z8 tile all the way down if they have a mask level specified..

I just dumped them to GeoJSON (but should look at the raw vector tile data preferably) and they all look the same even if they differ in their binary form: They all contain a polygon spanning over the entire area of the tile with OSM id 0.

**Comment by lukasmartinelli** [comment]
I really need to test the maskLevel out next thing I do. Generate MBTiles for some empty ocean and then I will just manually remove the higher layers, adjust the mask level and check how it looks.

**Comment by klokan** [comment]
It has surprised me as well. I expected z8 to be rendered - and bellow all levels either equal to z8 or at least equal to z9. +1 on testing the maskLevel in mapnik/tilelive/tessara.

We may need to adjust tileserver-php as well to provide the right "empty" tile for pbf requests... https://github.com/klokantech/tileserver-php/issues/56

**Comment by klokan** [comment]
@lukasmartinelli could you please prepare me an valid empty tile with no feature?
I will include it into tileserver.php.

**Comment by lukasmartinelli** [comment]
If no `maskLevel` is set it is automatically assumed that level 10 is https://github.com/mapbox/tilelive-vector/blob/24b2112a5b77c45f265c8b1834487a613884b7a5/backend.js#L37

**Comment by lukasmartinelli** [comment]
Some research.

## Rendering Times and Time/Space Savings

My hypothesis that water tiles render **much** faster than normal tiles was wrong!
Rendering water is only two to three times as fast as rendering urban areas.

Time of local machine for a `z8` all water tile: **206 seconds**
Time of server (8cores + 50GB): **84 seconds**
Size of MBTiles:  **428KB**

Time of local machine for a `z8` urban tile like around Zurich: **447.5  seconds**
Time of server (8cores + 50GB): **192 seconds**
Size MBTiles:  **129MB**

If we assume we can avoid rendering 40% of the world (even though 70% of world of water still have to render alot of water due to marine labels, borders, island etc). Because rendering water is 2.5x faster we **can save 24% time** (`1 - 0.6 - (0.4 * (1 / 2.5))`).

We can also save 11 GB in size of MBTiles (`65536 * 0.4 * 428KB`).

## Implementation Details of maskLevel in tilelive

If the source tells tilelive that the tile does not exist and zoom level is higher than the specified
mask Level the **tile parent** with the masked zoom level for the missing tile is calculated and requested.

Explained differently: If a `z14` tile is missing and `z8` is specified as mask level the `z8` parent of a `z14` tile is calculated and returned.

https://github.com/mapbox/tilelive-vector/blob/24b2112a5b77c45f265c8b1834487a613884b7a5/backend.js#L85-L91

```javascript
if (typeof backend._maskLevel === 'number' &&
    err && err.message === 'Tile does not exist' &&
    bz > backend._maskLevel) {
    bz = backend._maskLevel;
        bx = Math.floor(x / Math.pow(2, z - bz));
        by = Math.floor(y / Math.pow(2, z - bz));
        return source.getTile(bz, bx, by, sourceGet);
}
```

**Comment by klokan** [comment]
Thanks! So maskLevel runs as expected - despite the test above on MapBox hosting.

It seems to be the only test on water or not is to construct an SQL test query for region in question and all tables which potentially may provide something to the tiles on deeper zoomlevels. If such query tells there is nothing bellow - skip all related sub pyramid.

BTW I hope we manage the world under 32 GB - to fit on a USB stick ;-).

**Comment by lukasmartinelli** [comment]
There are two approaches.

## Variant 1: Query Data in Worker

One is to do the decision whether to render all tiles of z8 directly in the worker and avoid doing any extra work. In this case we need to query whether the source *would* render data. We need to build a query that is coupled to the source project.

Pros:
- 24% savings in time
- No additional component needed

Cons:
- Prone to errors (query needs to be pretty close to the actual source project query)
- More complex approach
- How do we know that we haven't missed something?

## Variant 2: Optimize MBTiles 

We could also do it in the aftermath after we generated the entire world. In this case we have to go through each z8 tile in the world MBTiles and check all it's descendants whether they contain the **same** data as the tile on z8. In this case we can remove them from the database.

Pros:
- Simpler algorithm -> easier to test and no rerendering needed if something is skipped)
- Also supports stuff like antarctica and desert
- More generic (works with any source project)

Cons:
- No saved time -> more expensive
- Actual optimizing might take a long time (assumption?)

**Comment by lukasmartinelli** [comment]
I personally want to do it afterwards (variant 2).

The querying is certainly doable in 6-8 hours but it is much harder to test and ensure quality.
And if we don't render something we need to rerender that part and fix it.

The second approach (although not as elegant perhaps) is more straightforward to implement and does not have any loopholes. If the algorithm works it works for any source project and kind of data redundancy.

**Comment by lukasmartinelli** [comment]
@klokan are you ok with the increased rendering time?

> The second approach (although not as elegant perhaps) is more straightforward to implement and does not have any loopholes. If the algorithm works it works for any source project and kind of data redundancy.

Implementation took only a hour. I can just check the checksum of the z8 tile and compare it with the
checksums of all descendants and I get the z8 pyramid which can be left out. Not performant but dead simple.

```python
def find_optimizable_tiles(mbtiles_file, maskLevel, scheme):
    mbtiles = MBTiles(mbtiles_file, scheme)
    parent_tiles = [t for t in mbtiles.tiles_at_zoom_level(maskLevel)]

    def descendant_checksums(x, y, zoom, max_zoom):
        for tile in all_descendant_tiles(x, y, zoom, max_zoom=14):
            yield mbtiles.inspect_tile(tile.x, tile.y, tile.z)

    for tile in parent_tiles:
        parent_checksum = mbtiles.inspect_tile(tile.x, tile.y, tile.z)
        counter = Counter(descendant_checksums(tile.x, tile.y, tile.z, 14))

        checksum, _ = counter.most_common(1)[0]
        if parent_checksum == checksum and len(counter) == 1:
            yield tile
```

**Comment by klokan** [comment]
I am OK with this dummy but universal approach.
We will render a lot of data which we later on throw away... :-(
