### ISSUE TITLE
Mobile friendly download page

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#422]
The http://osm2vectortiles.org/downloads/ page should be available in a more mobile device friendly form - for use in the OSM2VectorTiles mobile app.

We may adjust the CSS styles for use on mobile phones and tablets. Could you, @daliborjanak, please make a PR for these changes against the gh-pages branch of this project?

We may then release for the SOTM2016 conference a new version of the OSM2VectorTiles mobile app - which will allow people to download any area of choice for offline use (including the whole planet) to an Android or iOS device.

This is the link to the existing OSM2VectorTiles mobile app: http://onelink.to/7fpsaf

@lukasmartinelli - is it fine to link the mobile app from the main OSM2VectorTiles website?

**Comment by klokan** [comment]
Done in a first version.
See: http://osm2vectortiles.org/downloads/embed/

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli - is it fine to link the mobile app from the main OSM2VectorTiles website?

Yup link it!
