### ISSUE TITLE
Question: how to change 'extent' field of vector tile?

### ISSUE THREAD

**Issue by romanshuvalov** [osm2vectortiles/osm2vectortiles#424]
According to [Specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1), Mapbox Vector Tile format has `extent` property which represent resolution of coordinates. 

(Don't be confused with `extent` parameter of tm2source layers. By the way, I have no idea what is it for but removing it from tm2source reduces exporting time twice. But it's another question.)

I stuck with a problem with overzooming. When zooming 13th zoom level tile up to 18th zoom, there are sharp edges and even gaps between polygons edges). That's because low resolution of coordinate fields. I'm sure because I tried same test with 12th zoom level tile and there are more artifacts (more sharp edges and more gaps because of lack of accuracy). 14th tile also has artifacts but I test with 13th just to see them clearly. 

In Vector Tile PBFs coordinates are stored as integers between 0 and `extent` and by default `extent` is set to 4096. So, only 4096x4096 integer mesh for coordinates. Not accurate enough for overzooming. 

Is there way to change this parameter? (As I said, `extent` in tm2source is another parameter just with same name and that makes confusion.)

**Comment by romanshuvalov** [comment]
Look at this.

![z12_z13_z14](https://cloud.githubusercontent.com/assets/6326141/18410096/70366800-7769-11e6-80e6-9bb3498940bc.gif)

12th, 13th and 14th tiles are upscaled to 18th. Even 14th tile has a small gap in between polygons. 

Also it looks like smaller zooms not only has less accuate coordinates, but also has simplified geometry. Simplification is not written in `tm2source`, so it's performed somewhere inside tile exporting mechanism. 

How to adjust this parameters?

**Comment by lukasmartinelli** [comment]
> 12th, 13th and 14th tiles are upscaled to 18th. Even 14th tile has a small gap in between polygons.
> 
> Also it looks like smaller zooms not only has less accuate coordinates, but also has simplified geometry. Simplification is not written in tm2source, so it's performed somewhere inside tile exporting mechanism.
> 
> How to adjust this parameters?

What about going deeper with the zoom levels? That is not feasible if you do the entire planet but if you do only parts of the planet..

**Comment by romanshuvalov** [comment]
Found!

Tile object is created In [tilelive-bridge/index.js:243](https://github.com/mapbox/tilelive-bridge/blob/master/index.js#L243). There is no 'tile_size' parameter so default value of 4096 is used. 

Parameter can be added easly:
```
var tile_size_value = 65536;
// ...
var vtile = new mapnik.VectorTile(+z,+x,+y, {tile_size:tile_size_value, buffer_size:tile_size_value});
```

After that, vector tile will be created with 65536x65536 integer grid and `extent` parameter will be set to 65536 (or whatever you choose). It's accurate enough for overzooming. I've just tested - no gaps, no geometry simplifications. Brilliant. 
 
I modified `tilelive-bridge/index.js` for my purposes but generally this is not the best solution, it's better to store this tile_size value somewhere in `tm2source` file and read it while processing `tm2source`.

**Comment by romanshuvalov** [comment]
Important notice.

`MapBox GL JS` library seems to have accuracy limitations. Even if tile itself have coordinates with enough resolution, highly overtiled rendering (for example, 12th tile upscaled up to zoom level 17 and higher) with `MapBox GL JS` can cause clearly visible skewing of geometry. Keep it in mind.
