### ISSUE TITLE
ERROR:  function xyz_extent(integer, integer, integer, integer) does not exis

### ISSUE THREAD

**Issue by xingdavis** [osm2vectortiles/osm2vectortiles#428]
I follow the guidelines,
excute "docker-compose up import-sql", and then issue appears.

psql:/usr/src/app/functions.sql:27: ERROR:  function xyz_extent(integer, integer, integer, integer) does not exist
import-sql_1            | LINE 15:       geom && XYZ_Extent(0, 0, 0, buffer_size)

![image](https://cloud.githubusercontent.com/assets/11851006/18538575/ec8d0e00-7b41-11e6-9c80-7b7a360afe99.png)

**Comment by ImreSamu** [comment]
@xingdavis 
Thank you for the bug reporting ..    I am working on the fix #429

**Comment by ImreSamu** [comment]
@xingdavis 
Ready for testing !   ( Travis test OK ) 

* go to the project directory
 * `cd ./osm2vectortiles`
* you have to stop the running osm2vectortiles containers
 * `docker-compose down`
 * `docker-compose rm -f -v -a`
* download the new version from the github repo 
 *  `git pull`
* Please ->  rebuild the containers : 
  *  `make fast` 

And now you can start the tutorial:  
 * http://osm2vectortiles.org/docs/own-vector-tiles/

**Comment by xingdavis** [comment]
@ImreSamu Thank you.
