### ISSUE TITLE
Water shows tiling edges when used with line style

### ISSUE THREAD

**Issue by indus** [osm2vectortiles/osm2vectortiles#431]
![image](https://cloud.githubusercontent.com/assets/2046274/18660122/137b3138-7f0f-11e6-9ff9-63b3f35905cc.png)

Of course they show their outline because I told them to do so in the style. But in contrast to mapbox they not only show the shoreline but also their tiling edges. Would be nice if there is a solution to remove the latter so I can use only shoreline  and stateborders as an overlay for a raster map.

**Comment by hannesj** [comment]
Duplicate of #300?

**Comment by indus** [comment]
Jep! Thanks for the hint.

**Comment by indus** [comment]
"wonfix" is a bummer
