### ISSUE TITLE
Some questions about the rendering process and generate MVT

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#437]
I have read the "study thesis" and "bachelor thesis" these days.  It is  very helpful for me to understand the whole project. I am not very clear with some places in the thesis.

1\ Like the picture below, there is a process called render in the workflow. In my mind,"render" means render data to a picture with mapnik. But I found the "render" here means make the data to a MVT format. Am I  right? So  what is the function of mapnik here? Does mapnik provide some method to generate MVT?

![render](https://cloud.githubusercontent.com/assets/21222866/18912881/5fe4bb12-85b7-11e6-9f85-b76656f80d19.png)

2\  in page 29 of the bachelor thesis said
 "In order to support the Mapbox vector tile 2.0 specification the entire planet needs to be rerendered. If time and resources allow the project maintainers intend to do this in the future."
does this process begin?  if not how could I do something helpful.

3\ what tools did you use to generate MVT from data in postgreDB?

that's all my question. thank you for your patience.

**Comment by lukasmartinelli** [comment]
So these papers do get read :) Happy to hear.

> 1\ Like the picture below, there is a process called render in the workflow. In my mind,"render" means render data to a picture with mapnik. But I found the "render" here means make the data to a MVT format. Am I right? So what is the function of mapnik here? Does mapnik provide some method to generate MVT?

Render is the wrong word. It is actually encoding the data. But everyone is using rendering.. so we stick with it.
It is an extension to Mapnik https://github.com/mapbox/mapnik-vector-tile that turns the data into vector tiles (MVT) and stores it in MBTiles.

> 2\ in page 29 of the bachelor thesis said
> "In order to support the Mapbox vector tile 2.0 specification the entire planet needs to be rerendered. If time and resources allow the project maintainers intend to do this in the future."
> does this process begin? if not how could I do something helpful.

We already did that shortly afterwards (details in https://github.com/osm2vectortiles/osm2vectortiles/issues/368).

> 3\ what tools did you use to generate MVT from data in postgreDB?

It is using `tilelive-copy` (which in turns calls tilelive-bridge - which calls Mapnik).
Code for running it locally here: https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/export/export-local.sh

**Comment by bearnxx** [comment]
Thank you for your reply. To be honest the tow thesis is very helpful. I work in a top GIS study institution, I have not read any document such perfect these years. :)

**Comment by lukasmartinelli** [comment]
> Thank you for your reply. To be honest the tow thesis is very helpful. I work in a top GIS study institution, I have not read any document such perfect these years. :)

Oh I love this. We spent so much time in writing this dead paper document so your compliment is really flattering to us :)

You think it makes sense to pull some content out of the thesis and put it on the project wiki or so?

**Comment by bearnxx** [comment]
I think it is necessary, especially for the new user of this project. 
and also if some question can be indexed by google. It will bring some new user.
