### ISSUE TITLE
Generating countries.geojson

### ISSUE THREAD

**Issue by vitalcrazz** [osm2vectortiles/osm2vectortiles#452]
Hello!
I want to generate my own `countries.geojson` file with custom languages.
Actually I've already done it, but I'm a little bit confused about the `rank` property.

How to generate the `rank` property?
Or maybe you could publish your script for generating `countries.geojson`? I've not found this script in repository.
Thank you.

**Comment by ImreSamu** [comment]
>I want to generate my own countries.geojson file with custom languages.
>Actually I've already done it, but I'm a little bit confused about the rank property.

in the [Bachelor Thesis](https://cdn.rawgit.com/osm2vectortiles/bachelor-thesis/882a46977f7b984fc59be188335127d62921c44c/thesis.pdf)   - there is some information: 
**3.3.4 Place Label Rank Calculation**
_"Ranks are important for determining at which zoom level which places should be displayed.
The NaturalEarth database contains places with scaleranks assigned by humans and is the
most important source for better quality labels (historic places might be much more important
despite having a very small population). This dataset is merged with the imported OpenStreetMap
data. They can also be used to limit density at lower zoom levels to decrease data
density. Using the scalerank and other information such as place type and population the
actual rank called localrank is calculated. An example of localrank calculation can be seen in
figure Figure 13 (localrank is denoted as number inside circle)."_

so my guess - this info from [NaturalEarth](http://www.naturalearthdata.com/forums/topic-tag/scalerank/)

**Comment by vitalcrazz** [comment]
Thank you, @ImreSamu
