### ISSUE TITLE
Hardware requirement

### ISSUE THREAD

**Issue by gisgraphy** [osm2vectortiles/osm2vectortiles#457]
I have googled it and look at the documentation but I can not find the hardware requirements to host tileserver-gl-light for all the planet. RAM, CPU, hard drive, bandwith... 

Is there some advices on the number of CPU to handle something like ~1600 tiles per seconds (100 maps of 16 tiles) . 
Is it better to have a loadbalancer with several small servers or one big ?

Is it CPU bound ? is http://ark.intel.com/products/88173/ a good choice? how many request can we handle with this

Many thanks

**Comment by hyperknot** [comment]
I was serving full planet v1 on a 10 EUR per month VPS from Scaleway. The
key is to use nginx proxy with at least a month of caching time. You'll
need at least 4 GB ram.

**Comment by ImreSamu** [comment]
> .. tileserver-gl-light ...

as I know 
*  64bit +  Amd64/Intel CPU a minimal (  32bit + ARM  not supported )

more information:  
* https://www.npmjs.com/package/tileserver-gl-light
* https://github.com/klokantech/tileserver-gl
* https://github.com/klokantech/tileserver-gl/issues

**Comment by klokan** [comment]
**TileServer GL Light** is lightweight - and runs everywhere where node.js runs - no limits. It serves only PBF vector tiles - it does not render raster tiles (PNG/JPEG) from these on the server. Any cheap VPS is fine. Test performance on your selected hosting platform for the number of visits you need.

**TileServer GL** renders the tiles on the server side - and needs better hardware and must be used with a cache for serious deploy. Binary libraries are compiled only for 64bit systems - elsewhere you need to compile yourself. Loadbalancer recommended.

This discussion belongs to repository https://github.com/klokantech/tileserver-gl where is the code of the project.

Be aware of legal issues with deploying OSM2VectorTiles tiles #387
