### ISSUE TITLE
If MapZoom is from 0 - 20, that we need to create vector tiles to zoom level 20?

### ISSUE THREAD

**Issue by joaokho** [osm2vectortiles/osm2vectortiles#461]
Hi,

I already process own data: street, suburb, state, cadastre, geocode national address into osm.
i use osm2vectortiles to generate zoom level 9-14 is take 2-3 hour, but it already can view on zoom level 20.

My questions is we need to generate level 14,15 ... 20 ? Because will take very long time to generate and a lot of space needing ?? I think? 

Any suggestion? Thanks in advance

**Comment by joaokho** [comment]
I look at data.yml all the query is limited to zoom level 14 only, so i think it's no need to docker-compose to assign generate vector tile more than zoom level 14, it is correct?

**Comment by lukasmartinelli** [comment]
> My questions is we need to generate level 14,15 ... 20 ? Because will take very long time to generate and a lot of space needing ?? I think?

All data for 15-22 is already contained within the z14 tile. You only needs to go as deep if you need to add even more detail. Mapbox GL can overzoom - so use features from z14 in a z16 tile.

**Comment by joaokho** [comment]
Thanks
