### ISSUE TITLE
Error while referencing to my style on localhost:8080

### ISSUE THREAD

**Issue by pokyah** [osm2vectortiles/osm2vectortiles#462]
Hi all,

I try to run a local tileserver using osm2vectortiles. 

Everything works fine. But when I want to use a local style referenced as a javascript object in my index.html file (see https://gist.github.com/pokyah/17f1efb06b1c731ccd20816d77366f5a) according to the presentation made at FOSSGIS 2016 (https://youtu.be/lG7atynI8Pk?t=13m12s) 

I get the following error in my navigator console : 
<img width="924" alt="screen shot 2016-11-03 at 13 14 25" src="https://cloud.githubusercontent.com/assets/15193683/19965508/93832f2c-a1c7-11e6-94a2-1439e89a9f90.png">

Any idea of what is wrong in my code ? 

Thanks for your support.

**Comment by lukasmartinelli** [comment]
Not like that (only works for TileJSON endpoints)

```
    "sources": {
        "mapbox": {
            "url": "http://localhost:8080/data/osm2vectortiles/{z}/{x}/{y}.pbf",
            "type": "vector"
        }
    },
```

but like that

```
    "sources": {
        "mapbox": {
            "tiles": ["http://localhost:8080/data/osm2vectortiles/{z}/{x}/{y}.pbf"],
            "type": "vector"
        }
    },
```

**Comment by pokyah** [comment]
Thanks @lukasmartinelli,

now it effectively works ! I just get another problem : above a certain zoom level I get the following error in my navigator console : GET http://localhost:8080/data/osm2vectortiles/15/24148/13756.pbf 404 (Not Found)

I'll check it by myself but if you have a quick suggestion ? 

Thanks again

**Comment by lukasmartinelli** [comment]
> now it effectively works ! I just get another problem : above a certain zoom level I get the following error in my navigator console : GET http://localhost:8080/data/osm2vectortiles/15/24148/13756.pbf 404 (Not Found)

To solve that set a minzoom and maxzoom in the vector tile source (as described in mapbox gl style spec referenced above).
