### ISSUE TITLE
How to render diff updates locally

### ISSUE THREAD

**Issue by vitalcrazz** [osm2vectortiles/osm2vectortiles#464]
Hello!

I followed the **Detailed Usage Guide** to apply and render diff updates (for my small region).

I stopped at the last step:
```
docker-compose scale export-worker=4
docker-compose run merge-jobs
```

As I see, this step requires Amazon S3 services. But I want to execute it locally. What should I do?

I tried to execute `docker-compose run export-list` using `tiles.txt` file (from changed-tiles step).
It works, but it updates not all of necessary tiles.
As I understand, `tiles.txt` should be treated using `pyramid` scheme, not `list`. Am I right?

Thank you for building such a great workflow by the way.

**Comment by lukasmartinelli** [comment]
> I followed the Detailed Usage Guide to apply and render diff updates (for my small region).

You can run `docker-compose export-list` to export whatever is in `tiles.txt`.

**Comment by vitalcrazz** [comment]
I just try to understand the `changed-tiles` command output.
We have a list of tiles. For example, line `7/68/52`. Does it mean that we should rerender all nested tiles from zoom 7 to zoom 14?  Or just one specific tile at zoom 7?

**Comment by lukasmartinelli** [comment]
The specific tile at zoom level 7. The jobs component can bundle up tiles back into jobs (and looking after proximity).
