### ISSUE TITLE
Documentation of file format.

### ISSUE THREAD

**Issue by mg262** [osm2vectortiles/osm2vectortiles#467]
I'd be grateful for any documentation of the file format you use.  The extension suggests you are using a vector variant of MBTiles -- but this is not supported by the latest MBTiles specification... 

https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md

**Comment by lukasmartinelli** [comment]
> The extension suggests you are using a vector variant of MBTiles -- but this is not supported by the latest MBTiles specification...

What parts of the spec is not fulfilled? Do we miss metadata in `select * from metadata`?
You will have problem inserting new tiles directly into `tiles` (since it is made up from views to save redundant PBFs) but from the reading perspective the MBTiles spec should be fulfilled.

**Comment by klokan** [comment]
Looks like a duplicate to this request:
https://github.com/mapbox/mbtiles-spec/issues/43

The documentation should happen on the mbtiles-spec repo probably...

**Comment by mg262** [comment]
@lukasmartinelli The docs say 

>The image file format of the tile data: png or jpg

which pretty clearly indicates that it's only meant for raster data.  Later it states:

>The tile_data blob column contains raw image data in binary.

And gives PNG and JPG as options. 

NB. I'm not trying to be pedantic; from reading your docs + the mbtiles docs, I don't have a clue how you are actually _storing_ the vector data.  My guess is that you are storing it in tile_data, but beyond that ...?  Are you using some unpublished extension to MBtiles?

**Comment by lukasmartinelli** [comment]
> NB. I'm not trying to be pedantic; from reading your docs + the mbtiles docs, I don't have a clue how you are actually storing the vector data. My guess is that you are storing it in tile_data, but beyond that ...? Are you using some unpublished extension to MBtiles?

In `tile_data` it is a gzipped Mabpox Vector Tile Specification Protobuf as produced by https://github.com/mapbox/tilelive/blob/master/bin/tilelive-copy

**Comment by mg262** [comment]
Thank you @lukasmartinelli !
