### ISSUE TITLE
Live update of OSM2Vectortiles

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#468]
This is a discussion issue exploring how to have a fully updated OSM2Vectortiles that is as near to "live" as humanly possible. I'd also like to explore how to have the updates streamed, so that the downloading of data may be minimized.

Thoughts as how to achieve this:

1. Have a new container which performs the updates on a database, grabbing the minute changes and applying them. I know there's been some work on imposm and figuring out the changed tiles. I've been out of the loop on this but I want to explore this further and anticipate quite a few changes, especially depending which way the styling goes.
2. The changed tiles will be dumped through generate-jobs, putting the jobs into RabbitMQ. I don't anticipate any changes to generate-jobs.
3. RabbitMQ will need to be long-lived, but no changes anticipated to what's already there.
4. Export-workers will need to be long-lived. What I'd like to see is a new export format, where instead of mbtiles, it's a stream of "UPDATES" so that the MBTiles may be updated continuously.

What are other's thoughts on this? I'm happy to explore (4) as I know some work on imposm is already in the works.

**Comment by klokan** [comment]
Answer to 4 is https://github.com/mapbox/serialtiles-spec
We are working on the updates at @klokantech

**Comment by stirringhalo** [comment]
@klokan Is the work on github?

**Comment by stirringhalo** [comment]
Oh cool, I figured out how to get tilelive-copy to serialize the mbtiles. So this should be easy to adapt the export-worker to send out the stream. You probably know this, but to do so, just leave off the destination for tilelive-copy and it will stream it.
