### ISSUE TITLE
What is the purpose of osm2vectortiles.json ?

### ISSUE THREAD

**Issue by mg262** [osm2vectortiles/osm2vectortiles#478]
I'm trying to understand how this is put together; I'd be grateful if you could clarify a point. A style file such as e.g. `bright-v9.json` refers to `osm2vectortiles.json`, and then `osm2vectortiles.json` refers to the vector tiles like so:

"tiles":["http://localhost:8080/data/osm2vectortiles/{z}/{x}/{y}.pbf"]

What is the advantage of having the intermediate file `osm2vectortiles.json`, as opposed to simply having the style file point directly at the vector tiles? 

Thanks!

**Comment by lukasmartinelli** [comment]
> What is the advantage of having the intermediate file osm2vectortiles.json, as opposed to simply having the style file point directly at the vector tiles?

This intermediary format is called TileJSON https://github.com/mapbox/tilejson-spec and has additional information about what is in the tiles. 
It allows specifying multiple tileservers for example. But directly specifying x/y/z is fine as well.

**Comment by mg262** [comment]
Thanks!
