### ISSUE TITLE
Label placement algorithm

### ISSUE THREAD

**Issue by mg262** [osm2vectortiles/osm2vectortiles#480]
I'm trying to understand the label placement algorithm for roads (and want to see if it can be tweaked to produce fewer labels).  

Looking at osm2vectortiles.tm2source/data.yml tells me that the final `road_label` layer is stitched together from SQL views with names like `road_label_z8toz10`. src/import-sql/layers/road_label.sql then shows that these are generated from the `osm_road_geometry` table.  But I can't find where/how `osm_road_geometry` is generated...

https://github.com/osm2vectortiles/osm2vectortiles/search?utf8=%E2%9C%93&q=osm_road_geometry

only shows usages, not creation.  But Google + github search suggests `osm_road_geometry`  is specific to osm2vectortiles, not `imposm3`.  I'd be very grateful if anyone could tell me where the `osm_road_geometry` table comes from, so I can track back the source of the label data.

**Comment by ImreSamu** [comment]
>I'd be very grateful if anyone could tell me where the osm_road_geometry table comes from, so I can >track back the source of the label data.

imposm3 default table name prefix is `osm_`  see https://imposm.org/docs/imposm3/latest/tutorial.html#writing
so just look for `road_geometry` 
 *   https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-osm/mapping.yml#L513

**Comment by mg262** [comment]
Thanks!
