### ISSUE TITLE
Large polygon is split into tiles, tile edges are visible

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#484]
National parks in the source layer "landuse_overlay" are correct between zoomlevel 5 and 12. Beginning with zoom level 13 horizontal and vertical lines become visible, presumably the edges of tiles. This way it's impossible to apply fill-outlines.

See screenshot: The green line along the bottom is the correct border of the national park yet the straight lines within are not.

![screen shot 2016-11-29 at 16 07 30](https://cloud.githubusercontent.com/assets/1606618/20715102/63536fc4-b64e-11e6-81c8-3143aa0f5c17.png)

Location hash of that area: #13.16/47.0350/12.6977

**Comment by indus** [comment]
#300
#431

**Comment by hannesj** [comment]
This was recently fixed in Mapzen tiles by https://github.com/tilezen/vector-datasource/pull/1124

**Comment by lukasmartinelli** [comment]
> This was recently fixed in Mapzen tiles by tilezen/vector-datasource#1124

But in a post processing step we don't have here :(

**Comment by muesliq** [comment]
Thanks, I'm closing this, duplicate & won't fix.
