### ISSUE TITLE
POI_Labels not display in level 13

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#485]
I want to display POI_labels in level 13, so I changed the data.yml in osm2vectortiles.tm2source. Like the picture below, I changed  "WHERE z(!scale_denominator!) = 13" and read the same data from the view poi_label_z14.

![13yml](https://cloud.githubusercontent.com/assets/21222866/20745677/51e8a374-b71d-11e6-9ca5-ce8fc97cb7eb.png)

and after I excute docker-compose export I checked the mbtiles with TileInfo tool. there are POI_label in the vector tiles and also there are features in the layer. like picture below.
![qq 20161130165436](https://cloud.githubusercontent.com/assets/21222866/20745767/b08a493c-b71d-11e6-888d-74a09f0a1885.png)

why the poi_label didn't display in the web browser? is it relative to the bright-v9.json?

**Comment by lukasmartinelli** [comment]
> why the poi_label didn't display in the web browser? is it relative to the bright-v9.json?

Very possible that I limited the POI appearance in the style JSON as well.

**Comment by bearnxx** [comment]
yes I edited the style json and it worked! thank you !
