### ISSUE TITLE
Incompatibility with mbtiles

### ISSUE THREAD

**Issue by twisig** [osm2vectortiles/osm2vectortiles#487]
Hi,

I would to export some tiles from SQLITE in MBTILES. 
Each tile is stored in binary format but the image is corrupted.

Can you explain how to generate your tiles ?

thx

**Comment by stirringhalo** [comment]
What do you mean corrupted?

The stored tiles are actually gzipped in the the mbtiles. You will have to extract each before you can decode it with some pbf library.

**Comment by twisig** [comment]
OK I understand your answer. 
What is the tool to ungzip the mbtiles ? I would like to see the data. Is it a Geojson, topojson or json ?
Thx

**Comment by stirringhalo** [comment]
Lookup gzip, there's plenty of ways to do so in just about any language.

**Be aware of legal issues with deploying OSM2VectorTiles tiles #387**

**Comment by mg262** [comment]
@gistack See http://gis.stackexchange.com/questions/217704/vector-tile-formats-vector-mbtiles-and-mvf .
