### ISSUE TITLE
Why are some coordinates outside the extents?

### ISSUE THREAD

**Issue by mg262** [osm2vectortiles/osm2vectortiles#496]
Sometimes road geometries start with a x/y coordinate that is outside the range [0, 4096] -- one even finds negative values like -10.  What's going on? Is there some buffer around the edges of tiles?  If so, why is this needed?  It it because a road segment can cross boundaries and it's easier to put in a buffer than to clip the segment?  (But that can't be quite right, because some road segments are _very_ long... )

NB. I've looked at the thesis, but can only find mention of an extra buffer zone for determining whether a tile has changed, which seems quite different.

**Comment by stirringhalo** [comment]
I don't know the exact rationale but I think it goes along these lines:
1) Spatial operations are expensive, it's usually cheaper to load features that intersect the tile than to clip them. Sure for line segments it doesn't seem so bad. But, consider complicated coastlines with 100s of vertices. Clipping is slow and has a risk of generating bad geometries. Sending the entire feature is safer, and although larger, is should be faster.
2) Drawing is cleaner as you don't have sharp cuts that follow exactly on tile extents.
