### ISSUE TITLE
mbtiles over https?

### ISSUE THREAD

**Issue by Benni08** [osm2vectortiles/osm2vectortiles#504]
I don't now, if im writting here to the wrong Forum, but please, i such need help.

Im searching vor a Tilesserver, that can serve the Maps from the osm2vectortiles.mbtiles over HTTPS.

I hope you can help me.

I've found no posibility to get the tilesever-gl working over https.

**Comment by stirringhalo** [comment]
You could always reverse proxy: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by klokan** [comment]
TileServer GL runs behind HTTPS very well. We use it always on deploy.
See for example: https://demo.tileserver.org/

Relevant:
http://tileserver.readthedocs.io/en/latest/deployment.html#running-behind-a-proxy-or-a-load-balancer
