### ISSUE TITLE
Serving tiles with tileserver-php - land and water polygons missing?

### ISSUE THREAD

**Issue by int19h** [osm2vectortiles/osm2vectortiles#505]
I apologize if this is the wrong repo - it's kinda hard to figure out where this should go, as I'm not sure where the problem is, exactly.

Briefly, I'm trying to serve an mbtiles file for USA downloaded from osm2vectortiles via tileserver-php (the reason is that the machine serving it is running FreeBSD, and successfully building all the requisite Node modules even for tileserver-gl-lite, much less tileserver-gl, has proven to be very difficult - most native modules seem to assume it's either Linux or OS X, and there's a lot of build script breakage etc). 

Based on this bug being closed with "implementation finished", I assumed that this is a supported scenario:
https://github.com/klokantech/tileserver-php/issues/42

Now, when trying to actually test it, using tileserver-php's own index page, I'm seeing the maps, but it seems like the base layer (land and water polygons? not sure what it's called properly) is missing. Here's how it looks:

![image](https://cloud.githubusercontent.com/assets/1175142/21959042/5f017f92-da70-11e6-9cdc-a7d628cb04ef.png)

(It is the same at any zoom level)

Now, all I did was follow the instructions on tileserver-php: unpack it into the www folder of a PHP (7.0) enabled Apache 2.4 installation, copy .mbtiles file there, and open it in the browser. 

Is there some configuration step that I'm missing specifically for .mbtiles from osm2vectortiles? Do I need to download some separate vector tileset for those polygons?

**Comment by int19h** [comment]
Closing it here and opening in tileserver-php instead.

https://github.com/klokantech/tileserver-php/issues/95

**Comment by hyperknot** [comment]
I had so much trouble exactly with this on FreeBSD that I migrated to
Ubuntu where everything is supported. Your easiest choice would be Linux in
Docker in FreeBSD.

**Comment by int19h** [comment]
FWIW, I'm having the same exact problem on Windows.

I'd like to avoid Linux in Docker if at all possible, because it consumes quite a lot of space (which, when maps are involved, is already precious).

**Comment by hyperknot** [comment]
It takes a few hundred MBs, which compared to GBs of map data is quite
nothing.

I've literally wasted a month of my time trying to set up a full tile
generation environment on FreeBSD. After I've given up it pretty much got
replaced with a 1 minute docker pull.

It's up to you what do you choose.

**Comment by int19h** [comment]
This particular issue is not actually FreeBSD related - note that this is about *serving* premade tiles, not generating them. Turned out it was entirely a client-side issue: I just needed to set up the styles properly. This is discussed in the comments to the other issue linked above, for those hitting the same problem.
