### ISSUE TITLE
OSM Carto Visual Style 

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#7]
Optional Carto Style for MBTiles. https://github.com/gravitystorm/openstreetmap-carto

**Comment by klokan** [comment]
Reopening and removing from FINAL milestone. This work is not fiinished, but is is not suppose to be done now.

**Comment by lukasmartinelli** [comment]
Out of scope for the bachelor thesis.

**Comment by klokan** [comment]
This ticket is practically beeing implemented under:
https://github.com/geofabrik/openstreetmap-carto-vector-tiles
and related JSON style under:
https://github.com/stirringhalo/openstreetmap-mapboxgl
