### ISSUE TITLE
Preview native app with node-webkit on USB stick

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#72]
Idea: Offer USB disk with offline preview of the OpenStreetMap map showing the Mapnik rendered tiles or offline MapBox GL JS. I am now getting info about how USB sticks could be ordered and shipped.

Amazing would be to have on the stick, next to the world MBTiles file (ideally under 32GB size), also a basic viewer running everywhere - just like the "docker serve" - but with basic double click start for most platforms.

It seems it may be pretty easy to turn the node.js app into Windows / Mac / Linux app with http://nwjs.io/
see:
http://tutorialzine.com/2015/01/your-first-node-webkit-app/
https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps

Tilemill, MapBox Studio, Kitematic, etc are build this way...

**Comment by lukasmartinelli** [comment]
> Amazing would be to have on the stick, next to the world MBTiles file (ideally under 32GB size), also a basic viewer running everywhere - just like the "docker serve" - but with basic double click start for most platforms.

I like it - hope we have time for this. I forgot those kinds of applications - but they are as good use cases as having a custom base map.
That's the beauty of our project - because we provide the data it is possible to integrate it into offline applications like these.

It is very fancy nowadays to deploy packaged node apps as single binaries - there should be enough resources describing how to do this.

**Comment by klokan** [comment]
@manuelroth tried http://electron.atom.io/ successfully. Could you please push it to GitHub?

**Comment by manuelroth** [comment]
@klokan I created a [repository](https://github.com/osm2vectortiles/offline-maps) with instructions to build an electron app for offline serving of our vector tiles. Right now I use tessera so no Mapbox GL. I couldn't get it to work with Mapbox GL. Would love to hear if you can get it to run with my instructions.

**Comment by klokan** [comment]
I tried - it was running fine on Mac. The server stopped after some time unfortunately.
We need to wrap the whole app in installer and finish this task.

**Comment by manuelroth** [comment]
In order to wrap the app in an installer, the native node modules(node-mapnik) need to be rebuilt.

Here a comment, which describes why the native modules need to be rebuilt:
> Electron is using the V8 shipped by Chromium, which is usually much newer than the V8 used by Node, and the differences are big enough to make native modules compiled for electron and Node not compatible. I'm afraid this incompatiblity is not going to change because we can not force Chromium to be built with older V8.

The [documentation](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) of electron describes how to do this. But unfortunately it always exited with an error. I don't think that we can do anything about this.

**Comment by klokan** [comment]
Is MapBox Studio build with Electron? If it is, you can get from them automated build scripts (probably for appveyor.com - the CI a la Travis for windows apps) or even extract the binaries from existing MapBox Studio package and reuse these with the same version of environment as they use...

**Comment by klokan** [comment]
Preferred would be to have our own repo with autobuild in AppVeyor of course...
Related: https://github.com/atom/electron/issues/533

**Comment by manuelroth** [comment]
They are using Electron (previous atom-shell), but Dane Springmeyer explained in [this issue](https://github.com/mapbox/node-sqlite3/issues/357) that they are not using node modules in Mapbox Studio at all.

Here his comment:
> Mapbox studio is not using atom shell and node-sqlite3 in the same process. The lack of binary compatibility with node was a major deterant. Because we have multiple node c++ addons and support multiple platforms having to provide 2x the binaries for atom-shell is not viable for us at this point. So Mapbox Studio is only using atom shell for the browser and not taking advantage of the ability to call into node modules.

But how can they do the mbtiles export in Mapbox Studio if they are not using any node modules at all?

**Comment by klokan** [comment]
Compilation of MapBox studio is made in:
https://github.com/mapbox/mapbox-studio-classic/blob/mb-pages/.travis.yml
and
https://github.com/mapbox/mapbox-studio-classic/blob/mb-pages/scripts/build-atom.sh

**Comment by lukasmartinelli** [comment]
Compilation for Windows can be found here:
https://github.com/mapbox/mapbox-studio-classic/blob/mb-pages/appveyor.yml and
https://github.com/mapbox/mapbox-studio-classic/blob/mb-pages/scripts/build-appveyor.bat

**Comment by klokan** [comment]
Another approach would be to create a basic QT application with binaries for different platforms which would use https://github.com/tmpsantos/qmapboxgl and render the vector tiles offline directly from the USB disk with OpenGL. We can try this approach at @klokantech.

**Comment by lukasmartinelli** [comment]
> Another approach would be to create a basic QT application with binaries for different platforms which would use https://github.com/tmpsantos/qmapboxgl and render the vector tiles offline directly from the USB disk with OpenGL. We can try this approach at @klokantech.

For the end user this is the most convenient option as he gets a native application. Would need to work a bit on QT skills but for a basic application that should be doable. 
Let's keep it in the backlog for the kick off.

btw: It would also be cool if we can prototype something offline with Mapbox GL on Android.

**Comment by klokan** [comment]
Advantage of going with QT is guarantee that OpenGL will run on all platforms. This is hard to get with embedded WebKit and Node.js...

Offline native MapBox GL for both Android and iOS apps could be prototyped with Phonegap online service / Apache Cordova and the plugin: http://plugins.telerik.com/cordova/plugin/mapbox and the sample app.

With JavaScript MapBox GL for Android and iOS offline app should be doable as well with http://trevorpowell.com/2015/02/20/mapbox-gl-js-with-offline-vector-tiles-on-cordova/ and https://github.com/trevorpowell/mapbox-gl-js-cordova-offline-example - but this a bit of hack and will have troubles on different mobile phone because of missing WebGL in WebKit, unless we pack webkit with the app as well (which ads about 50 MB to the app size).

In all cases, if we go for mobile app - it should be tracked in a different ticket.

**Comment by sfkeller** [comment]
Just another 2 cents: Perhaps QGIS Browser https://www.qgis.org/en/site/about/features.html#qgis-browser would be an option when our Vector Tiles Reader Plugin is ready
http://giswiki.hsr.ch/Vector_Tiles_Reader_QGIS_Plugin ? I don't have used yet this "Browser" variant of QGIS though.

**Comment by sfkeller** [comment]
Interesting project: https://github.com/mapbox/mapbox-gl-native

**Comment by klokan** [comment]
@sfkeller - the projects I mentioned are powered by mapbox-gl-native.

I have made and compiled first version of the mobile app:
https://github.com/klokan/osm-vector-offline/
Still, most of the work still must be done:
https://github.com/klokan/osm-vector-offline/issues

**Comment by lukasmartinelli** [comment]
Nice, now we have a skeleton to start with :+1: . If offline support is coming in Q1 
https://github.com/mapbox/mapbox-gl-native/issues/584 we can actually do this.

**Comment by klokan** [comment]
Show stopper for QMapBoxGL or native MapBox GL in general: the mapbox-gl-native does not compile on Windows: https://github.com/mapbox/mapbox-gl-native/issues/1421

**Comment by klokan** [comment]
The basic binary web server application for USB stick is now finished. Looks like:

![2016-03-01](https://cloud.githubusercontent.com/assets/59284/13501460/139dd814-e167-11e5-85de-d25db6d370e5.png)

It is standalone signed windows .exe and mac .app. It serves on localhost the content of "static" directory (with index.html and all assets) and it serves also raster or vector tiles dynamically from .mbtiles located next to the application binary.

We will release it soon. Now it would be great to have v2 tiles which fits to 64GB disk ;-).

**Comment by klokan** [comment]
Regarding offline use on mobile apps SDKs for Android / iOS: https://github.com/mapbox/mapbox-gl-native/issues/4178

**Comment by sfkeller** [comment]
What a cool gadget!

**Comment by lukasmartinelli** [comment]
This issue was primarily for the CeBit right? Can we close it?

The size problem with 64 GB is stated elsewhere.

**Comment by klokan** [comment]
The preview application for USB disk is now finished. I am closing this ticket.

The USB disks must be ordered one month before they are delivered. For placing the order the new complete world map with MBTiles not bigger than 60 GB should be uploaded to the remote location.

Next events where the USB disks would be practical are: GeoSummit (June 5th), FOSSGIS (July 4th), FOSS4G (24th August).
To meet the GeoSummit deadline - the new world MBTiles should be available by the end of April, latest in the beginning of May.

Could you prioritize the tasks related to world rendering and fixing of the mapping - to start the rendering of world on cluster in following few weeks @lukasmartinelli @manuelroth?

BTW what about to meet on Hangout this week to catch up on the progress?

**Comment by lukasmartinelli** [comment]
> 60 GB

Is this verified? A NTFS (or the planned filesystem) formatted 64GB USB stick still has 60GB of space?

> Could you prioritize the tasks related to world rendering and fixing of the SQL mapping - to start the rendering of world on cluster in following few weeks @lukasmartinelli @manuelroth?

@manuelroth now works on v7 which includes a lot of mapping changes. It is the same as last time, we first need to freeze the mapping before we can start rendering at all. And this time it is even more important to have enough time for the mapping because you can't change it after the diff process is running.

Our goal is to start rendering end of April so it will be close..

**Comment by klokan** [comment]
Unverified. By looking on the web it seems the final limit for MBTiles is going to be more 59 GB - we may need for the software itself ~100 MB (Mac signed fat binary with Intel 32+64bit+PowerPC + Windows statically compiled QT for compatibility from XP SP3 above + probably a basic start.py for Linux or general multi-platform command-line use by hackers on a computer with python interpret).

I will check the used filesystem and exact numbers (in bytes) with the manufacturer and let you know.

**Comment by lukasmartinelli** [comment]
> Unverified. By looking on the web it seems the final limit for MBTiles is going to be more 59 GB - we may need some space for the software itself ~100 MB (Mac signed fat binary with Intel 32+64bit+PowerPC + Windows statically compiled QT for compatibility from XP SP3 above + probably a basic start.py for Linux or general multi-platform command-line use by hackers on a computer with python interpret).

Okay, I know it is quite difficult to estimate.
The bad thing is we can only guess/estimate whether we will make it below 60GB even when we improve the road problem #86 (which might have already been resolved by #187). Especially since we are when we are adding stuff again when implementing v7.



> BTW what about to meet on Hangout this week to catch up on the progress?

What about next week? Would also be good to have input from Andreas then to check how we should proceed.

**Comment by klokan** [comment]
To test the apps and sample content of the USB disk download and unpack this ZIP file:
https://drive.google.com/open?id=0BwUe1kqIRJWST2FGTFFGQ0RfZjg

Next week for the Hangout meeting would be nice. Monday 14:00?

**Comment by lukasmartinelli** [comment]
Yes 2pm works. We have the next meeting at 3pm.
