### ISSUE TITLE
Vector Tile Server Discussion

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#81]
Hello Petr

We had a look at how to recompile mapnik to take vector tiles as source. Mapnik has an option to compile the source with an sqlite plugin. But this is not all it takes to read the vector tiles. Because of this Mapbox created the project mapnik-vector-tiles, which implements the mapbox vector tile specification for mapnik. The problem is that there is no documentation on how to compile the mapbox vector tiles implementation together with mapnik. 

The node-mapnik module handles the bindings to the special version of mapnik which contains the implementation of the vector tiles specification. To build up the same stack with mod_tile and renderd we would have to write a custom renderd daemon and compile this special mapnik version. 

We also analyzed how wikimedia built their tileserver. It turned out that they use the same node-mapnik module. They scale horizontally to handle many concurrent requests. Today, we reached out to the creator of kartotherian for getting his opinion on handling many concurrent users.
​
We worry that we would need to invest a lot of time in creating the renderd setup (inlcuding writing custom C++ code) just to check whether there are performance benefits. The time invested now indicates that this is not such an easy setup as it seems.

We talked today with Prof. Keller and discussed the importance of performance for this project. His advise is to delay performance and concentrate on completing the tm2source project and actually produce the mbtiles.

For these reasons we decided to no longer invest time in a more performant tileserver based on mod_tile because the basic needs are met with a tessera based setup.

We are actually able to handle 50 concurrent users with the tessera setup and a small server which suffices for the target group.

Tessera Setup:

Tessera calls the tilelive modules which directly invoke the Mapnik library (no local socket). There might be a small overhead in using JavaScript over C++ but because most work is IO related this difference is probably insignificant.

![tessera_node_bindings](https://cloud.githubusercontent.com/assets/1810384/11585449/6bf72a16-9a6c-11e5-8b3b-8386b4cd2d93.png)

Apache mod_tile introduced nice features such as caching (but those can easily be replicated with an Nginx in front of tessera) but requests are then relayed to the renderd daemon over Unix sockets. The tilelive modules invoke Mapnik directly without relaying the request to another process.

If we want to support vector tiles we would have to introduce vector tile support into the renderd daemon.

![mod_tile](https://cloud.githubusercontent.com/assets/1810384/11585451/6f4e381c-9a6c-11e5-9680-9c36a9b9f691.png)

**Comment by lukasmartinelli** [comment]
This is just for archival purposes.

**Comment by klokan** [comment]
This should have been a comment on #5 instead of a new ticket here - without milestone...
