### ISSUE TITLE
Tiles missing

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#87]
Bad news. Seems at the end of the rendering when we had the weird spikes some tiles got lost. I suspected this because we had not quite 64k MBTiles.
Or what is more likely is that I forgot to schedule a certain area - because I scheduled the separate place by hand.

It is only in the USA, Europe seems to be fine.

![skiirujd2k](https://cloud.githubusercontent.com/assets/1288339/11721085/5686d136-9f62-11e5-873d-bbe4d364d82d.gif)

I don't think this is because of removing the water tiles - it is due to missing MBTiles files in the first place.
I will enumerate the files on S3 and compare it with the tile indizes that should have been rendered to find out the missing ones.

How urgent this is depends a bit on what we want to publish at what date.

**Comment by lukasmartinelli** [comment]
Find the real tiles that should exist.

```bash
mercantile children "[0,0,0]" --depth 8 > correct_tiles.txt
```

Find the list of MBTiles from S3

```bash
aws s3 ls s3://osm2vectortiles > real_tiles.txxt
```

Bring both in to the same format and also sort them.

```bash
awk '{print $4;}' list_of_mbtiles.txt \
| sed 's/_z8-z14.mbtiles/_8/g' \
| sed 's/_/\//g' \
| sort > fixed_real_tiles.txt
cat mercantile_children.txt \
| sed 's/, /\//g' \
| sed 's/\[//g' \
| sed 's/\]//g' \
| sort > fixed_correct_tiles.txt
```

Find out the missing tiles

```
diff --unchanged-line-format="" fixed_correct_tiles.txt fixed_real_tiles.txt > missing_tiles.txt
```

**Comment by lukasmartinelli** [comment]
It really seems I forgot a tile area to schedule.

https://gist.github.com/lukasmartinelli/b1a5c672dd83f344e76c#file-missing_tiles-csv

**Comment by lukasmartinelli** [comment]
No completely wrong - the files actually are all there. One chunk of files was in a folder :see_no_evil: therefore they were not listed. In fact only 2 tiles are missing (and those are the same that were hanged up in the bucket).

This means it **was a merging problem** and requires no rerendering.

The tiles that are missing:
```
49/70/8
60/87/8
```

I started a remerge of the files and then will check after it has finished whether it has been improved.

**Comment by lukasmartinelli** [comment]
Wohooo good news. The remerge fixed the issues and the areas that were missing now are there. Seems some files were just not merged because they were in a other folder at the first merge: dumb mistake.

Currently uploading the files to drive and then I will also merge the lower zoom level tiles into it and put it on the download server as well. But it will take a while until everything is uploaded and updated.

Bad news - the MBTiles files are now even bigger:
- All tiles from z8 to z14: **81GB**
- Tiles from z8 to z14 with water removed: **65GB**

When we do the second rerender and fix the roads this will drop down to the size where it fits on a USB stick again - but until then I would wait ordering them.

**Comment by lukasmartinelli** [comment]
Running `VACUUM` on the database file saves **3GB**. https://sqlite.org/lang_vacuum.html
Now the world file from z0 to z14 with water removed is **62GB**.

**Comment by klokan** [comment]
Cool!

Is the fixed version on downloads.osm2vectortiles.org now?

On Monday, 14 December 2015, Lukas Martinelli <notifications@github.com>
wrote:

> Running VACUUM on the database file saves *3GB*.
> https://sqlite.org/lang_vacuum.html
> Now the world file from z0 to z14 with water removed is *62GB*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osm2vectortiles/osm2vectortiles/issues/87#issuecomment-164510872>
> .
>


-- 
Petr Pridal, Ph.D.
CEO

Klokan Technologies GmbH
Hofnerstrasse 98, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by lukasmartinelli** [comment]
> downloads.osm2vectortiles.org

Have to reupload it again. Missed correct zoom levels in MBTiles metadata.

The downloads.osm2vectortiles.org was actually the same Apache server that also served the vector tiles. So this was more for testing purposes. Now I upload the files directly to Switch S3. Thanks to @manuelroth for finding out how to do that in Switch.

Sadly one cannot associate a domain with Switch S3. The download urls look more like this:
- https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/world_z0-z14_v1.0.mbtiles

I will now start to version the files and start with `v1.0` (even when they actually are from the `v0.2` rendering but the upper level tiles are from the updated version that will be the `v1.0` release this thursday). Files will end with suffix `_v1.0`.

BTW. I cannot upload to Google Drive with rclone - it seems that if I upload the files are counted against **my** quota even when I upload to the Klokantech public folder. Weird issue. I will create a list of all downloads that we then have to mirror to Google Drive.

**Comment by lukasmartinelli** [comment]
The world is already updated on the raster tile server (I repaired the metadata by hand for the world download).
New York is now looking good!! http://rastertiles.osm2vectortiles.org/osm-bright/#11/40.6601/-73.9915

![rastertiles_osm2vectortiles_org_osm-bright__11_40_6601_-73_9915](https://cloud.githubusercontent.com/assets/1288339/11794093/d2da33ea-a2af-11e5-9c73-a00d9ab5a434.png)

What also works now that I have the maskLevel set in the MBTiles is the overzooming into water (previously did not work with tessera).

![4awndzscud](https://cloud.githubusercontent.com/assets/1288339/11794139/2028c8c8-a2b0-11e5-9237-e42cf5346e75.gif)

**Comment by lukasmartinelli** [comment]
> I will now start to version the files and start with v1.0 (even when they actually are from the v0.2 rendering but the upper level tiles are from the updated version that will be the v1.0 release this thursday). Files will end with suffix _v1.0.

Nope. Better idea - versioning makes more sense at a folder level.
Each version will get it's own folder in the download bucket. The extracts of the version
contain the country extracts and the tiles contain the tile pyramid sources (what is now on S3) from which the world.mbtiles is built. The zoom suffixes can be omitted if it is from z0 to z14.

```
.
└── v1.0
    ├── extracts
    │   └── andorra.mbtiles
    ├── tiles
    │   └── 135_147_z8-z14.mbtiles
    └── world.mbtiles
```

**Comment by klokan** [comment]
+1 on versioning vie directory

Are the data on a cloud mashine? And the extracts? I can start upload to
gdrive myself...

On Monday, 14 December 2015, Lukas Martinelli <notifications@github.com>
wrote:

> I will now start to version the files and start with v1.0 (even when they
> actually are from the v0.2 rendering but the upper level tiles are from the
> updated version that will be the v1.0 release this thursday). Files will
> end with suffix _v1.0.
>
> Nope. Better idea - versioning makes more sense at a folder level.
> Each version will get it's own folder in the download bucket. The extracts
> of the version
> contain the country extracts and the tiles contain the tile pyramid
> sources (what is now on S3) from which the world.mbtiles is built. The zoom
> suffixes can be omitted if it is from z0 to z14.
>
> .
> └── v1.0
>     ├── extracts
>     │   └── andorra.mbtiles
>     ├── tiles
>     │   └── 135_147_z8-z14.mbtiles
>     └── world.mbtiles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osm2vectortiles/osm2vectortiles/issues/87#issuecomment-164568327>
> .
>


-- 
Petr Pridal, Ph.D.
CEO

Klokan Technologies GmbH
Hofnerstrasse 98, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by lukasmartinelli** [comment]
> Are the data on a cloud mashine?

Right now this link works for the latest world mbtiles.
https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/world_z0-z14_v1.0.mbtiles

> And the extracts?
Currently "extracting" the extracts.

**Comment by lukasmartinelli** [comment]
The issue with the missing tiles is resolved from my point of view.
