### ISSUE TITLE
Create Extracts

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#88]
- create Extracts for most importants cities, countries

**Comment by lukasmartinelli** [comment]
This is the script to create the all extracts
https://gist.github.com/lukasmartinelli/33385087c01ca5f42487

It makes sense to run multiple once in parallel to speed this up.
Currently running the extracts.

**Comment by lukasmartinelli** [comment]
Extract of Switzerland: https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/switzerland.mbtiles

We plan to merge the world from z0-z4 (20mb or so) into each country mbtiles because it looks a bit weird on lower zoom levels otherwise.

**Comment by lukasmartinelli** [comment]
Extract of Czech Republic: https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/czech_republic.mbtiles

This already contains world z0 to z4.
I've not been able to test the generated extracts yet - would be glad for feedback whether they worked.

**Comment by lukasmartinelli** [comment]
Note to myself:
I need to generate the following extracts later because they are quite large.

```
./tilelive-copy --minzoom=0 --maxzoom=14 --bounds=-179.1591529,-52.9213686,179.4643594,-28.9303302 world.mbtiles extracts/new_zealand.mbtiles
./tilelive-copy --minzoom=0 --maxzoom=14 --bounds=-9.7848145,-54.7539999,34.7891253,81.128076 world.mbtiles extracts/norway.mbtiles
./tilelive-copy --minzoom=0 --maxzoom=14 --bounds=-180.0999999,41.0858711,180.1,82.1586232 world.mbtiles extracts/russian_federation.mbtiles
./tilelive-copy --minzoom=0 --maxzoom=14 --bounds=-180.0999999,-14.8608357,180.1,71.7048217 world.mbtiles extracts/united_states_of_america.mbtiles
./tilelive-copy --minzoom=0 --maxzoom=14 --bounds=-178.4873748,-50.3187168,172.4057152,51.368318 world.mbtiles extracts/france.mbtiles
```

**Comment by lukasmartinelli** [comment]
Except the 5 extracts mentioned the rest of them is available for download at http://osm2vectortiles.org/data/download.html

**Comment by lukasmartinelli** [comment]
Open until #92 is fixed.

**Comment by manuelroth** [comment]
As #92 is closed, this issue can also be closed.
