### ISSUE TITLE
Support mask level for serving vector tiles

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#89]
Tileserver-php does not support mask level yet. There are two ways we can fix it.

1. Mask level is implemented in tileserver-php
2. For the CDN hosting we just use a world.mbtiles that also contain the water tiles

It is not that urgent however, could also be implemented afterwards because people usually don't zoom into water with no reason.

**Comment by klokan** [comment]
Tracked under https://github.com/klokantech/tileserver-php/issues/56
