### ISSUE TITLE
CDN hosting for vector tiles and sample raster maps

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#93]
The CDN is now configured:

http://osm2vectortiles.tileserver.com/v1.json

Our sample maps on CDN as well:

http://klokantech.tileserver.com/

Front page redirects, cleaning of CSS and additional improvements still to be deployed - and everything to be integrated together.

**Comment by klokan** [comment]
MapBox GL JS x-ray viewer for vector tiles:
http://klokantech.github.io/mapbox-gl-js-offline-example/xray.html#http://osm2vectortiles.tileserver.com/v1.json

**Comment by lukasmartinelli** [comment]
Great seeing everything coming along so quickly! :+1: 
Including the website. Now we can reference the CDN in the documentation.

The raster tiles server is based on Klokantech tileserver tessera with a caching proxy in front?
This is amazingly fast.

**Comment by sfkeller** [comment]
I'm flabbergasted...

**Comment by klokan** [comment]
BTW @klokantech team has added also support for open-source static maps requests, like:
http://klokantech.tileserver.com/streets-basic/static/8.82,47.225,15/500x500@2x.png
http://klokantech.tileserver.com/osm-bright/static/8.82,47.225,15/500x500@2x.png

Tomorrow wan't to work on Kitematic friendliness - so that it dead easy to use the docker... even for newbies...

**Comment by lukasmartinelli** [comment]
> BTW @klokantech team has added also support for open-source static maps requests, like:
> http://klokantech.tileserver.com/streets-basic/static/8.82,47.225,15/500x500@2x.png
> http://klokantech.tileserver.com/osm-bright/static/8.82,47.225,15/500x500@2x.png

Now it is almost a Wikimedia Maps replacement! :)

Clarification Questions:
We will host OSM Bright and Streets Classic (and your Retro style) as raster tile examples
on the Klokantech CDN?

The other examples we will continue to serve from a separate server (respectively prerender the raster tiles for small areas)?

**Comment by klokan** [comment]
Yes and Yes.

**Comment by klokan** [comment]
OSM2VectorTiles for sure wins over Wikimedia Maps stack in simplicity of deployment and usage, and in this moment also in quality of the maps :)

Critical is going to be the implementation of incremental updates from planet diffs and of the  gazetteer search - which are both on the roadmap for the follow-up project.
You and Manuel did a great job indeed!

**Comment by daliborjanak** [comment]
You can now crequest links for sample maps on http://maps.klokantech.com/. Key will be send by email

**Comment by manuelroth** [comment]
Thanks, we moved the maps example to http://klokantech-{s}.tileserver.com/ with access key.

**Comment by lukasmartinelli** [comment]
CDN is up and running for the launch. Let's close this so we can close the milestone as well.
If there are additional CDN features we can move them to a new ticket.
