### ISSUE TITLE
create a project file for taginfo  ( for documenting osm tags used by this project )

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#95]
My wish list : please create a taginfo project file  about this awesome project!  :)
    
info:  http://wiki.openstreetmap.org/wiki/Taginfo/Projects

Nominatim example:
* http://taginfo.openstreetmap.org/projects/nominatim#overview
* http://taginfo.openstreetmap.org/projects/nominatim#tags  ( Tags used by this project  )

**Comment by lukasmartinelli** [comment]
Great idea! We will do that, thanks for the suggestion. Alot of knowledge is in the mapping of tags, values and classes.

Below is a diagram visualizing the different mappings to the tables.

![mapping_graph](https://cloud.githubusercontent.com/assets/1288339/11840901/d173e9a6-a3f9-11e5-8d10-37689010bdd3.png)

**Comment by lukasmartinelli** [comment]
Done and waiting until PR is merged.

**Comment by ImreSamu** [comment]
Thanks!

**Comment by ImreSamu** [comment]
http://taginfo.openstreetmap.org/projects/osm2vectortiles#overview

**Comment by lukasmartinelli** [comment]
Hehe yeah. Nice to be listed.
