### ISSUE TITLE
Better UX for Map Examples

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#97]
Use a splitter to choose vector tiles and raster tiles.
Take care of attribution. (OSM attr + Mapbox only link to tm2source)
Back links to repositories.

Update FAQ with link to OSM Copyright http://www.openstreetmap.org/copyright

**Comment by manuelroth** [comment]
- Style Buttons like mapzen https://mapzen.com/projects/vector-tiles
- Height of map plus 100px

**Comment by manuelroth** [comment]
Added attribution "OpenStreeMap contributors"
Moved Vector Tile maps and 3 Raster Tile maps to klokan tileserver (http://klokantech-{s}.tileserver.com/)
The maps demo should now be finished.
